-- changing final table name schema

USE ANALYTICS.CAPITAL_MARKETS;

-- Conentration Limits
SET RISKLIMIT = 0.04;
SET WA_RISK_SCORE = 4.5;
SET TERM_GT_TWENTY_FOUR = 0.2;
SET TERM_GT_TWENTY_FOUR_RISK_RANGE = 0.04;
SET ModifiedReceivablesLimit_CS = 0.05;
SET ModifiedReceivablesLimit_CRB = 0.025;
SET VantageScoreLimit = 0.1;
SET Limit_100K = 0.05;
SET Limit_120K = 0.025;
SET Credit_Limit_Average = 30000;

-- Advance Rate
SET CRBWAM_Advance_Rate = 0.95;
SET CS_Advance_Rate = 0.91;

--Raw Data used for calculations
CREATE OR REPLACE TEMPORARY TABLE FACILITY_BASE2 AS
WITH pledging_dates as (
select edate, lag(edate) over(order by edate asc) as previous_pledge_date from ANALYTICS.CAPITAL_MARKETS.PLEDGE_DATES 
),
BREATHERS AS
(
	SELECT
	    FBBID,
	    FROM_DATE BREATHER_START_DATE,
	    TO_DATE BREATHER_END_DATE,
	    ROUND((EVENT_JSON:breather_days)/7,0) BREATHER_PLAN_COUNT
	FROM BI.FINANCE.DIM_BREATHER_EVENT
	WHERE FROM_DATE IS NOT NULL
),
Repurchased_loan_date AS
(SELECT  LOAN_KEY,
CASE WHEN Set_SPV.FROM_SPV IN ( 'FBX_PT6',  'FBX_PT5','FBX_PT4') AND Set_SPV.TO_SPV =  'FBX_INC' THEN Set_SPV.Edate ELSE NULL end AS "Repurchase Date",
Set_SPV.FROM_SPV,
FROM SETPOINT_APPROVED_REPORT_DATA.RESULTS.REPORT_APPROVAL_RESULTS AS Set_SPV),
MODIFICATIONS AS
(
	SELECT
	    A.LOAN_KEY,
        EDATE,
--        rolling sum
    	SUM(CASE WHEN ACTIVE_PAYMENT_PLAN_NAME IN ('AMOUNT_BASED_QUAD_WEEKLY', 'AMOUNT_BASED_WEEKLY') AND A.EDATE = ACTIVE_PAYMENT_PLAN_START_DATE THEN 1 ELSE 0 END) OVER(PARTITION BY A.LOAN_KEY ORDER BY A.EDATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) CUSTOM_PLAN_COUNT
	    --SUM(DISTINCT CASE WHEN LOAN_OPERATIONAL_STATUS = 'FROZ' THEN 1 ELSE 0 END) OVER(PARTITION BY A.LOAN_KEY ORDER BY A.EDATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) WAIVER_COUNT
--		Least(SUM( CASE WHEN LOAN_OPERATIONAL_STATUS = 'FROZ' THEN 1 ELSE 0 END) OVER(PARTITION BY A.LOAN_KEY ORDER BY A.EDATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),1) WAIVER_COUNT
    	FROM BI.FINANCE.FINANCE_METRICS_DAILY A
),
FBXPLUS AS 
(
    SELECT 
            DACD.FBBID,
            DACD.EDATE,
            1 FBX_PLUS
    FROM BI."PUBLIC".DAILY_APPROVED_CUSTOMERS_DATA DACD
    WHERE UPPER(DACD.FUNDBOX_PLUS_STATUS) LIKE '%SUBSCRIBED%'
    	AND YEAR(EDATE) > 2023
    GROUP BY ALL
),
BK_FRAUD AS
(
	SELECT FBBID,
			EDATE,
			IS_FRAUD,
			BK_FILING_DATE
	FROM BI.PUBLIC.DAILY_APPROVED_CUSTOMERS_DATA
	WHERE YEAR(EDATE) > 2023
	GROUP BY ALL
),
ACQ_CHANNEL_CALC AS
(
	SELECT
		A.FBBID,
		A.LOAN_KEY,
		CASE
			WHEN LOWER(REGEXP_REPLACE(TRIM(CD.REGISTRATION_CAMPAIGN_ID), '\s+\d+$', '')) = LOWER(REGEXP_REPLACE(TRIM(TB.TERMINATED_BROKERS), '\s+\d+$', '')) THEN 'Brokers'
			WHEN PN.PARTNER_NAME = 'Intuit' THEN 'Intuit'
			WHEN LOWER(CD.REGISTRATION_CAMPAIGN_ID) IN ('intuit', 'intuit_appcenter', 'quickbooks-financing', 'intuit_campaigns') OR LOWER(REGISTRATION_CAMPAIGN_ID) LIKE '%intuit%' THEN 'Intuit'
			WHEN PN.PARTNER_NAME = 'Nav' THEN 'NAV'
			WHEN PN.PARTNER_NAME IN ('Lendingtree', 'Lendio') THEN 'Marketplace'
			WHEN LOWER(REGEXP_REPLACE(TRIM(CD.PARTNER_ATTRIBUTION), '\s+\d{4}$', '')) = LOWER(REGEXP_REPLACE(TRIM(PN.PARTNER_ATTRIBUTION), '\s+\d{4}$', '')) THEN 'Strategic Partners'
			WHEN LOWER(REGEXP_REPLACE(TRIM(CD.PARTNER_ATTRIBUTION), '\s+\d{4}$', '')) = LOWER(REGEXP_REPLACE(TRIM(PN.PARTNER_NAME), '\s+\d{4}$', '')) THEN 'Strategic Partners'
			WHEN LOWER(CD.PARTNER_ATTRIBUTION) IN ('organic','content', 'fundboxpay', 'content 100817571549') THEN 'Organic'
	        WHEN LOWER(CD.PARTNER_ATTRIBUTION) LIKE '%direct%' THEN 'Direct'
			WHEN (PN.PARTNER_NAME IS NULL AND CD.PARTNER_ATTRIBUTION IN ('non-partner')) THEN 'Organic'
			WHEN (PN.PARTNER_NAME IS NULL) THEN 'Terminated Channel'
			ELSE 'Brokers'
		END ACQ_CHANNEL
	FROM BI.FINANCE.FINANCE_METRICS_DAILY A
	LEFT JOIN BI."PUBLIC".CUSTOMERS_DATA cd 
	ON CD.FBBID = A.FBBID
	LEFT JOIN ANALYTICS.CREDIT.EG_PA_TO_PN PN 
		ON LOWER(REGEXP_REPLACE(TRIM(CD.PARTNER_ATTRIBUTION), '\s+\d{4}$', '')) = LOWER(REGEXP_REPLACE(TRIM(PN.PARTNER_ATTRIBUTION), '\s+\d{4}$', ''))
			OR LOWER(REGEXP_REPLACE(TRIM(CD.PARTNER_ATTRIBUTION), '\s+\d{4}$', '')) = LOWER(REGEXP_REPLACE(TRIM(PN.PARTNER_NAME), '\s+\d{4}$', ''))
	LEFT JOIN ANALYTICS.CAPITAL_MARKETS.TERMINATED_BROKERS TB
		ON LOWER(REGEXP_REPLACE(TRIM(CD.REGISTRATION_CAMPAIGN_ID), '\s+\d{4}$', '')) = LOWER(REGEXP_REPLACE(TRIM(TB.TERMINATED_BROKERS), '\s+\d{4}$', ''))
	GROUP BY ALL
),
OG_CDC AS (
  SELECT
    D.FBBID,
    D.EDATE,
    LAST_VALUE(CASE WHEN D.RISK_CREDIT_REVIEW_MODEL_NAME IN ('UnifiedOngoingMLEModelV2.2', 'sm-internalmodel_unified_og_v2.2_shap', 'smm-ongoing-SV-v2-2-shap', 'smm-ongoing-SV-v2-2-shap-sbd-v2') 
    	THEN D.RISK_CREDIT_REVIEW_ALIGNED_BUCKET ELSE OG.RETRO_SCORE END) OVER(PARTITION BY D.FBBID, D.EDATE ORDER BY D.EDATE) AS OG_SCORE
  FROM BI.PUBLIC.DAILY_APPROVED_CUSTOMERS_DATA AS d
    LEFT JOIN (
      SELECT
        FBBID,
        SCORE_DT,
        FIRST_VALUE(UNI_BKT) IGNORE NULLS OVER(PARTITION BY FBBID ORDER BY SCORE_DT) AS RETRO_SCORE,
        FIRST_VALUE(OG_SCORE) IGNORE NULLS OVER(PARTITION BY FBBID ORDER BY SCORE_DT) AS SCORE_SPECIFIC
      FROM
        (
          SELECT
            CAST(PREDICTION_TIME AS DATE) AS SCORE_DT,
            IDENTIFIER_ID AS FBBID,
            SCORE AS OG_SCORE,
            CASE
              WHEN SCORE <= 0.016 THEN 1
              WHEN SCORE <= 0.019 THEN 2
              WHEN SCORE <= 0.025 THEN 3
              WHEN SCORE <= 0.03 THEN 4
              WHEN SCORE <= 0.036 THEN 5
              WHEN SCORE <= 0.043 THEN 6
              WHEN SCORE <= 0.052 THEN 7
              WHEN SCORE <= 0.063 THEN 8
              WHEN SCORE <= 0.08 THEN 9
              WHEN SCORE <= 0.11 THEN 10
              WHEN SCORE <= 0.122 THEN 11
              WHEN SCORE <= 0.135 THEN 12
              WHEN SCORE <= 0.156 THEN 13
              WHEN SCORE <= 0.195 THEN 14
              WHEN SCORE <= 1 THEN 15
            END AS UNI_BKT
          FROM CDC_V2.SCORING.SCORING_MODEL_SCORES
          WHERE MODEL_NAME IN ('UnifiedOngoingMLEModelV2.2', 'sm-internalmodel_unified_og_v2.2_shap', 'smm-ongoing-SV-v2-2-shap', 'smm-ongoing-SV-v2-2-shap-sbd-v2')
        )
    ) AS OG 
    ON D.FBBID = OG.FBBID
    	AND D.EDATE = OG.SCORE_DT
),
CDC_OB AS (
  SELECT
    DISTINCT IDENTIFIER_ID AS FBBID,
    CASE
      WHEN SCORE <= 0.01 THEN 1
      WHEN SCORE <= 0.02 THEN 2
      WHEN SCORE <= 0.03 THEN 3
      WHEN SCORE <= 0.04 THEN 4
      WHEN SCORE <= 0.05 THEN 5
      WHEN SCORE <= 0.06 THEN 6
      WHEN SCORE <= 0.07 THEN 7
      WHEN SCORE <= 0.08 THEN 8
      WHEN SCORE <= 0.09 THEN 9
      WHEN SCORE <= 0.1 THEN 10
      WHEN SCORE <= 0.125 THEN 11
      WHEN SCORE <= 0.150 THEN 12
      WHEN SCORE <= 0.175 THEN 13
      WHEN SCORE <= 0.2 THEN 14
      WHEN SCORE <= 1 THEN 15
    END AS CURRENT_ONBOARDING
  FROM CDC_V2.SCORING.SCORING_MODEL_SCORES
  WHERE MODEL_NAME = 'smm-eaglet-SV-dac-v9-9-v3'
  QUALIFY ROW_NUMBER() OVER(PARTITION BY IDENTIFIER_ID ORDER BY PREDICTION_TIME DESC) = 1
)
SELECT
   DISTINCT A.LOAN_KEY,
    A.EDATE,
    DPD_BUCKET,
    DPD_DAYS,
    CHARGEOFF_PRINCIPAL,
    ORIGINAL_TERM,
    "Repurchase Date",
    CASE
    	WHEN ZEROIFNULL(IS_FRAUD) = 1 OR BK_FILING_DATE IS NOT NULL THEN 1
    	ELSE 0
    END BK_FRAUD,             
    FBX_PLUS,
    IS_CHARGED_OFF,
    CHARGE_OFF_DATE,
    RLD.FROM_SPV,
    CASE 
        WHEN UPPER(ORIGINAL_PAYMENT_PLAN_NAME) = 'BUYER_FINANCE_WEEKLY_FIXED' THEN CONCAT(ORIGINAL_TERM, ' Weeks Amortized') WHEN UPPER(ORIGINAL_PAYMENT_PLAN_NAME) LIKE '%TERM_LOAN_24%' THEN '24 Week TL' WHEN UPPER(ORIGINAL_PAYMENT_PLAN_NAME) LIKE '%TERM_LOAN_52%' THEN '52 Week TL' WHEN UPPER(ORIGINAL_PAYMENT_PLAN_NAME) LIKE '%QUAD_WEEKLY_12%' THEN 'Quad Weekly 12 Weeks' WHEN UPPER(ORIGINAL_PAYMENT_PLAN_NAME) LIKE '%QUAD_WEEKLY_24%' THEN 'Quad Weekly 24 Weeks' WHEN UPPER(ORIGINAL_PAYMENT_PLAN_NAME) LIKE '%QUAD_WEEKLY_52%' THEN 'Quad Weekly 52 Weeks' WHEN UPPER(ORIGINAL_PAYMENT_PLAN_NAME) LIKE '%AMORTIZED_12%' THEN '12 Weeks Amortized' WHEN UPPER(ORIGINAL_PAYMENT_PLAN_NAME) LIKE '%AMORTIZED_24%' THEN '24 Weeks Amortized' WHEN UPPER(ORIGINAL_PAYMENT_PLAN_NAME) LIKE '%AMORTIZED_52%' THEN '52 Weeks Amortized' WHEN UPPER(ORIGINAL_PAYMENT_PLAN_NAME) LIKE '%AMORTIZED_12%' THEN '12 Weeks Amortized' WHEN UPPER(ORIGINAL_PAYMENT_PLAN_NAME) LIKE '%BASED_WEEKLY%' THEN 'Custom Weekly' WHEN UPPER(ORIGINAL_PAYMENT_PLAN_NAME) ILIKE '%BASED%QUAD%WEEKLY%' THEN 'Custom Monthly' WHEN UPPER(ORIGINAL_PAYMENT_PLAN_NAME) ILIKE '%WEEKLY%FIXED%' THEN CONCAT(ORIGINAL_TERM, ' Weeks Amortized') WHEN ORIGINAL_PAYMENT_PLAN_NAME IS NULL THEN NULL ELSE ORIGINAL_PAYMENT_PLAN_NAME
    END ORIGINAL_PAYMENT_PLAN,
    CASE 
        WHEN ACTIVE_PAYMENT_PLAN_CONTEXT = 'PAY_EARLY' THEN 'Pay Early Plan' WHEN UPPER(ACTIVE_PAYMENT_PLAN_NAME) = 'BUYER_FINANCE_WEEKLY_FIXED' THEN CONCAT(ACTIVE_PAYMENT_PLAN_DURATION, ' Weeks Amortized') WHEN UPPER(ACTIVE_PAYMENT_PLAN_NAME) LIKE '%TERM_LOAN_24%' THEN '24 Week TL' WHEN UPPER(ACTIVE_PAYMENT_PLAN_NAME) LIKE '%TERM_LOAN_52%' THEN '52 Week TL' WHEN UPPER(ACTIVE_PAYMENT_PLAN_NAME) LIKE '%QUAD_WEEKLY_12%' THEN 'Quad Weekly 12 Weeks' WHEN UPPER(ACTIVE_PAYMENT_PLAN_NAME) LIKE '%QUAD_WEEKLY_24%' THEN 'Quad Weekly 24 Weeks' WHEN UPPER(ACTIVE_PAYMENT_PLAN_NAME) LIKE '%QUAD_WEEKLY_52%' THEN 'Quad Weekly 52 Weeks' WHEN UPPER(ACTIVE_PAYMENT_PLAN_NAME) LIKE '%AMORTIZED_12%' THEN '12 Weeks Amortized' WHEN UPPER(ACTIVE_PAYMENT_PLAN_NAME) LIKE '%AMORTIZED_24%' THEN '24 Weeks Amortized' WHEN UPPER(ACTIVE_PAYMENT_PLAN_NAME) LIKE '%AMORTIZED_52%' THEN '52 Weeks Amortized' WHEN UPPER(ACTIVE_PAYMENT_PLAN_NAME) LIKE '%AMORTIZED_12%' THEN '12 Weeks Amortized' WHEN UPPER(ACTIVE_PAYMENT_PLAN_NAME) LIKE '%BASED_WEEKLY%' THEN 'Custom Weekly' WHEN UPPER(ACTIVE_PAYMENT_PLAN_NAME) ILIKE '%BASED%QUAD%WEEKLY%' THEN 'Custom Monthly' WHEN UPPER(ACTIVE_PAYMENT_PLAN_NAME) ILIKE '%WEEKLY%FIXED%' THEN CONCAT(ACTIVE_PAYMENT_PLAN_DURATION, ' Weeks Amortized') WHEN ACTIVE_PAYMENT_PLAN_NAME IS NULL THEN NULL ELSE ACTIVE_PAYMENT_PLAN_NAME 
    END ACTIVE_PAYMENT_PLAN,
    CASE 
        WHEN UPPER(ACTIVE_PAYMENT_PLAN_NAME) LIKE '%BASED%' THEN ACTIVE_PAYMENT_PLAN ELSE ORIGINAL_PAYMENT_PLAN
    END PAYMENT_PLAN,
     CASE
    	WHEN PAYMENT_PLAN IN  ('Quad Weekly 12 Weeks', 'Quad Weekly 24 Weeks','Quad Weekly 52 Weeks', 'Custom Monthly')  THEN 1
    	ELSE 0
    END QUAD_WEEKLY, 
    CASE
    	WHEN OWNERSHIP_DATE IS NOT NULL AND LOAN_CREDITED_DATE IS NOT NULL THEN 1
    	ELSE 0
    END FBX_OWNED,
    CASE
	    WHEN A.EDATE > '1/31/2025' THEN COALESCE(TO_SPV, SPV::STRING)
		WHEN (A.EDATE < CRB_REPURCHASES.REPURCHASE_WEEK OR  CRB_REPURCHASES.REPURCHASE_WEEK IS NULL) AND CRB_PLEDGED.TRANSFER_DATE <= A.EDATE THEN 'FBX_PT6'
		WHEN A.EDATE >= DATEADD(DAY, 1 - DAYOFWEEK(CS_PLEDGED.TRANSFER_DATE), CS_PLEDGED.TRANSFER_DATE) AND DATEADD(DAY, 1 - DAYOFWEEK(CS_PLEDGED.TRANSFER_DATE), CS_PLEDGED.TRANSFER_DATE) > DATEADD(DAY, 1 - DAYOFWEEK(CS_REPURCHASESV2.REPURCHASE_WEEK), CS_REPURCHASESV2.REPURCHASE_WEEK)  THEN 'FBX_PT5'
		--                    IF repurchased BY cs THEN fbx inc
		WHEN A.EDATE >= DATEADD(DAY, 1 - DAYOFWEEK(CS_REPURCHASESV2.REPURCHASE_WEEK), CS_REPURCHASESV2.REPURCHASE_WEEK) THEN 'FBX_INC'
		--                    IF repurchased BY crb and not transfered to cs THEN fbx inc
		WHEN A.EDATE >= DATEADD(DAY, 1 - DAYOFWEEK(CRB_REPURCHASES.REPURCHASE_WEEK), CRB_REPURCHASES.REPURCHASE_WEEK) AND A.EDATE < DATEADD(DAY, 1 - DAYOFWEEK(CS_PLEDGED.TRANSFER_DATE), CS_PLEDGED.TRANSFER_DATE) THEN 'FBX_INC'
		--                    IF pledged to crb and not transfered to cs then crb
		   -- WHEN A.EDATE >= DATEADD(DAY, 1 - DAYOFWEEK(CRB_PLEDGED.TRANSFER_DATE), CRB_PLEDGED.TRANSFER_DATE) AND A.EDATE < DATEADD(DAY, 1 - DAYOFWEEK(CS_PLEDGED.TRANSFER_DATE), CS_PLEDGED.TRANSFER_DATE) THEN 'FBX_PT6'
		--                    IF pledged to cs and not yet repurchased by cs then cs
		WHEN A.EDATE >= DATEADD(DAY, 1 - DAYOFWEEK(CS_PLEDGED.TRANSFER_DATE), CS_PLEDGED.TRANSFER_DATE) AND A.EDATE < DATEADD(DAY, 1 - DAYOFWEEK(CS_REPURCHASESV2.REPURCHASE_WEEK), CS_REPURCHASESV2.REPURCHASE_WEEK) THEN 'FBX_PT5'
		--                    IF pledged to cs, not repurchased by cs or transferred to crb then cs
		WHEN A.EDATE >= DATEADD(DAY, 1 - DAYOFWEEK(CS_PLEDGED.TRANSFER_DATE), CS_PLEDGED.TRANSFER_DATE) AND A.EDATE <= MAX(CASE WHEN SPV::STRING = 'FBX_PT5' THEN A.EDATE END) OVER(PARTITION BY A.LOAN_KEY) THEN 'FBX_PT5'
		--                    IF pledged to crb, not repurchased by crb or transferred to cs then crb
		  --  WHEN A.EDATE >= DATEADD(DAY, 1 - DAYOFWEEK(CRB_PLEDGED.TRANSFER_DATE), CRB_PLEDGED.TRANSFER_DATE) AND A.EDATE <= MAX(CASE WHEN SPV::STRING = 'FBX_PT6' THEN A.EDATE END) OVER(PARTITION BY A.LOAN_KEY) THEN 'FBX_PT6'
		--                    If Loan is pledged on cutoff day(or within 3 days greater) then CS
	   	WHEN (DATEDIFF(DAY, DATEADD(DAY, 1 - DAYOFWEEK(CS_PLEDGED.TRANSFER_DATE), CS_PLEDGED.TRANSFER_DATE), A.EDATE) BETWEEN 0 AND 3) AND DATEADD(DAY, 1 - DAYOFWEEK(CS_REPURCHASESV2.REPURCHASE_WEEK), CS_REPURCHASESV2.REPURCHASE_WEEK) IS NULL THEN 'FBX_PT5'
		--                    IF PIMCO then PIMCO
		WHEN SPV::STRING = 'FBX_PT4' THEN 'FBX_PT4'
		ELSE 'FBX_INC'
    END ACTUAL_SPV,
    CRB_REPURCHASES.REPURCHASE_WEEK CRB_REPURCHASED,
    CS_REPURCHASESV2.REPURCHASE_WEEK CS_REPURCHASED,
    CASE
	    WHEN A.EDATE > '1/31/2025' AND "Repurchase Date" <= A.EDATE THEN 1
    	WHEN A.EDATE <= '1/31/2025' AND CRB_REPURCHASES.REPURCHASE_WEEK <= A.EDATE or CS_REPURCHASESV2.REPURCHASE_WEEK <= A.EDATE THEN 1
    	WHEN A.EDATE <= '1/31/2025' AND ((CRB_REPURCHASED > A.EDATE OR CRB_REPURCHASED IS NULL) AND (CS_REPURCHASED > A.EDATE OR CS_REPURCHASED IS NULL)) THEN 0
    	ELSE 0
    END REPURCHASED,
    CASE
	    WHEN A.EDATE > '1/31/2025' AND "Repurchase Date" <= A.EDATE THEN 1
    	WHEN A.EDATE <= '1/31/2025' AND CRB_REPURCHASES.REPURCHASE_WEEK <= A.EDATE THEN 1
    	WHEN A.EDATE <= '1/31/2025' AND ((CRB_REPURCHASED > A.EDATE OR CRB_REPURCHASED IS NULL) AND (CS_REPURCHASED > A.EDATE OR CS_REPURCHASED IS NULL)) THEN 0
    	ELSE 0
    END "Repurchased CRB",
    CASE
	    WHEN A.EDATE > '1/31/2025' AND "Repurchase Date" <= A.EDATE THEN 1
    	WHEN A.EDATE <= '1/31/2025' AND CS_REPURCHASESV2.REPURCHASE_WEEK <= A.EDATE THEN 1
    	WHEN A.EDATE <= '1/31/2025' AND ((CRB_REPURCHASED > A.EDATE OR CRB_REPURCHASED IS NULL) AND (CS_REPURCHASED > A.EDATE OR CS_REPURCHASED IS NULL)) THEN 0
    	ELSE 0
    END "Repurchased ATLAS",
    CASE
    	WHEN PAYMENT_PLAN IN ('Quad Weekly 12 Weeks', 'Quad Weekly 24 Weeks','Quad Weekly 52 Weeks', 'Custom Monthly') AND zeroifnull(DPD_BUCKET) > 1 THEN 1
    	WHEN PAYMENT_PLAN NOT IN ('Quad Weekly 12 Weeks', 'Quad Weekly 24 Weeks','Quad Weekly 52 Weeks', 'Custom Monthly') AND zeroifnull(DPD_BUCKET) > 3 THEN 1
    	ELSE 0
    END MPFQUALIFICATION,
    CS_DEBT_DRAWN,
    CRB_DEBT_DRAWN,
    RESTRICTED_CASH_CRB,
    RESTRICTED_CASH_CS,
    OUTSTANDING_PRINCIPAL_FUNDED,
    CREDIT_LIMIT,
    CASE
    	WHEN UPPER(SUB_PRODUCT) LIKE '%LINE%' THEN 1
    	ELSE 0
    END LOC,
    BREATHER_PLAN_COUNT,
    IS_IN_BREATHER,
    CASE
        WHEN LOAN_OPERATIONAL_STATUS = 'FROZ' THEN 1 ELSE 0
    END WAIVER_COUNT,
    CASE
    	WHEN (CUSTOM_PLAN_COUNT+WAIVER_COUNT+(CASE WHEN ZEROIFNULL(BREATHER_PLAN_COUNT) > 2 THEN 1 ELSE 0 END)) > 1 THEN 1
    	ELSE 0
    END CS_MATERIAL_MODIFICATION,
    CASE
    	WHEN (CUSTOM_PLAN_COUNT+WAIVER_COUNT+ZEROIFNULL(BREATHER_PLAN_COUNT)) > 1 THEN 1
    	ELSE 0
    END CRB_MATERIAL_MODIFICATION,
    CASE
    	WHEN (QUAD_WEEKLY = 1 and zeroifnull(FBX_PLUS) = 0) THEN 1
    	ELSE 0
    END PAYMENT_FREQUENCY,
    CASE
        WHEN DATEDIFF('day', FIRST_APPROVED_DATE, LOAN_CREATED_DATE) >= 30 
        THEN OG_SCORE
    END OG_SCORING,
    CASE
        WHEN ORIGINAL_TERM = 52 AND DATEDIFF('day', FIRST_APPROVED_DATE, LOAN_CREATED_DATE) >= 30 THEN 0
        WHEN ORIGINAL_TERM = 52 AND DATEDIFF('day', FIRST_APPROVED_DATE, LOAN_CREATED_DATE) < 30 THEN 1
        ELSE 0
    END NEW_OR_EXISTING,
    coalesce(OB_TO_USE,CURRENT_ONBOARDING)  as Ob_score_to_use,
    COALESCE(CSR.Risk_score, june.risk_score, OG_SCORE, Ob_score_to_use) RISK_SCORE_TRUE,
    CASE
    	WHEN RISK_SCORE_TRUE >=13 THEN 1
    	ELSE 0
    END "Risk Score >=13",
    ZEROIFNULL(CASE
    	WHEN ORIGINAL_TERM = 52 THEN 1
    	ELSE 0
    END) "52W Allocation",
    ZEROIFNULL(CASE
    	WHEN ORIGINAL_TERM = 52 AND RISK_SCORE_TRUE BETWEEN 5 AND 8 THEN 1
    	ELSE 0
    END) "52W Risk Score",
    CASE
    	WHEN RISK_SCORE_TRUE >=13 AND A.ORIGINAL_TERM >= 24 THEN 1
    	ELSE 0
    END "Oterm >= 24 and Risk Score >=13" ,
    CASE
	    WHEN (CS_MATERIAL_MODIFICATION + PAYMENT_FREQUENCY + MPFQUALIFICATION + BK_FRAUD + 
	         (CASE WHEN (Original_Term = 52 AND ZEROIFNULL(FBX_PLUS) = 0) THEN 1 ELSE 0 END)
	         ) = 0
	    THEN 1
	    ELSE 0
	END AS CS_Eligible,
	CASE
		WHEN ORIGINAL_TERM = 52 AND ACQ_CHANNEL IN ('Organic', 'Direct') THEN 1
		ELSE 0
	END ACQ_CHANNEL_FIFTY_TWO,
	CASE
		WHEN ORIGINAL_TERM = 52 AND ZEROIFNULL(Ob_score_to_use) > 7 THEN 1
		WHEN ORIGINAL_TERM = 52 AND ZEROIFNULL(RISK_SCORE_TRUE) <= 8 THEN 0
		ELSE 0
	END RISK_SCORE_FIFTY_TWO,	
    CASE 
    	WHEN CRB_MATERIAL_MODIFICATION = 0 AND PAYMENT_FREQUENCY = 0 AND MPFQUALIFICATION = 0 AND BK_FRAUD = 0 AND ACQ_CHANNEL_FIFTY_TWO = 0 and CREDIT_LIMIT <= 150000 THEN 1
    	ELSE 0
    END CRB_Eligible,
    CASE 
    	WHEN CREDIT_LIMIT > 100000 THEN 1
    	ELSE 0
    END Credit_limit_100K,
    CASE 
    	WHEN CREDIT_LIMIT > 120000 THEN 1
    	ELSE 0
    END Credit_limit_120K,
    CUSTOM_PLAN_COUNT + WAIVER_COUNT + ZEROIFNULL(BREATHER_PLAN_COUNT) AS  "Total Modifications",
    ZEROIFNULL(GET(GET(PARSE_JSON(REGEXP_REPLACE(DACD.CREDIT_SCORE_JSON::VARCHAR , 'VantageScore [0-9].[0-9]', 'VantageScore')),'VantageScore'),'score')) AS "Vantage Score",
    previous_pledge_date AS "Previous Pledge Date"
FROM pledging_dates PD
LEFT JOIN BI.FINANCE.FINANCE_METRICS_DAILY A
		ON PD.EDATE = A.EDATE
LEFT JOIN ANALYTICS.CAPITAL_MARKETS.CS_PLEDGED
       	ON A.LOAN_KEY = CS_PLEDGED.LOAN_KEY
LEFT JOIN ANALYTICS.CAPITAL_MARKETS.CS_REPURCHASESV2
		ON A.LOAN_KEY = CS_REPURCHASESV2.LOAN_KEY
LEFT JOIN ANALYTICS.CAPITAL_MARKETS.CRB_PLEDGED
		ON A.LOAN_KEY = CRB_PLEDGED.LOAN_KEY
LEFT JOIN ANALYTICS.CAPITAL_MARKETS.CRB_REPURCHASES
		ON A.LOAN_KEY = CRB_REPURCHASES.LOAN_KEY
LEFT JOIN FBXPLUS
        ON A.FBBID = FBXPLUS.FBBID AND A.LOAN_CREATED_DATE = FBXPLUS.EDATE
LEFT JOIN MODIFICATIONS 
		ON A.LOAN_KEY = MODIFICATIONS.LOAN_KEY AND A.EDATE = MODIFICATIONS.EDATE
LEFT JOIN BREATHERS
	    ON A.FBBID = BREATHERS.FBBID AND A.EDATE >= BREATHERS.BREATHER_START_DATE AND A.EDATE <= BREATHERS.BREATHER_END_DATE
LEFT JOIN BK_FRAUD
		ON A.FBBID = BK_FRAUD.FBBID AND A.LOAN_CREATED_DATE = BK_FRAUD.EDATE
LEFT JOIN ANALYTICS.CAPITAL_MARKETS.ACTUAL_DEBT_DRAWN ADDD
		ON A.EDATE = ADDD.EDATE
LEFT JOIN ANALYTICS.CAPITAL_MARKETS.RESTRICTED_CASH RC 
		ON A.EDATE = RC.EDATE
LEFT JOIN ACQ_CHANNEL_CALC
		ON ACQ_CHANNEL_CALC.LOAN_KEY = A.LOAN_KEY
LEFT JOIN SETPOINT_APPROVED_REPORT_DATA.RESULTS.REPORT_APPROVAL_RESULTS SETPOINT_SPV
	ON A.LOAN_KEY = SETPOINT_SPV.LOAN_KEY AND A.EDATE = SETPOINT_SPV.EDATE
LEFT JOIN (SELECT FBBID, EDATE, SUB_PRODUCT, RISK_CREDIT_REVIEW_ALIGNED_BUCKET, RISK_CREDIT_REVIEW_MODEL_NAME, RISK_CREDIT_REVIEW_MODEL_SCORE, FIRST_APPROVED_TIME::DATE FIRST_APPROVED_DATE, CREDIT_SCORE_JSON, IS_IN_BREATHER, CREDIT_LIMIT FROM BI.PUBLIC.DAILY_APPROVED_CUSTOMERS_DATA) DACD
        ON A.FBBID = DACD.FBBID AND A.LOAN_CREATED_DATE = DACD.EDATE
LEFT JOIN OG_CDC AS BS 
	ON A.FBBID = BS.FBBID AND A.LOAN_CREATED_DATE = BS.EDATE
LEFT JOIN CDC_OB AS COB 
	ON A.FBBID = COB.FBBID
LEFT JOIN Repurchased_loan_date RLD ON A.loan_key = RLD.loan_key AND A.Edate = RLD."Repurchase Date"
left join (select loan_key, risk_score, FBBID from ANALYTICS.CAPITAL_MARKETS.DATA_ROOM_LOAN_TAPE_JUNE2025) JUNE
    on June.loan_key = A.loan_key
left join ANALYTICS.CAPITAL_MARKETS.CS_RISK_SCORES CSR
    on CSR.loan_key = A.loan_key
left join ANALYTICS.CAPITAL_MARKETS.OB_SCORES OBS
                on OBS.loan_key = A.loan_key;


--Credit Suisse Atlas & LibreMax (FBX_PT5)
CREATE OR REPLACE TEMPORARY TABLE CSALM AS
SELECT
	EDATE,
    CASE WHEN DAYNAME(edate) = 'Wednesday' THEN edate  ELSE NEXT_DAY(edate, 'WEDNESDAY') END AS WEEK_END_DATE,

	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND FBX_OWNED = 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) FBX_RECEIVABLES,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_PT5' THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) ATLAS_PLEDGED_RECEIVABLES_CS,
	ATLAS_PLEDGED_RECEIVABLES_CS/ FBX_RECEIVABLES as PER_PLEDGED_TO_ATLAS,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_PT5' and CS_Eligible = 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) ELIGIBLE_RECEIVABLES_ATLAS,
	ELIGIBLE_RECEIVABLES_ATLAS / ATLAS_PLEDGED_RECEIVABLES_CS AS PER_ELIGIBLE_CS,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_PT5' AND CS_eligible = 1 AND "Risk Score >=13" = 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END ),2) RISKSCOREGG13_TOTAL_CS,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_PT5' AND CS_eligible = 1 AND "Total Modifications" > 0 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END ),2) MODIFICATIONS_TOTAL_CS,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_PT5' AND CS_eligible = 1 AND "Oterm >= 24 and Risk Score >=13" = 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END ),2) "Oterm >= 24 and Risk Score >=13 Total",
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_PT5' AND CS_eligible = 1 AND Credit_limit_100K = 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END ),2) CREDITLIMITG$100K_CS,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_PT5' AND CS_eligible = 1 AND Credit_limit_120K = 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END ),2) CREDITLIMITG$120K_CS,
	RISKSCOREGG13_TOTAL_CS / ELIGIBLE_RECEIVABLES_ATLAS AS PER_RISK_SCOREGG13_CS,
	MODIFICATIONS_TOTAL_CS / ELIGIBLE_RECEIVABLES_ATLAS AS PER_MODIFICATIONS_CS,
	CREDITLIMITG$100K_CS / ELIGIBLE_RECEIVABLES_ATLAS AS PER_CREDITLIMITG$100K_CS,
	CREDITLIMITG$120K_CS / ELIGIBLE_RECEIVABLES_ATLAS AS PER_CREDITLIMITG$120K_CS,
	round(CASE WHEN PER_RISK_SCOREGG13_CS > $RISKLIMIT THEN (PER_RISK_SCOREGG13_CS - $RISKLIMIT) * ELIGIBLE_RECEIVABLES_ATLAS ELSE 0 END +  
	CASE WHEN PER_MODIFICATIONS_CS > $ModifiedReceivablesLimit_CS THEN (PER_MODIFICATIONS_CS - $ModifiedReceivablesLimit_CS) * ELIGIBLE_RECEIVABLES_ATLAS ELSE 0 END +
	CASE WHEN PER_CREDITLIMITG$100K_CS > $Limit_100K THEN (PER_CREDITLIMITG$100K_CS - $Limit_100K) * ELIGIBLE_RECEIVABLES_ATLAS ELSE 0 END +
	CASE WHEN PER_CREDITLIMITG$120K_CS > $Limit_120K THEN (PER_CREDITLIMITG$120K_CS - $Limit_120K) * ELIGIBLE_RECEIVABLES_ATLAS ELSE 0 END,2) as RECEIVABLESINCONCENTRATIONLIMITS_CS,
	RECEIVABLESINCONCENTRATIONLIMITS_CS / ELIGIBLE_RECEIVABLES_ATLAS AS PER_EXCESSCONCENTRATION_CS,
	ROUND( ((ELIGIBLE_RECEIVABLES_ATLAS - RECEIVABLESINCONCENTRATIONLIMITS_CS) * .025) ,2) AS YSOC,
	round((ELIGIBLE_RECEIVABLES_ATLAS - RECEIVABLESINCONCENTRATIONLIMITS_CS - YSOC) * $CS_Advance_Rate,2) AS TOTALBORROWINGBASE_CS,
	(YSOC / ELIGIBLE_RECEIVABLES_ATLAS) YSOCPER,
	TOTALBORROWINGBASE_CS / ATLAS_PLEDGED_RECEIVABLES_CS AS EFFECTIVE_LEVERAGE_CS,
	ZEROIFNULL(CS_DEBT_DRAWN) AS TOTAL_DEBT_DRAWN_CS,
	TOTAL_DEBT_DRAWN_CS / ATLAS_PLEDGED_RECEIVABLES_CS as REALIZED_LEVERAGE_CS,
	RESTRICTED_CASH_CS AS RESTRICTEDCASH_CS,
	(TOTAL_DEBT_DRAWN_CS - RESTRICTEDCASH_CS ) / ATLAS_PLEDGED_RECEIVABLES_CS AS CASH_ADJUSTEDLEVERAGE_CS,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0   AND FROM_SPV = 'FBX_PT5' AND ("Repurchase Date" = EDATE)  THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) REPURCHASEDRECEIVABLESATLAS,
	REPURCHASEDRECEIVABLESATLAS / ATLAS_PLEDGED_RECEIVABLES_CS as PER_REPURCHASEDRECEVIABLES_CS,
	ROUND(SUM(CASE WHEN (CHARGE_OFF_DATE > "Previous Pledge Date" AND CHARGE_OFF_DATE <= EDATE) AND ACTUAL_SPV = 'FBX_PT5'  AND "Repurchased ATLAS" = 0  THEN CHARGEOFF_PRINCIPAL ELSE 0 END),2) CORECEIVABLESATLAS,
	CORECEIVABLESATLAS / ATLAS_PLEDGED_RECEIVABLES_CS AS PER_CHARGED_OFF_CS,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0  AND ACTUAL_SPV = 'FBX_PT5' AND "Repurchased ATLAS" = 0 AND zeroifnull(DPD_DAYS) >21 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) DELINQUENTRECEIVABLESDPD21PLUS_CS,
	DELINQUENTRECEIVABLESDPD21PLUS_CS / ATLAS_PLEDGED_RECEIVABLES_CS AS PER_DELINQUENT_CS,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0  AND ACTUAL_SPV = 'FBX_PT5' AND "Repurchased ATLAS" = 0 AND zeroifnull(DPD_DAYS) <=21  AND zeroifnull(FBX_PLUS) = 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) F52WEEKSRECEIVABLESANDNOTFUNDBOXPLUS_CS,
	F52WEEKSRECEIVABLESANDNOTFUNDBOXPLUS_CS / ATLAS_PLEDGED_RECEIVABLES_CS AS PER_52WEEKSANDNOTFUNDBOXPLUS_CS, 
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0  AND ACTUAL_SPV = 'FBX_PT5' AND "Repurchased ATLAS" = 0 AND zeroifnull(DPD_DAYS) <=21  AND zeroifnull(FBX_PLUS) <> 1 AND CS_MATERIAL_MODIFICATION = 1  THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) MATERIALMODS_CS,
	MATERIALMODS_CS / ATLAS_PLEDGED_RECEIVABLES_CS AS PER_MATERIALMODS_CS,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0  AND ACTUAL_SPV = 'FBX_PT5' AND "Repurchased ATLAS" = 0 AND zeroifnull(DPD_DAYS) <=21  AND 
(FBX_PLUS) <> 1 AND CS_MATERIAL_MODIFICATION <> 1 AND zeroifnull(IS_IN_BREATHER) = 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) BREATHERS_CS,
	BREATHERS_CS / nullifzero(ATLAS_PLEDGED_RECEIVABLES_CS) AS PER_BREATHERS_CS,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_PT5' and CS_Eligible = 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END * Nullifzero("Vantage Score")  ) /SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_PT5' AND CS_Eligible = 1 AND "Vantage Score"<> 0 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END ) ,2)  WAVANATAGESCORE_CS,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_PT5' and CS_Eligible = 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END * RISK_SCORE_TRUE   ) / ELIGIBLE_RECEIVABLES_ATLAS,2) AS WARISKSCORE_CS,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_PT5' and CS_Eligible = 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END * Original_Term   ) / ELIGIBLE_RECEIVABLES_ATLAS,2) AS WATERM_CS
FROM FACILITY_BASE2
WHERE EDATE > '10/1/2024'
GROUP BY ALL
ORDER BY 1 ASC;


--Cross River Bank & Waterfall Asset Management (FBX_PT6)
CREATE OR REPLACE TEMPORARY TABLE CRBWAM AS
SELECT
	EDATE,
    CASE WHEN DAYNAME(edate) = 'Wednesday' THEN edate  ELSE NEXT_DAY(edate, 'WEDNESDAY') END AS WEEK_END_DATE,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND FBX_OWNED = 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) FBX_RECEIVABLES,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_PT6' THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) CRBPLEDGEDRECEIVABLES,
	CRBPLEDGEDRECEIVABLES/ FBX_RECEIVABLES as PER_PLEDGEDTOCRBWAM,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_PT6' and CRB_Eligible = 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) ELIGIBLERECEIVABLESCRBWAM,
    ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_PT6' and CRB_Eligible = 1 and ORIGINAL_TERM = 52 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) "Eligible Receivables 52W CRBWAM",
	ELIGIBLERECEIVABLESCRBWAM / CRBPLEDGEDRECEIVABLES AS PER_ELIGIBLE_CR,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_PT6' AND CRB_eligible = 1 AND "Risk Score >=13" = 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END ),2) RISKSCOREGG13_TOTAL_CR,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_PT6' AND CRB_eligible = 1 AND "Total Modifications" > 0  THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END ),2) MODIFICATIONS_TOTAL_CR,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_PT6' AND CRB_eligible = 1 AND "Vantage Score" = 0 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END ),2) VANTAGESCOREISZEROTOTAL_CR,
	ROUND(AVG(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_PT6' AND CRB_eligible = 1 AND OUTSTANDING_PRINCIPAL_FUNDED > 0  THEN CREDIT_LIMIT ELSE NULL END ),2) AVERAGECREDITLIMIT_CR,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_PT6' AND CRB_eligible = 1 AND Credit_limit_120K = 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END ),2) CREDITLIMITG$120K_CR,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_PT6' AND CRB_eligible = 1 AND ORIGINAL_TERM = 52 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END ),2) "52W Allocation Total",
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_PT6' AND CRB_eligible = 1 AND RISK_SCORE_FIFTY_TWO = 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END ),2) "52W Risk Score Total",
	RISKSCOREGG13_TOTAL_CR / ELIGIBLERECEIVABLESCRBWAM AS PER_RISK_SCOREGG13_CR,
	MODIFICATIONS_TOTAL_CR / ELIGIBLERECEIVABLESCRBWAM AS PER_MODIFICATIONS_CR,
	VANTAGESCOREISZEROTOTAL_CR / ELIGIBLERECEIVABLESCRBWAM AS PER_VANTAGESCOREISZERO_CR,
	CREDITLIMITG$120K_CR / ELIGIBLERECEIVABLESCRBWAM AS PER_CREDITLIMITG$120K_CR,
	NULLIFZERO("52W Allocation Total") / ELIGIBLERECEIVABLESCRBWAM AS PER_52W,
	NULLIFZERO("52W Risk Score Total") / ELIGIBLERECEIVABLESCRBWAM AS PER_52W_RISKSCORE,
	ROUND(CASE WHEN PER_RISK_SCOREGG13_CR > $RISKLIMIT THEN (PER_RISK_SCOREGG13_CR - $RISKLIMIT) * ELIGIBLERECEIVABLESCRBWAM ELSE 0 END +  
	CASE WHEN PER_MODIFICATIONS_CR > $ModifiedReceivablesLimit_CRB THEN (PER_MODIFICATIONS_CR - $ModifiedReceivablesLimit_CRB) * ELIGIBLERECEIVABLESCRBWAM ELSE 0 END +
	CASE WHEN PER_VANTAGESCOREISZERO_CR > $VantageScoreLimit THEN (PER_VANTAGESCOREISZERO_CR - $VantageScoreLimit) * ELIGIBLERECEIVABLESCRBWAM ELSE 0 END +
	CASE WHEN AVERAGECREDITLIMIT_CR > $Credit_Limit_Average THEN (AVERAGECREDITLIMIT_CR - $Credit_Limit_Average) * ELIGIBLERECEIVABLESCRBWAM ELSE 0 END +
	CASE WHEN PER_CREDITLIMITG$120K_CR > $Limit_120K THEN (PER_CREDITLIMITG$120K_CR - $Limit_120K) * ELIGIBLERECEIVABLESCRBWAM ELSE 0 END +
	CASE WHEN PER_52W > $TERM_GT_TWENTY_FOUR THEN (PER_52W - $TERM_GT_TWENTY_FOUR) * ELIGIBLERECEIVABLESCRBWAM ELSE 0 END +
	CASE WHEN ZEROIFNULL(PER_52W_RISKSCORE) > $TERM_GT_TWENTY_FOUR_RISK_RANGE THEN (ZEROIFNULL(PER_52W_RISKSCORE) - $TERM_GT_TWENTY_FOUR_RISK_RANGE) * ELIGIBLERECEIVABLESCRBWAM ELSE 0 END,2) as RECEIVABLESINCONCENTRATIONLIMITS_CR,
	RECEIVABLESINCONCENTRATIONLIMITS_CR / ELIGIBLERECEIVABLESCRBWAM AS PER_EXCESSCONCENTRATION_CR,
	Round((ELIGIBLERECEIVABLESCRBWAM - RECEIVABLESINCONCENTRATIONLIMITS_CR) * $CRBWAM_Advance_Rate,2)  AS TOTALBORROWINGBASE_CR,
	TOTALBORROWINGBASE_CR / CRBPLEDGEDRECEIVABLES AS EFFECTIVE_LEVERAGE_CR,
	ZEROIFNULL(CRB_DEBT_DRAWN) AS TOTAL_DEBT_DRAWN_CR,
	TOTAL_DEBT_DRAWN_CR / CRBPLEDGEDRECEIVABLES as REALIZED_LEVERAGE_CR,
	-- need to switch this to CRBWAM only when possible
	RESTRICTED_CASH_CRB AS RESTRICTEDCASH_CRB,
	(TOTAL_DEBT_DRAWN_CR - RESTRICTEDCASH_CRB ) / CRBPLEDGEDRECEIVABLES AS CASH_ADJUSTEDLEVERAGE_CRB,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0  AND FROM_SPV = 'FBX_PT6' AND ("Repurchase Date" = EDATE)  THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) REPURCHASEDRECEIVABLESCRBWAM, --("Repurchase Date" > "Previous Pledge Date" AND "Repurchase Date" <= EDATE)
	REPURCHASEDRECEIVABLESCRBWAM / CRBPLEDGEDRECEIVABLES as PER_REPURCHASEDRECEVIABLES_CR,
	ROUND(SUM(CASE WHEN (CHARGE_OFF_DATE > "Previous Pledge Date" AND CHARGE_OFF_DATE <= EDATE)   AND ACTUAL_SPV = 'FBX_PT6' AND "Repurchased CRB" = 0  THEN CHARGEOFF_PRINCIPAL ELSE 0 END),2) CORECEIVABLESCRBWAM,
	CORECEIVABLESCRBWAM / CRBPLEDGEDRECEIVABLES AS PER_CHARGED_OFF_CR,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0  AND ACTUAL_SPV = 'FBX_PT6' AND "Repurchased CRB" = 0 AND zeroifnull(DPD_DAYS) >21 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) DELINQUENTRECEIVABLESDPD21PLUS_CR,
	DELINQUENTRECEIVABLESDPD21PLUS_CR / CRBPLEDGEDRECEIVABLES AS PER_DELINQUENT_CR,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0  AND ACTUAL_SPV = 'FBX_PT6' AND "Repurchased CRB" = 0 AND zeroifnull(DPD_DAYS) <=21  AND zeroifnull(FBX_PLUS) = 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) F52WEEKSRECEIVABLESANDNOTFUNDBOXPLUS_CR,
	F52WEEKSRECEIVABLESANDNOTFUNDBOXPLUS_CR / CRBPLEDGEDRECEIVABLES AS PER_52WEEKSANDNOTFUNDBOXPLUS_CR, 
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0   AND ACTUAL_SPV = 'FBX_PT6' AND "Repurchased CRB" = 0 AND zeroifnull(DPD_DAYS) <=21  AND zeroifnull(FBX_PLUS) <> 1 AND CRB_MATERIAL_MODIFICATION = 1  THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) MATERIALMODS_CR,
	MATERIALMODS_CR / CRBPLEDGEDRECEIVABLES AS PER_MATERIALMODS_CR,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0  AND ACTUAL_SPV = 'FBX_PT6' AND "Repurchased CRB" = 0 AND zeroifnull(DPD_DAYS) <=21  AND zeroifnull(FBX_PLUS) <> 1 AND CRB_MATERIAL_MODIFICATION <> 1 and zeroifnull(IS_IN_BREATHER) = 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) BREATHERS_CR,
	BREATHERS_CR / nullifzero(CRBPLEDGEDRECEIVABLES) AS PER_BREATHERS_CR,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_PT6' and CRB_Eligible = 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END * Nullifzero("Vantage Score")  ) /(ELIGIBLERECEIVABLESCRBWAM - VANTAGESCOREISZEROTOTAL_CR ),2)  WAVANATAGESCORE_CR,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_PT6' and CRB_Eligible = 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END * RISK_SCORE_TRUE   ) / ELIGIBLERECEIVABLESCRBWAM,2) AS WARISKSCORE_CR,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_PT6' and CRB_Eligible = 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END * Original_Term   ) / ELIGIBLERECEIVABLESCRBWAM,2) AS WATERM_CR,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_PT6' and CRB_Eligible = 1 AND ORIGINAL_TERM = 52 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END * NEW_OR_EXISTING) / "Eligible Receivables 52W CRBWAM",2) AS WA52W_NEWLOANS,
    ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_PT6' and CRB_Eligible = 1 AND ORIGINAL_TERM = 52 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END * RISK_SCORE_TRUE) / "Eligible Receivables 52W CRBWAM",2) AS WA52W_RISKSCORE
FROM FACILITY_BASE2
WHERE EDATE > '10/1/2024'
GROUP BY ALL
ORDER BY 1 ASC;

-- SELECT * FROM ANALYTICS.CAPITAL_MARKETS.BALANCE_SHEET_EVAL_RG

-- SELECT * FROM ANALYTICS.CAPITAL_MARKETS.FACILITY_BASE2;

--Balance Sheet / Total Metric
CREATE OR REPLACE TABLE INDUS.PUBLIC.BALANCE_SHEET_EVAL_RG AS 
WITH pledging_dates as (
select edate, lag(edate) over(order by edate asc) as previous_pledge_date from ANALYTICS.CAPITAL_MARKETS.PLEDGE_DATES 
),
BREATHERS AS (
	SELECT
	    A.FBBID,
	    A.LOAN_KEY,
	    A.EDATE,
	    FROM_DATE BREATHER_START_DATE,
	    TO_DATE BREATHER_END_DATE,
	    (TO_DATE - FROM_DATE) BREATHER_LENGTH,
	    CASE
	        WHEN A.EDATE BETWEEN BREATHER_START_DATE AND BREATHER_END_DATE THEN 1
	        ELSE 0
	    END IS_IN_BREATHER,
	    CASE
	        WHEN A.EDATE BETWEEN BREATHER_START_DATE AND BREATHER_END_DATE THEN BREATHER_LENGTH
	        ELSE 0
	    END BREATHER_DURATION,
	        ROUND(((SUM(CASE WHEN BREATHER_START_DATE IS NOT NULL THEN BREATHER_LENGTH END) OVER(PARTITION BY LOAN_KEY))/7),0) BREATHER_PLAN_COUNT
	FROM BI.FINANCE.FINANCE_METRICS_DAILY A
	LEFT JOIN BI.FINANCE.DIM_BREATHER_EVENT B
	        ON A.FBBID = B.FBBID
	                AND A.EDATE>=B.FROM_DATE
	                AND A.EDATE<=B.TO_DATE
	WHERE FROM_DATE IS NOT NULL
		AND YEAR(EDATE) > 2023
	GROUP BY 1,2,3,4,5,6,7
),
BREATHER_FINAL AS 
(
	SELECT
	        LOAN_KEY,
	        EDATE,
	        IS_IN_BREATHER,
	        BREATHER_DURATION,
	        zeroifnull(BREATHER_PLAN_COUNT) BREATHER_PLAN_COUNT,
	        BREATHER_START_DATE,
	        BREATHER_END_DATE
	FROM BREATHERS
	WHERE EDATE>=BREATHER_START_DATE 
	    AND EDATE<=BREATHER_END_DATE
),
ACQ_CHANNEL_CALC AS
(
	SELECT
		A.FBBID,
		A.LOAN_KEY,
		CASE
			WHEN LOWER(REGEXP_REPLACE(TRIM(CD.REGISTRATION_CAMPAIGN_ID), '\s+\d+$', '')) = LOWER(REGEXP_REPLACE(TRIM(TB.TERMINATED_BROKERS), '\s+\d+$', '')) THEN 'Brokers'
			WHEN PN.PARTNER_NAME = 'Intuit' THEN 'Intuit'
			WHEN LOWER(CD.REGISTRATION_CAMPAIGN_ID) IN ('intuit', 'intuit_appcenter', 'quickbooks-financing', 'intuit_campaigns') OR LOWER(REGISTRATION_CAMPAIGN_ID) LIKE '%intuit%' THEN 'Intuit'
			WHEN PN.PARTNER_NAME = 'Nav' THEN 'NAV'
			WHEN PN.PARTNER_NAME IN ('Lendingtree', 'Lendio') THEN 'Marketplace'
			WHEN LOWER(REGEXP_REPLACE(TRIM(CD.PARTNER_ATTRIBUTION), '\s+\d{4}$', '')) = LOWER(REGEXP_REPLACE(TRIM(PN.PARTNER_ATTRIBUTION), '\s+\d{4}$', '')) THEN 'Strategic Partners'
			WHEN LOWER(REGEXP_REPLACE(TRIM(CD.PARTNER_ATTRIBUTION), '\s+\d{4}$', '')) = LOWER(REGEXP_REPLACE(TRIM(PN.PARTNER_NAME), '\s+\d{4}$', '')) THEN 'Strategic Partners'
			WHEN LOWER(CD.PARTNER_ATTRIBUTION) IN ('organic','content', 'fundboxpay', 'content 100817571549') THEN 'Organic'
	        WHEN LOWER(CD.PARTNER_ATTRIBUTION) LIKE '%direct%' THEN 'Direct'
			WHEN (PN.PARTNER_NAME IS NULL AND CD.PARTNER_ATTRIBUTION IN ('non-partner')) THEN 'Organic'
			WHEN (PN.PARTNER_NAME IS NULL) THEN 'Terminated Channel'
			ELSE 'Brokers'
		END ACQ_CHANNEL
	FROM BI.FINANCE.FINANCE_METRICS_DAILY A
	LEFT JOIN BI."PUBLIC".CUSTOMERS_DATA cd 
	ON CD.FBBID = A.FBBID
	LEFT JOIN ANALYTICS.CREDIT.EG_PA_TO_PN PN 
		ON LOWER(REGEXP_REPLACE(TRIM(CD.PARTNER_ATTRIBUTION), '\s+\d{4}$', '')) = LOWER(REGEXP_REPLACE(TRIM(PN.PARTNER_ATTRIBUTION), '\s+\d{4}$', ''))
			OR LOWER(REGEXP_REPLACE(TRIM(CD.PARTNER_ATTRIBUTION), '\s+\d{4}$', '')) = LOWER(REGEXP_REPLACE(TRIM(PN.PARTNER_NAME), '\s+\d{4}$', ''))
	LEFT JOIN ANALYTICS.CAPITAL_MARKETS.TERMINATED_BROKERS TB
		ON LOWER(REGEXP_REPLACE(TRIM(CD.REGISTRATION_CAMPAIGN_ID), '\s+\d{4}$', '')) = LOWER(REGEXP_REPLACE(TRIM(TB.TERMINATED_BROKERS), '\s+\d{4}$', ''))
	GROUP BY ALL
),
Repurchased_loan_date AS
(SELECT LOAN_KEY,
CASE WHEN Set_SPV.FROM_SPV IN ( 'FBX_PT6', 'FBX_PT5', 'FBX_PT4') AND Set_SPV.TO_SPV = 'FBX_INC' THEN Set_SPV.Edate ELSE NULL end AS "Repurchase Date",
Set_SPV.FROM_SPV,
FROM SETPOINT_APPROVED_REPORT_DATA.RESULTS.REPORT_APPROVAL_RESULTS AS Set_SPV),
MODIFICATIONS AS
(
	SELECT
	    A.LOAN_KEY,
	    A.edate,
	    SUM(CASE WHEN ACTIVE_PAYMENT_PLAN_NAME = ('AMOUNT_BASED_WEEKLY') AND EDATE=ACTIVE_PAYMENT_PLAN_START_DATE THEN 1 WHEN ACTIVE_PAYMENT_PLAN_NAME= ('AMOUNT_BASED_QUAD_WEEKLY') AND EDATE=ACTIVE_PAYMENT_PLAN_START_DATE THEN 1 ELSE 0 END) CUSTOM_PLAN_COUNT,
	    SUM(DISTINCT CASE WHEN LOAN_OPERATIONAL_STATUS = 'FROZ' THEN 1 ELSE 0 END) WAIVER_COUNT,
	    MIN(CASE WHEN LOAN_OPERATIONAL_STATUS = 'FROZ' THEN EDATE END) WAIVER_DATE,
	    MAX(CASE WHEN ACTIVE_PAYMENT_PLAN_NAME IN ('AMOUNT_BASED_WEEKLY', 'AMOUNT_BASED_QUAD_WEEKLY') THEN ACTIVE_PAYMENT_PLAN_START_DATE END) MAX_CUSTOM_PLAN_DATE
	FROM BI.FINANCE.FINANCE_METRICS_DAILY A
	WHERE YEAR(EDATE) > 2023
	GROUP BY A.LOan_KEY, A.EDATE
),
OB_MANUAL AS
(
	    SELECT 
            FBBID,
            1 OB_MANUAL_UW 
	    FROM
	    (
            SELECT 
                FBBID
            FROM ANALYTICS.CREDIT.AUW_INCREASE_ACCTS
            UNION
            SELECT
                FBBID 
            FROM ANALYTICS.CREDIT.SECOND_LOOK_ACCOUNTS
	    )
	    GROUP BY ALL
),
OG_MANUAL AS
(
     SELECT 
         FUNDBOX_ID__C FBBID,
         1 OG_MANUAL_UW
    FROM EXTERNAL_DATA_SOURCES.SALESFORCE_NOVA.LOAN__C C
    WHERE TRUE
        AND FUNDBOX_ID__C IN (SELECT FBBID FROM ANALYTICS.CREDIT.JOHNFL_AUW_OG_OUTREACH_DEC_2024)
        AND RECORDTYPEID = '012Rd000001B2txIAC'
        AND CREATEDDATE::DATE >= '2024-12-02'
        AND STATUS__C IN ('Complete - Increase + Better Terms', 'Complete - Increase')
	GROUP BY ALL
),
FBXPLUS AS 
(
    SELECT 
            DACD.FBBID,
            DACD.EDATE,
            1 FBX_PLUS
    FROM BI."PUBLIC".DAILY_APPROVED_CUSTOMERS_DATA DACD
    WHERE UPPER(DACD.FUNDBOX_PLUS_STATUS) LIKE '%SUBSCRIBED%'
    	AND YEAR(EDATE) > 2023
    GROUP BY ALL
),
CREDIT_LIMIT AS 
(
    SELECT
        FBBID,
        MAX(CREDIT_LIMIT) CREDIT_LIMIT_MAX
    FROM (SELECT FBBID, CREDIT_LIMIT FROM BI.PUBLIC.DAILY_APPROVED_CUSTOMERS_DATA WHERE YEAR(EDATE) > 2023) DACD
    GROUP BY ALL
),
BK_FRAUD AS
(
	SELECT FBBID,
			EDATE,
			IS_FRAUD,
			BK_FILING_DATE
	FROM BI.PUBLIC.DAILY_APPROVED_CUSTOMERS_DATA
	WHERE YEAR(EDATE) > 2023
	GROUP BY ALL
),
CDC_OB AS (
  SELECT
    DISTINCT IDENTIFIER_ID AS FBBID,
    CASE
      WHEN SCORE <= 0.01 THEN 1
      WHEN SCORE <= 0.02 THEN 2
      WHEN SCORE <= 0.03 THEN 3
      WHEN SCORE <= 0.04 THEN 4
      WHEN SCORE <= 0.05 THEN 5
      WHEN SCORE <= 0.06 THEN 6
      WHEN SCORE <= 0.07 THEN 7
      WHEN SCORE <= 0.08 THEN 8
      WHEN SCORE <= 0.09 THEN 9
      WHEN SCORE <= 0.1 THEN 10
      WHEN SCORE <= 0.125 THEN 11
      WHEN SCORE <= 0.150 THEN 12
      WHEN SCORE <= 0.175 THEN 13
      WHEN SCORE <= 0.2 THEN 14
      WHEN SCORE <= 1 THEN 15
    END AS CURRENT_ONBOARDING
  FROM CDC_V2.SCORING.SCORING_MODEL_SCORES
  WHERE MODEL_NAME = 'smm-eaglet-SV-dac-v9-9-v3'
  QUALIFY ROW_NUMBER() OVER(PARTITION BY IDENTIFIER_ID ORDER BY PREDICTION_TIME DESC) = 1
),
OG_CDC AS (
  SELECT
    D.FBBID,
    D.EDATE,
    LAST_VALUE(CASE WHEN D.RISK_CREDIT_REVIEW_MODEL_NAME IN ('UnifiedOngoingMLEModelV2.2', 'sm-internalmodel_unified_og_v2.2_shap', 'smm-ongoing-SV-v2-2-shap', 'smm-ongoing-SV-v2-2-shap-sbd-v2') 
    	THEN D.RISK_CREDIT_REVIEW_ALIGNED_BUCKET ELSE OG.RETRO_SCORE END) OVER(PARTITION BY D.FBBID, D.EDATE ORDER BY D.EDATE) AS OG_SCORE
  FROM BI.PUBLIC.DAILY_APPROVED_CUSTOMERS_DATA AS d
    LEFT JOIN (
      SELECT
        FBBID,
        SCORE_DT,
        FIRST_VALUE(UNI_BKT) IGNORE NULLS OVER(PARTITION BY FBBID ORDER BY SCORE_DT) AS RETRO_SCORE,
        FIRST_VALUE(OG_SCORE) IGNORE NULLS OVER(PARTITION BY FBBID ORDER BY SCORE_DT) AS SCORE_SPECIFIC
      FROM
        (
          SELECT
            CAST(PREDICTION_TIME AS DATE) AS SCORE_DT,
            IDENTIFIER_ID AS FBBID,
            SCORE AS OG_SCORE,
            CASE
              WHEN SCORE <= 0.016 THEN 1
              WHEN SCORE <= 0.019 THEN 2
              WHEN SCORE <= 0.025 THEN 3
              WHEN SCORE <= 0.03 THEN 4
              WHEN SCORE <= 0.036 THEN 5
              WHEN SCORE <= 0.043 THEN 6
              WHEN SCORE <= 0.052 THEN 7
              WHEN SCORE <= 0.063 THEN 8
              WHEN SCORE <= 0.08 THEN 9
              WHEN SCORE <= 0.11 THEN 10
              WHEN SCORE <= 0.122 THEN 11
              WHEN SCORE <= 0.135 THEN 12
              WHEN SCORE <= 0.156 THEN 13
              WHEN SCORE <= 0.195 THEN 14
              WHEN SCORE <= 1 THEN 15
            END AS UNI_BKT
          FROM CDC_V2.SCORING.SCORING_MODEL_SCORES
          WHERE MODEL_NAME IN ('UnifiedOngoingMLEModelV2.2', 'sm-internalmodel_unified_og_v2.2_shap', 'smm-ongoing-SV-v2-2-shap', 'smm-ongoing-SV-v2-2-shap-sbd-v2')
        )
    ) AS OG 
    ON D.FBBID = OG.FBBID
    	AND D.EDATE = OG.SCORE_DT
),
MODEL_DEVELOPMENT AS
(
    SELECT
        FBBID,
        CASE WHEN IS_SAVED_BY_CONTROL_GROUP+IS_SAVED_BY_PARTNERSHIP > 0 THEN 1 ELSE 0 END MODEL_DEVELOPMENT_FLAG
    FROM (SELECT FBBID, IS_SAVED_BY_CONTROL_GROUP, IS_SAVED_BY_PARTNERSHIP FROM BI.PUBLIC.DAILY_APPROVED_CUSTOMERS_DATA WHERE YEAR(EDATE) > 2023) DACD
    GROUP BY ALL
)
SELECT
	EDATE,
    CASE 
        WHEN DAYNAME(edate) = 'Wednesday' THEN edate  
        ELSE NEXT_DAY(edate, 'WEDNESDAY') 
    END AS WEEK_END_DATE,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) MANAGED_RECEIVABLES,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND FBX_OWNED = 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) FBX_RECEIVABLES,
	FBX_RECEIVABLES / MANAGED_RECEIVABLES AS PER_OWNED,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_PT6' THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) CRB_OUTSTANDING,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_PT5' THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) CS_OUTSTANDING,
	CRB_OUTSTANDING + CS_OUTSTANDING AS TOTALPLEDGED,
	TOTALPLEDGED/ MANAGED_RECEIVABLES AS PLEDGED_PER,
	TOTALPLEDGED/ FBX_RECEIVABLES AS PLEDGEDPEROWNEDBOOK,
	ZEROIFNULL(CS_DEBT_DRAWN + CRB_DEBT_DRAWN) AS DEBTDRAWN,
	DEBTDRAWN / MANAGED_RECEIVABLES AS "Debt Drawn %",
	DEBTDRAWN / FBX_RECEIVABLES AS DEBTDRAWNPEROWNEDBOOK,
	DEBTDRAWN / TOTALPLEDGED AS DRAWNPERPLEDGED,
	 ZEROIFNULL(RESTRICTED_CASH) AS RESTRICTEDCASH,
	(DEBTDRAWN  - ZEROIFNULL(RESTRICTED_CASH) ) / FBX_RECEIVABLES AS CASH_ADJUSTEDLEVERAGE,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_INC' THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) FBX_INC_MANAGED_RECEIVABLES,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_INC' AND FBX_OWNED = 0 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) FBX_INC_NOT_OWNED_RECEIVABLES,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_INC' AND FBX_OWNED = 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) FBX_INC_RECEIVABLES,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_INC' AND FBX_OWNED = 1 AND DPD > 0 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) DQ_RECEIVABLES,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_INC' AND FBX_OWNED = 1 AND DPD = 0 AND MATERIAL_MODIFICATION > 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) MATERIAL_MODIFICATIONS,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_INC' AND FBX_OWNED = 1 AND DPD = 0 AND REPURCHASED = 1 AND MATERIAL_MODIFICATION <= 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) REPURCHASED_RECEIVABLES,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_INC' AND FBX_OWNED = 1 AND DPD = 0 AND REPURCHASED = 0 AND MATERIAL_MODIFICATION <= 1 AND (QUAD_WEEKLY = 1) THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) F52WEEKSQUADWEEKLY,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_INC' AND FBX_OWNED = 1 AND DPD = 0 AND REPURCHASED = 0 AND MATERIAL_MODIFICATION <= 1 AND (FIFTY_TWO = 1) AND zeroifnull(FBX_PLUS) = 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) F52WEEKSFBXPLUS,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_INC' AND FBX_OWNED = 1 AND DPD = 0 AND REPURCHASED = 0 AND MATERIAL_MODIFICATION <= 1 AND (FIFTY_TWO = 1) AND zeroifnull(FBX_PLUS) = 0 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) F52WEEKSTOTAL,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_INC' AND FBX_OWNED = 1 AND DPD = 0 AND REPURCHASED = 0 AND MATERIAL_MODIFICATION <= 1 AND (FIFTY_TWO = 1) AND ZEROIFNULL(SCORE_TO_USE) > 8 AND zeroifnull(FBX_PLUS) = 0 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) F52WEEKS_RISKSCORE8,
    ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_INC' AND FBX_OWNED = 1 AND DPD = 0 AND REPURCHASED = 0 AND MATERIAL_MODIFICATION <= 1 AND (FIFTY_TWO = 1) AND ZEROIFNULL(OB_score_to_use) > 7 AND zeroifnull(FBX_PLUS) = 0 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) F52WEEKS_RISKSCORE7,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_INC' AND FBX_OWNED = 1 AND DPD = 0 AND REPURCHASED = 0 AND MATERIAL_MODIFICATION <= 1 AND (FIFTY_TWO = 1) AND ZEROIFNULL(SCORE_TO_USE) <= 8 AND ZEROIFNULL(OB_score_to_use) <= 7 AND DIRECT_OR_ORGANIC = 1 AND zeroifnull(FBX_PLUS) = 0 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) F52WEEKS_DOO,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_INC' AND FBX_OWNED = 1 AND DPD = 0 AND REPURCHASED = 0 AND MATERIAL_MODIFICATION <= 1 AND (FIFTY_TWO = 1) AND ZEROIFNULL(SCORE_TO_USE) <= 8 AND ZEROIFNULL(OB_score_to_use) <= 7 AND DIRECT_OR_ORGANIC = 0 AND zeroifnull(FBX_PLUS) = 0 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) F52WEEKS_REM,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_INC' AND FBX_OWNED = 1 AND DPD = 0 AND REPURCHASED = 0 AND MATERIAL_MODIFICATION <= 1 AND (FIFTY_TWO = 0 AND QUAD_WEEKLY = 0) AND MANUAL_UW = 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) MANUALUW,
    ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_INC' AND FBX_OWNED = 1 AND DPD = 0 AND REPURCHASED = 0 AND MATERIAL_MODIFICATION <= 1 AND (FIFTY_TWO = 0 AND QUAD_WEEKLY = 0) AND MANUAL_UW = 0 AND LOC = 0 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) NONLOC, -- manually added 20th aug for KM
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_INC' AND FBX_OWNED = 1 AND DPD = 0 AND REPURCHASED = 0 AND MATERIAL_MODIFICATION <= 1 AND (FIFTY_TWO = 0 AND QUAD_WEEKLY = 0) AND MANUAL_UW = 0 AND AUTOBOOKS = 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) AUTOBOOKS_TOTAL,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_INC' AND FBX_OWNED = 1 AND DPD = 0 AND REPURCHASED = 0 AND MATERIAL_MODIFICATION <= 1 AND (FIFTY_TWO = 0 AND QUAD_WEEKLY = 0) AND MANUAL_UW = 0 AND AUTOBOOKS = 0 AND LOC = 1 AND MODEL_DEVELOPMENT_FLAG = 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) MODEL_DEVELOPMENT,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_INC' AND FBX_OWNED = 1 AND DPD = 0 AND REPURCHASED = 0 AND MATERIAL_MODIFICATION <= 1 AND (FIFTY_TWO = 0 AND QUAD_WEEKLY = 0) AND MANUAL_UW = 0 AND AUTOBOOKS = 0 AND LOC = 1 AND MODEL_DEVELOPMENT_FLAG = 0 AND BK_FRAUD = 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) BK_FRAUDS,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_INC' AND FBX_OWNED = 1 AND DPD = 0 AND REPURCHASED = 0 AND MATERIAL_MODIFICATION <= 1 AND (FIFTY_TWO = 0 AND QUAD_WEEKLY = 0) AND MANUAL_UW = 0 AND AUTOBOOKS = 0 AND LOC = 1 AND MODEL_DEVELOPMENT_FLAG = 0 AND BK_FRAUD = 0 AND CREDIT_LIMIT_INCREASE = 1 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) CREDIT_LIMIT_MAX,
	ROUND(SUM(CASE WHEN IS_CHARGED_OFF = 0 AND ACTUAL_SPV = 'FBX_INC' AND FBX_OWNED = 1 AND DPD = 0 AND REPURCHASED = 0 AND MATERIAL_MODIFICATION <= 1 AND (FIFTY_TWO = 0 AND QUAD_WEEKLY = 0) AND ZEROIFNULL(SCORE_TO_USE) <= 8 AND ZEROIFNULL(OB_score_to_use) <= 7 AND MANUAL_UW = 0 AND AUTOBOOKS = 0 AND LOC = 1 AND MODEL_DEVELOPMENT_FLAG = 0 AND BK_FRAUD = 0 AND CREDIT_LIMIT_INCREASE = 0 THEN OUTSTANDING_PRINCIPAL_FUNDED ELSE 0 END),2) REMAINING_BALANCE,
	DQ_RECEIVABLES/ FBX_INC_RECEIVABLES AS DQ_RECEIVABLESPER,
	MATERIAL_MODIFICATIONS / FBX_INC_RECEIVABLES AS MATERIAL_MODIFICATIONPER,
	REPURCHASED_RECEIVABLES / FBX_INC_RECEIVABLES AS REPURCHASED_RECEIVABLESPER,
	F52WEEKSFBXPLUS / FBX_INC_RECEIVABLES AS F52WEEKSFBXPLUSPER,
	F52WEEKSQUADWEEKLY / FBX_INC_RECEIVABLES AS F52WEEKSQUADWEEKLYPER,
	F52WEEKSTOTAL / FBX_INC_RECEIVABLES AS F52WEEKSTOTALPER,
	F52WEEKS_RISKSCORE8 / FBX_INC_RECEIVABLES AS F52WEEKS_RISKSCORE8PER,
    F52WEEKS_RISKSCORE7 / FBX_INC_RECEIVABLES AS F52WEEKS_RISKSCORE7PER,
	F52WEEKS_DOO / FBX_INC_RECEIVABLES AS F52WEEKS_DOO_PER,
	F52WEEKS_REM / FBX_INC_RECEIVABLES AS F52WEEKS_REM_PER,
	MANUALUW / FBX_INC_RECEIVABLES AS MANUALUNDEWRITINGPER,
	AUTOBOOKS_TOTAL / FBX_INC_RECEIVABLES AS AUTOBOOKSPER,
	MODEL_DEVELOPMENT / FBX_INC_RECEIVABLES AS MODELDEVELOPMENTPER,
	BK_FRAUDS / FBX_INC_RECEIVABLES AS BKORFRAUDPER,
	CREDIT_LIMIT_MAX / FBX_INC_RECEIVABLES AS CREDITLIMITMAXPER,
	REMAINING_BALANCE / FBX_INC_RECEIVABLES AS REMAININGBALANCEPER
FROM
        (
            SELECT
            	DISTINCT
                A.LOAN_KEY,
                A.EDATE,
                CASE WHEN DAYNAME(a.edate) = 'Wednesday' THEN a.edate  
                ELSE NEXT_DAY(a.edate, 'WEDNESDAY') 
                END AS WEEK_END_DATE,
                CHARGE_OFF_DATE,
                CRB_REPURCHASES.REPURCHASE_WEEK CRB_REPURCHASED,
                CS_REPURCHASESV2.REPURCHASE_WEEK CS_REPURCHASED,
                "Repurchase Date",
                RLD.FROM_SPV,
			    CASE
				    WHEN A.EDATE > '1/31/2025' THEN COALESCE(TO_SPV, SPV::STRING)
					WHEN (A.EDATE < CRB_REPURCHASES.REPURCHASE_WEEK OR  CRB_REPURCHASES.REPURCHASE_WEEK IS NULL) AND CRB_PLEDGED.TRANSFER_DATE <= A.EDATE THEN 'FBX_PT6'
					WHEN A.EDATE >= DATEADD(DAY, 1 - DAYOFWEEK(CS_PLEDGED.TRANSFER_DATE), CS_PLEDGED.TRANSFER_DATE) AND DATEADD(DAY, 1 - DAYOFWEEK(CS_PLEDGED.TRANSFER_DATE), CS_PLEDGED.TRANSFER_DATE) > DATEADD(DAY, 1 - DAYOFWEEK(CS_REPURCHASESV2.REPURCHASE_WEEK), CS_REPURCHASESV2.REPURCHASE_WEEK)  THEN 'FBX_PT5'
					--                    IF repurchased BY cs THEN fbx inc
					WHEN A.EDATE >= DATEADD(DAY, 1 - DAYOFWEEK(CS_REPURCHASESV2.REPURCHASE_WEEK), CS_REPURCHASESV2.REPURCHASE_WEEK) THEN 'FBX_INC'
					--                    IF repurchased BY crb and not transfered to cs THEN fbx inc
					WHEN A.EDATE >= DATEADD(DAY, 1 - DAYOFWEEK(CRB_REPURCHASES.REPURCHASE_WEEK), CRB_REPURCHASES.REPURCHASE_WEEK) AND A.EDATE < DATEADD(DAY, 1 - DAYOFWEEK(CS_PLEDGED.TRANSFER_DATE), CS_PLEDGED.TRANSFER_DATE) THEN 'FBX_INC'
					--                    IF pledged to crb and not transfered to cs then crb
					   -- WHEN A.EDATE >= DATEADD(DAY, 1 - DAYOFWEEK(CRB_PLEDGED.TRANSFER_DATE), CRB_PLEDGED.TRANSFER_DATE) AND A.EDATE < DATEADD(DAY, 1 - DAYOFWEEK(CS_PLEDGED.TRANSFER_DATE), CS_PLEDGED.TRANSFER_DATE) THEN 'FBX_PT6'
					--                    IF pledged to cs and not yet repurchased by cs then cs
					WHEN A.EDATE >= DATEADD(DAY, 1 - DAYOFWEEK(CS_PLEDGED.TRANSFER_DATE), CS_PLEDGED.TRANSFER_DATE) AND A.EDATE < DATEADD(DAY, 1 - DAYOFWEEK(CS_REPURCHASESV2.REPURCHASE_WEEK), CS_REPURCHASESV2.REPURCHASE_WEEK) THEN 'FBX_PT5'
					--                    IF pledged to cs, not repurchased by cs or transferred to crb then cs
					WHEN A.EDATE >= DATEADD(DAY, 1 - DAYOFWEEK(CS_PLEDGED.TRANSFER_DATE), CS_PLEDGED.TRANSFER_DATE) AND A.EDATE <= MAX(CASE WHEN SPV::STRING = 'FBX_PT5' THEN A.EDATE END) OVER(PARTITION BY A.LOAN_KEY) THEN 'FBX_PT5'
					--                    IF pledged to crb, not repurchased by crb or transferred to cs then crb
					  --  WHEN A.EDATE >= DATEADD(DAY, 1 - DAYOFWEEK(CRB_PLEDGED.TRANSFER_DATE), CRB_PLEDGED.TRANSFER_DATE) AND A.EDATE <= MAX(CASE WHEN SPV::STRING = 'FBX_PT6' THEN A.EDATE END) OVER(PARTITION BY A.LOAN_KEY) THEN 'FBX_PT6'
					--                    If Loan is pledged on cutoff day(or within 3 days greater) then CS
				   	WHEN (DATEDIFF(DAY, DATEADD(DAY, 1 - DAYOFWEEK(CS_PLEDGED.TRANSFER_DATE), CS_PLEDGED.TRANSFER_DATE), A.EDATE) BETWEEN 0 AND 3) AND DATEADD(DAY, 1 - DAYOFWEEK(CS_REPURCHASESV2.REPURCHASE_WEEK), CS_REPURCHASESV2.REPURCHASE_WEEK) IS NULL THEN 'FBX_PT5'
					--                    IF PIMCO then PIMCO
					WHEN SPV::STRING = 'FBX_PT4' THEN 'FBX_PT4'
					ELSE 'FBX_INC'
			    END ACTUAL_SPV,
                CASE
                	WHEN OWNERSHIP_DATE IS NOT NULL AND LOAN_CREDITED_DATE IS NOT NULL THEN 1
                	ELSE 0
                END FBX_OWNED,
                CASE
	    			WHEN A.EDATE > '1/31/2025' AND "Repurchase Date" <= A.EDATE THEN 1
    				WHEN A.EDATE <= '1/31/2025' AND CRB_REPURCHASES.REPURCHASE_WEEK <= A.EDATE or CS_REPURCHASESV2.REPURCHASE_WEEK <= A.EDATE THEN 1
    				WHEN A.EDATE <= '1/31/2025' AND ((CRB_REPURCHASED > A.EDATE OR CRB_REPURCHASED IS NULL) AND (CS_REPURCHASED > A.EDATE OR CS_REPURCHASED IS NULL)) THEN 0
    				ELSE 0
    			END REPURCHASED,
    			CASE
    				WHEN ACQ_CHANNEL IN ('Organic', 'Direct', 'Terminated Channel', 'Brokers') THEN 1
    				ELSE 0
    			END DIRECT_OR_ORGANIC,    			
                CASE
                	WHEN ORIGINAL_PAYMENT_PLAN_NAME = 'WEEKLY_AMORTIZED_52' THEN 1
                	ELSE 0
                END FIFTY_TWO,
                 CASE
                	WHEN ORIGINAL_PAYMENT_PLAN_NAME = 'QUAD_WEEKLY_52' THEN 1
                	ELSE 0
                END QUAD_WEEKLY,              
                ORIGINAL_TERM,
                CASE
                	WHEN (OB_MANUAL_UW = 1 OR OG_MANUAL_UW = 1) THEN 1
                	ELSE 0
                END MANUAL_UW,
                OB_MANUAL_UW,
                OG_MANUAL_UW,
                coalesce(OB_TO_USE,CURRENT_ONBOARDING)  as Ob_score_to_use,
                COALESCE(CSR.risk_score, june.risk_score, OG_SCORE, Ob_score_to_use) AS SCORE_TO_USE,
                CASE
                	WHEN UPPER(SUB_PRODUCT) LIKE '%LINE%' THEN 1
                	ELSE 0
                END LOC,
                CASE
                	WHEN UPPER(SUB_PRODUCT) LIKE '%MCA%' THEN 1
                	ELSE 0
                END AUTOBOOKS,
                CASE
                	WHEN ZEROIFNULL(IS_FRAUD) = 1 OR BK_FILING_DATE IS NOT NULL THEN 1
                	ELSE 0
                END BK_FRAUD,
                CASE
                	WHEN CREDIT_LIMIT_MAX > 150000 THEN 1
                	ELSE 0
                END CREDIT_LIMIT_INCREASE,                
                ZEROIFNULL(DPD_DAYS) DPD,      
                FBX_PLUS,
                ZEROIFNULL(MODEL_DEVELOPMENT_FLAG) MODEL_DEVELOPMENT_FLAG,
                IS_CHARGED_OFF,
                SUM(DISTINCT CUSTOM_PLAN_COUNT+WAIVER_COUNT+(CASE WHEN BREATHER_PLAN_COUNT > 2 THEN 1 ELSE 0 END)) OVER(PARTITION BY A.LOAN_KEY) MATERIAL_MODIFICATION,
                OUTSTANDING_PRINCIPAL_FUNDED,
                RESTRICTED_CASH,
                CS_DEBT_DRAWN,
                CRB_DEBT_DRAWN
            FROM pledging_dates PD
            LEFT JOIN BI.FINANCE.FINANCE_METRICS_DAILY A
            		ON PD.EDATE = A.EDATE
            LEFT JOIN ANALYTICS.CAPITAL_MARKETS.CS_PLEDGED
                   	ON A.LOAN_KEY = CS_PLEDGED.LOAN_KEY
            LEFT JOIN ANALYTICS.CAPITAL_MARKETS.CS_REPURCHASESV2
            		ON A.LOAN_KEY = CS_REPURCHASESV2.LOAN_KEY
            LEFT JOIN ANALYTICS.CAPITAL_MARKETS.CRB_PLEDGED
            		ON A.LOAN_KEY = CRB_PLEDGED.LOAN_KEY
            LEFT JOIN ANALYTICS.CAPITAL_MARKETS.CRB_REPURCHASES
            		ON A.LOAN_KEY = CRB_REPURCHASES.LOAN_KEY
            LEFT JOIN FBXPLUS
                    ON A.FBBID = FBXPLUS.FBBID AND A.LOAN_CREATED_DATE = FBXPLUS.EDATE
            LEFT JOIN MODEL_DEVELOPMENT
                    ON A.FBBID = MODEL_DEVELOPMENT.FBBID
            LEFT JOIN CREDIT_LIMIT
                    ON A.FBBID = CREDIT_LIMIT.FBBID
            LEFT JOIN OB_MANUAL
                    ON A.FBBID = OB_MANUAL.FBBID
            LEFT JOIN OG_MANUAL
                    ON A.FBBID = OG_MANUAL.FBBID
            LEFT JOIN MODIFICATIONS 
            		ON A.LOAN_KEY = MODIFICATIONS.LOAN_KEY  AND A.EDATE = MODIFICATIONS.EDATE
           	LEFT JOIN BREATHER_FINAL 
           			ON A.LOAN_KEY = BREATHER_FINAL.LOAN_KEY AND A.EDATE = BREATHER_FINAL.EDATE
            LEFT JOIN BK_FRAUD
            		ON A.FBBID = BK_FRAUD.FBBID AND A.LOAN_CREATED_DATE = BK_FRAUD.EDATE
            LEFT JOIN (SELECT FBBID, EDATE, SUB_PRODUCT FROM BI.PUBLIC.DAILY_APPROVED_CUSTOMERS_DATA) DACD
        			ON A.FBBID = DACD.FBBID AND A.LOAN_CREATED_DATE = DACD.EDATE
        	LEFT JOIN ANALYTICS.CAPITAL_MARKETS.ACTUAL_DEBT_DRAWN ADDD
        			ON A.EDATE = ADDD.EDATE
        	LEFT JOIN ANALYTICS.CAPITAL_MARKETS.RESTRICTED_CASH RC 
        			ON A.EDATE = RC.EDATE
			LEFT JOIN OG_CDC AS BS 
					ON A.FBBID = BS.FBBID AND A.LOAN_CREATED_DATE = BS.EDATE
			LEFT JOIN ACQ_CHANNEL_CALC
					ON ACQ_CHANNEL_CALC.LOAN_KEY = A.LOAN_KEY
			LEFT JOIN CDC_OB AS COB 
					ON A.FBBID = COB.FBBID
        	LEFT JOIN SETPOINT_APPROVED_REPORT_DATA.RESULTS.REPORT_APPROVAL_RESULTS SETPOINT_SPV
					ON A.LOAN_KEY = SETPOINT_SPV.LOAN_KEY AND A.EDATE = SETPOINT_SPV.EDATE
			LEFT JOIN Repurchased_loan_date RLD ON A.loan_key = RLD.loan_key AND A.Edate = RLD."Repurchase Date" 
            left join (select loan_key, risk_score, FBBID from ANALYTICS.CAPITAL_MARKETS.DATA_ROOM_LOAN_TAPE_JUNE2025) JUNE
                on June.loan_key = A.loan_key
            left join ANALYTICS.CAPITAL_MARKETS.CS_RISK_SCORES CSR
                on CSR.loan_key = A.loan_key
            left join ANALYTICS.CAPITAL_MARKETS.OB_SCORES OBS
                on OBS.loan_key = A.loan_key
        )
WHERE EDATE > '10/1/2024'
GROUP BY ALL
ORDER BY 1 ASC;


-- SELECT * FROM ANALYTICS.CAPITAL_MARKETS.BALANCE_SHEET_EVAL_RG bse;

-- SELECT *, count(loan_key) OVER( PARTITION BY loan_key) AS key_count  FROM ANALYTICS.CAPITAL_MARKETS.FACILITY_BASE2
-- WHERE edate = '7/28/2025'
-- QUALIFY key_count  > 1 
-- ORDER BY loan_key;


--- adding table name in final select

create or replace table INDUS.PUBLIC.CAPITAL_MARKETS_V2_RG as
SELECT 
--	Balance Sheet / Total Metrics
	BALANCE_SHEET_EVAL_RG.WEEK_END_DATE,
	BALANCE_SHEET_EVAL_RG.MANAGED_RECEIVABLES,
	BALANCE_SHEET_EVAL_RG.FBX_RECEIVABLES,
	BALANCE_SHEET_EVAL_RG.PER_OWNED,
	CRBWAM.CRBPLEDGEDRECEIVABLES,
	CSALM.ATLAS_PLEDGED_RECEIVABLES_CS,
	ROUND((CSALM.ATLAS_PLEDGED_RECEIVABLES_CS + CRBWAM.CRBPLEDGEDRECEIVABLES),2) TOTALPLEDGED,
	BALANCE_SHEET_EVAL_RG.PLEDGED_PER,
	BALANCE_SHEET_EVAL_RG.PLEDGEDPEROWNEDBOOK,
	BALANCE_SHEET_EVAL_RG.DEBTDRAWN,
	BALANCE_SHEET_EVAL_RG.DEBTDRAWNPEROWNEDBOOK,
	BALANCE_SHEET_EVAL_RG.DEBTDRAWN / (CRBWAM.ELIGIBLERECEIVABLESCRBWAM - CRBWAM.RECEIVABLESINCONCENTRATIONLIMITS_CR + CSALM.ELIGIBLE_RECEIVABLES_ATLAS -  CSALM.RECEIVABLESINCONCENTRATIONLIMITS_CS - CSALM.YSOC )  AS WAADVANCEDRATE,
	(CSALM.TOTALBORROWINGBASE_CS + CRBWAM.TOTALBORROWINGBASE_CR)/BALANCE_SHEET_EVAL_RG.FBX_RECEIVABLES EFFECTIVE_LEVERAGE,
	BALANCE_SHEET_EVAL_RG.DRAWNPERPLEDGED,
	BALANCE_SHEET_EVAL_RG.RESTRICTEDCASH,
	BALANCE_SHEET_EVAL_RG.CASH_ADJUSTEDLEVERAGE,
	BALANCE_SHEET_EVAL_RG.FBX_INC_MANAGED_RECEIVABLES,
	BALANCE_SHEET_EVAL_RG.FBX_INC_NOT_OWNED_RECEIVABLES,
	BALANCE_SHEET_EVAL_RG.FBX_INC_RECEIVABLES,
	BALANCE_SHEET_EVAL_RG.DQ_RECEIVABLES,
	BALANCE_SHEET_EVAL_RG.MATERIAL_MODIFICATIONS,
	BALANCE_SHEET_EVAL_RG.REPURCHASED_RECEIVABLES,
	BALANCE_SHEET_EVAL_RG.F52WEEKSQUADWEEKLY,
	BALANCE_SHEET_EVAL_RG.F52WEEKSFBXPLUS,
	BALANCE_SHEET_EVAL_RG.F52WEEKSTOTAL,
	BALANCE_SHEET_EVAL_RG.MANUALUW,
	BALANCE_SHEET_EVAL_RG.AUTOBOOKS_TOTAL,
	BALANCE_SHEET_EVAL_RG.MODEL_DEVELOPMENT,
	BALANCE_SHEET_EVAL_RG.BK_FRAUDS,
	BALANCE_SHEET_EVAL_RG.CREDIT_LIMIT_MAX,
	BALANCE_SHEET_EVAL_RG.REMAINING_BALANCE,
	BALANCE_SHEET_EVAL_RG.DQ_RECEIVABLESPER,
	BALANCE_SHEET_EVAL_RG.NONLOC,
	BALANCE_SHEET_EVAL_RG.MATERIAL_MODIFICATIONPER,
	BALANCE_SHEET_EVAL_RG.REPURCHASED_RECEIVABLESPER,
	BALANCE_SHEET_EVAL_RG.F52WEEKSQUADWEEKLYPER,
	BALANCE_SHEET_EVAL_RG.F52WEEKSFBXPLUSPER,
	BALANCE_SHEET_EVAL_RG.F52WEEKSTOTALPER,
	BALANCE_SHEET_EVAL_RG.F52WEEKS_RISKSCORE8PER,
	BALANCE_SHEET_EVAL_RG.F52WEEKS_RISKSCORE8,
	BALANCE_SHEET_EVAL_RG.F52WEEKS_RISKSCORE7,
    BALANCE_SHEET_EVAL_RG.F52WEEKS_RISKSCORE7PER,
	BALANCE_SHEET_EVAL_RG.F52WEEKS_DOO,
	BALANCE_SHEET_EVAL_RG.F52WEEKS_DOO_PER,
	BALANCE_SHEET_EVAL_RG.F52WEEKS_REM,
	BALANCE_SHEET_EVAL_RG.F52WEEKS_REM_PER,
	BALANCE_SHEET_EVAL_RG.MANUALUNDEWRITINGPER,
	BALANCE_SHEET_EVAL_RG.AUTOBOOKSPER,
	BALANCE_SHEET_EVAL_RG.MODELDEVELOPMENTPER,
	BALANCE_SHEET_EVAL_RG.BKORFRAUDPER,
	BALANCE_SHEET_EVAL_RG.CREDITLIMITMAXPER,
	BALANCE_SHEET_EVAL_RG.REMAININGBALANCEPER,
	-- BALANCE_SHEET_EVAL_RG.FBX_RECEIVABLES,
--	Credit Suisse Atlas - LibreMax Metrics
	-- CSALM.ATLAS_PLEDGED_RECEIVABLES_CS,
	CSALM.PER_PLEDGED_TO_ATLAS,
	CSALM.ELIGIBLE_RECEIVABLES_ATLAS,
	CSALM.PER_ELIGIBLE_CS,
	CSALM.YSOC,
	CSALM.YSOCPER,
	CSALM.TOTALBORROWINGBASE_CS,
	CSALM.EFFECTIVE_LEVERAGE_CS,
	CSALM.RESTRICTEDCASH_CS,
	CSALM.CASH_ADJUSTEDLEVERAGE_CS,
	CSALM.TOTAL_DEBT_DRAWN_CS,
	CSALM.REALIZED_LEVERAGE_CS,
--	Ineligibles
	CSALM.REPURCHASEDRECEIVABLESATLAS,
	CSALM.PER_REPURCHASEDRECEVIABLES_CS,
	CSALM.CORECEIVABLESATLAS,
	CSALM.PER_CHARGED_OFF_CS,
	CSALM.DELINQUENTRECEIVABLESDPD21PLUS_CS,
	CSALM.PER_DELINQUENT_CS,
	CSALM.F52WEEKSRECEIVABLESANDNOTFUNDBOXPLUS_CS,
	CSALM.PER_52WEEKSANDNOTFUNDBOXPLUS_CS, 
	CSALM.MATERIALMODS_CS,
	CSALM.PER_MATERIALMODS_CS,
	CSALM.BREATHERS_CS,
	CSALM.PER_BREATHERS_CS,
--	Excess Concentration
	CSALM.RISKSCOREGG13_TOTAL_CS,
	CSALM.MODIFICATIONS_TOTAL_CS,
	CSALM.CREDITLIMITG$100K_CS,
	CSALM.CREDITLIMITG$120K_CS,
	CSALM.PER_RISK_SCOREGG13_CS,
	CSALM.PER_MODIFICATIONS_CS,
	CSALM.PER_CREDITLIMITG$100K_CS,
	CSALM.PER_CREDITLIMITG$120K_CS,
	CSALM.RECEIVABLESINCONCENTRATIONLIMITS_CS,
	CSALM.PER_EXCESSCONCENTRATION_CS,
--	Book Strats
	CSALM.WAVANATAGESCORE_CS,
	CSALM.WARISKSCORE_CS,
	CSALM.WATERM_CS,
--	Cross River Bank - Waterfall Asset Management Metrics
	-- BALANCE_SHEET_EVAL_RG.FBX_RECEIVABLES,
	-- CRBWAM.CRBPLEDGEDRECEIVABLES,
	CRBWAM.PER_PLEDGEDTOCRBWAM,
	CRBWAM.ELIGIBLERECEIVABLESCRBWAM,
	CRBWAM.PER_ELIGIBLE_CR,
	CRBWAM.TOTALBORROWINGBASE_CR,
	CRBWAM.EFFECTIVE_LEVERAGE_CR,
	CRBWAM.TOTAL_DEBT_DRAWN_CR,
	CRBWAM.REALIZED_LEVERAGE_CR,
	CRBWAM.RESTRICTEDCASH_CRB,
	CRBWAM.CASH_ADJUSTEDLEVERAGE_CRB,
	CRBWAM.REPURCHASEDRECEIVABLESCRBWAM,
	CRBWAM.PER_REPURCHASEDRECEVIABLES_CR,
	CRBWAM.CORECEIVABLESCRBWAM,
	CRBWAM.PER_CHARGED_OFF_CR,
--	Ineligibles
	CRBWAM.DELINQUENTRECEIVABLESDPD21PLUS_CR,
	CRBWAM.PER_DELINQUENT_CR,
	-- CRBWAM.F52WEEKSRECEIVABLESANDNOTFUNDBOXPLUS_CS,
	-- CRBWAM.PER_52WEEKSANDNOTFUNDBOXPLUS_CS, 
	CRBWAM.MATERIALMODS_CR,
	CRBWAM.PER_MATERIALMODS_CR,
	CRBWAM.BREATHERS_CR,
	CRBWAM.PER_BREATHERS_CR,
--	Excess Concentration
	CRBWAM.RISKSCOREGG13_TOTAL_CR,
	CRBWAM.MODIFICATIONS_TOTAL_CR,
	CRBWAM.VANTAGESCOREISZEROTOTAL_CR,
	CRBWAM.AVERAGECREDITLIMIT_CR,
	CRBWAM.CREDITLIMITG$120K_CR,
	CRBWAM.PER_RISK_SCOREGG13_CR,
	CRBWAM.PER_MODIFICATIONS_CR,
	CRBWAM.PER_VANTAGESCOREISZERO_CR,
	CRBWAM.PER_CREDITLIMITG$120K_CR,
	CRBWAM.PER_52W,
	CRBWAM.PER_52W_RISKSCORE,
	CRBWAM.RECEIVABLESINCONCENTRATIONLIMITS_CR,
	CRBWAM.PER_EXCESSCONCENTRATION_CR,
--	Book Strats
	CRBWAM.WAVANATAGESCORE_CR,
	CRBWAM.WARISKSCORE_CR,
    CRBWAM.WA52W_RISKSCORE,
	CRBWAM.WATERM_CR,
	CRBWAM.WA52W_NEWLOANS
FROM INDUS.PUBLIC.BALANCE_SHEET_EVAL_RG
JOIN ANALYTICS.CAPITAL_MARKETS.CSALM
	ON BALANCE_SHEET_EVAL_RG.EDATE = CSALM.EDATE
JOIN ANALYTICS.CAPITAL_MARKETS.CRBWAM
	ON BALANCE_SHEET_EVAL_RG.EDATE = CRBWAM.EDATE
ORDER BY BALANCE_SHEET_EVAL_RG.EDATE ASC;
	

--Newly Allocated Loans - should be in a separate tab

-- CREATE OR REPLACE TEMPORARY TABLE NEW_TRANSFERS AS

CREATE OR REPLACE TABLE INDUS.PUBLIC.CAP_MARKET_23 AS
SELECT
	NEW_TRANSFER_DATE,
    CASE 
        WHEN DAYNAME(NEW_TRANSFER_DATE) = 'Wednesday' THEN NEW_TRANSFER_DATE  
        ELSE NEXT_DAY(NEW_TRANSFER_DATE, 'WEDNESDAY') 
    END AS week_end_date,
	ACTUAL_SPV SPV,
	VINTAGE,
	NEW_OR_EXISTING,
	FBX_PLUS,
	CASE
		WHEN RISK_SCORE_TRUE BETWEEN 1 AND 5 THEN '1 TO 5'
		WHEN RISK_SCORE_TRUE BETWEEN 6 AND 8 THEN '6 TO 8'
		WHEN RISK_SCORE_TRUE BETWEEN 9 AND 11 THEN '9 TO 11'
		WHEN RISK_SCORE_TRUE BETWEEN 13 AND 15 THEN '13 TO 15'
	END RISK_BUCKET,
	ORIGINAL_TERM,
	ACQ_CHANNEL,
	IS_MODEL_DEVELOPMENT,
	SUM(OS) NEW_TRANSFERED_ASSETS
FROM 
	(
	SELECT
		DISTINCT A.LOAN_KEY,
		SETPOINT_SPV.EDATE NEW_TRANSFER_DATE,
	    CASE
		    WHEN A.EDATE > '1/31/2025' THEN TO_SPV
			WHEN SPV::STRING = 'FBX_PT4' THEN 'FBX_PT4'
			ELSE 'FBX_INC'
	    END ACTUAL_SPV,
	    CASE
	    	WHEN UPPER(DACD.FUNDBOX_PLUS_STATUS) LIKE '%SUBSCRIBED%' THEN 1
	    	ELSE 0
	    END FBX_PLUS,	    
		CASE
			WHEN IS_CHARGED_OFF = 0 THEN OUTSTANDING_PRINCIPAL_FUNDED
		END OS,
		LAST_DAY(LOAN_CREATED_DATE) VINTAGE,
		ORIGINAL_TERM,
        coalesce(OBS.OB_TO_USE,CURRENT_ONBOARDING  ) as OB_USED,
		COALESCE(CSR.risk_score, JUNE.risk_Score , OG_SCORE, OB_USED) RISK_SCORE_TRUE,
	    SUB_PRODUCT,
	    CASE
	    	WHEN LAST_DAY(A.LOAN_CREATED_DATE, 'week') = LAST_DAY(FIRST_APPROVED_TIME::DATE, 'week') THEN 'New Customer' 
	    	ELSE 'Existing Customer'
	    END NEW_OR_EXISTING,    
		CASE
			WHEN LOWER(REGEXP_REPLACE(TRIM(CD.REGISTRATION_CAMPAIGN_ID), '\s+\d+$', '')) = LOWER(REGEXP_REPLACE(TRIM(TB.TERMINATED_BROKERS), '\s+\d+$', '')) THEN 'Brokers'
			WHEN PN.PARTNER_NAME = 'Intuit' THEN 'Intuit'
			WHEN LOWER(CD.REGISTRATION_CAMPAIGN_ID) IN ('intuit', 'intuit_appcenter', 'quickbooks-financing', 'intuit_campaigns') OR LOWER(REGISTRATION_CAMPAIGN_ID) LIKE '%intuit%' THEN 'Intuit'
			WHEN PN.PARTNER_NAME = 'Nav' THEN 'NAV'
			WHEN PN.PARTNER_NAME IN ('Lendingtree', 'Lendio') THEN 'Marketplace'
			WHEN LOWER(REGEXP_REPLACE(TRIM(CD.PARTNER_ATTRIBUTION), '\s+\d{4}$', '')) = LOWER(REGEXP_REPLACE(TRIM(PN.PARTNER_ATTRIBUTION), '\s+\d{4}$', '')) THEN 'Strategic Partners'
			WHEN LOWER(REGEXP_REPLACE(TRIM(CD.PARTNER_ATTRIBUTION), '\s+\d{4}$', '')) = LOWER(REGEXP_REPLACE(TRIM(PN.PARTNER_NAME), '\s+\d{4}$', '')) THEN 'Strategic Partners'
			WHEN LOWER(CD.PARTNER_ATTRIBUTION) IN ('organic','content', 'fundboxpay', 'content 100817571549') THEN 'Organic'
	        WHEN LOWER(CD.PARTNER_ATTRIBUTION) LIKE '%direct%' THEN 'Direct'
			WHEN (PN.PARTNER_NAME IS NULL AND CD.PARTNER_ATTRIBUTION IN ('non-partner')) THEN 'Organic'
			WHEN (PN.PARTNER_NAME IS NULL) THEN 'Terminated Channel'
			ELSE 'Brokers'
		END ACQ_CHANNEL,
	    CASE
	    	WHEN (IS_SAVED_BY_CONTROL_GROUP+IS_SAVED_BY_PARTNERSHIP) > 0 THEN 1
	    	ELSE 0
	    END IS_MODEL_DEVELOPMENT
	FROM ANALYTICS.CAPITAL_MARKETS.PLEDGE_DATES
	LEFT JOIN BI.FINANCE.FINANCE_METRICS_DAILY A
		ON A.EDATE = PLEDGE_DATES.EDATE
	LEFT JOIN (SELECT FBBID, EDATE, FUNDBOX_PLUS_STATUS, SUB_PRODUCT, RISK_CREDIT_REVIEW_MODEL_NAME, RISK_CREDIT_REVIEW_ALIGNED_BUCKET, YEAR_STARTED_EDATE, STATE,
	        CREDIT_SCORE_JSON, INDUSTRY_NAICS_CODE_EDATE, CREDIT_LIMIT, IS_SAVED_BY_CONTROL_GROUP, FIRST_APPROVED_TIME, IS_SAVED_BY_PARTNERSHIP FROM BI.PUBLIC.DAILY_APPROVED_CUSTOMERS_DATA) DACD
	        ON A.FBBID = DACD.FBBID AND A.LOAN_CREATED_DATE = DACD.EDATE
	LEFT JOIN SETPOINT_APPROVED_REPORT_DATA.RESULTS.REPORT_APPROVAL_RESULTS SETPOINT_SPV
		ON A.LOAN_KEY = SETPOINT_SPV.LOAN_KEY AND A.EDATE = SETPOINT_SPV.EDATE
	LEFT JOIN 
			(
			  SELECT
			    D.FBBID,
			    D.EDATE,
			    LAST_VALUE(CASE WHEN D.RISK_CREDIT_REVIEW_MODEL_NAME IN ('UnifiedOngoingMLEModelV2.2', 'sm-internalmodel_unified_og_v2.2_shap', 'smm-ongoing-SV-v2-2-shap', 'smm-ongoing-SV-v2-2-shap-sbd-v2') 
			    	THEN D.RISK_CREDIT_REVIEW_ALIGNED_BUCKET ELSE OG.RETRO_SCORE END) OVER(PARTITION BY D.FBBID, D.EDATE ORDER BY D.EDATE) AS OG_SCORE
			  FROM BI.PUBLIC.DAILY_APPROVED_CUSTOMERS_DATA AS d
			    LEFT JOIN (
			      SELECT
			        FBBID,
			        SCORE_DT,
			        FIRST_VALUE(UNI_BKT) IGNORE NULLS OVER(PARTITION BY FBBID ORDER BY SCORE_DT) AS RETRO_SCORE,
			        FIRST_VALUE(OG_SCORE) IGNORE NULLS OVER(PARTITION BY FBBID ORDER BY SCORE_DT) AS SCORE_SPECIFIC
			      FROM
			        (
			          SELECT
			            CAST(PREDICTION_TIME AS DATE) AS SCORE_DT,
			            IDENTIFIER_ID AS FBBID,
			            SCORE AS OG_SCORE,
			            CASE
			              WHEN SCORE <= 0.016 THEN 1
			              WHEN SCORE <= 0.019 THEN 2
			              WHEN SCORE <= 0.025 THEN 3
			              WHEN SCORE <= 0.03 THEN 4
			              WHEN SCORE <= 0.036 THEN 5
			              WHEN SCORE <= 0.043 THEN 6
			              WHEN SCORE <= 0.052 THEN 7
			              WHEN SCORE <= 0.063 THEN 8
			              WHEN SCORE <= 0.08 THEN 9
			              WHEN SCORE <= 0.11 THEN 10
			              WHEN SCORE <= 0.122 THEN 11
			              WHEN SCORE <= 0.135 THEN 12
			              WHEN SCORE <= 0.156 THEN 13
			              WHEN SCORE <= 0.195 THEN 14
			              WHEN SCORE <= 1 THEN 15
			            END AS UNI_BKT
			          FROM CDC_V2.SCORING.SCORING_MODEL_SCORES
			          WHERE MODEL_NAME IN ('UnifiedOngoingMLEModelV2.2', 'sm-internalmodel_unified_og_v2.2_shap', 'smm-ongoing-SV-v2-2-shap', 'smm-ongoing-SV-v2-2-shap-sbd-v2')
			        )
			    ) AS OG 
			    ON D.FBBID = OG.FBBID
			    	AND D.EDATE = OG.SCORE_DT
			) OG_MODEL
			ON A.FBBID = OG_MODEL.FBBID AND A.LOAN_CREATED_DATE = OG_MODEL.EDATE
	LEFT JOIN 
		(
		  SELECT
		    DISTINCT IDENTIFIER_ID AS FBBID,
		    CASE
		      WHEN SCORE <= 0.01 THEN 1
		      WHEN SCORE <= 0.02 THEN 2
		      WHEN SCORE <= 0.03 THEN 3
		      WHEN SCORE <= 0.04 THEN 4
		      WHEN SCORE <= 0.05 THEN 5
		      WHEN SCORE <= 0.06 THEN 6
		      WHEN SCORE <= 0.07 THEN 7
		      WHEN SCORE <= 0.08 THEN 8
		      WHEN SCORE <= 0.09 THEN 9
		      WHEN SCORE <= 0.1 THEN 10
		      WHEN SCORE <= 0.125 THEN 11
		      WHEN SCORE <= 0.150 THEN 12
		      WHEN SCORE <= 0.175 THEN 13
		      WHEN SCORE <= 0.2 THEN 14
		      WHEN SCORE <= 1 THEN 15
		    END AS CURRENT_ONBOARDING
		  FROM CDC_V2.SCORING.SCORING_MODEL_SCORES
		  WHERE MODEL_NAME = 'smm-eaglet-SV-dac-v9-9-v3'
		  QUALIFY ROW_NUMBER() OVER(PARTITION BY IDENTIFIER_ID ORDER BY PREDICTION_TIME DESC) = 1
		) OB
		ON A.FBBID = OB.FBBID
     left join (select loan_key, risk_score, FBBID from ANALYTICS.CAPITAL_MARKETS.DATA_ROOM_LOAN_TAPE_JUNE2025) JUNE
            on June.loan_key = A.loan_key
    left join ANALYTICS.CAPITAL_MARKETS.CS_RISK_SCORES CSR
            on CSR.loan_key = A.loan_key
    left join ANALYTICS.CAPITAL_MARKETS.OB_SCORES OBS
                on OBS.loan_key = A.loan_key
	LEFT JOIN (SELECT FBBID, PARTNER_ATTRIBUTION, REGISTRATION_CAMPAIGN_ID FROM BI."PUBLIC".CUSTOMERS_DATA) CD
	        ON A.FBBID = CD.FBBID
	LEFT JOIN ANALYTICS.CREDIT.EG_PA_TO_PN PN 
		ON LOWER(REGEXP_REPLACE(TRIM(CD.PARTNER_ATTRIBUTION), '\s+\d{4}$', '')) = LOWER(REGEXP_REPLACE(TRIM(PN.PARTNER_ATTRIBUTION), '\s+\d{4}$', ''))
			OR LOWER(REGEXP_REPLACE(TRIM(CD.PARTNER_ATTRIBUTION), '\s+\d{4}$', '')) = LOWER(REGEXP_REPLACE(TRIM(PN.PARTNER_NAME), '\s+\d{4}$', ''))
	LEFT JOIN ANALYTICS.CAPITAL_MARKETS.TERMINATED_BROKERS TB
		ON LOWER(REGEXP_REPLACE(TRIM(CD.REGISTRATION_CAMPAIGN_ID), '\s+\d{4}$', '')) = LOWER(REGEXP_REPLACE(TRIM(TB.TERMINATED_BROKERS), '\s+\d{4}$', ''))
        
    WHERE YEAR(A.EDATE) > 2024
    )
WHERE SPV IN ('FBX_PT5', 'FBX_PT6')
	AND RISK_BUCKET IS NOT NULL
GROUP BY ALL;