CREATE OR REPLACE TABLE INDUS."PUBLIC".CREDIT_BUILDER_STATE_SHELL
(
STATE_CA_GA VARCHAR(10)
);

INSERT INTO INDUS."PUBLIC".CREDIT_BUILDER_STATE_SHELL (STATE_CA_GA)
VALUES
    ('YES'),
   ('NO');
  
CREATE OR REPLACE TABLE INDUS."PUBLIC".CREDIT_BUILDER_REVENUE_SHELL
(
REVENUE_BUCKETS VARCHAR(20)
);

INSERT INTO INDUS."PUBLIC".CREDIT_BUILDER_REVENUE_SHELL (REVENUE_BUCKETS)
VALUES
    ('<100K'),
   ('100K - 600K'),
  ('>600K'),
 ('No Bucket');
 
CREATE OR REPLACE TABLE INDUS."PUBLIC".CREDIT_BUILDER_FICO_SHELL
(
FICO_BUCKETS VARCHAR(20)
);

INSERT INTO INDUS."PUBLIC".CREDIT_BUILDER_FICO_SHELL (FICO_BUCKETS)
VALUES
    ('300-350'),
   ('351-400'),
  ('401-450'),
 ('451-500'),
   ('501-550'),
  ('551-600'),
 ('601-650'),
   ('651-700'),
  ('701-750'),
 ('751-800' ),
('No Bucket');

CREATE OR REPLACE TABLE INDUS."PUBLIC".CREDIT_BUILDER_UTIL_SHELL
(
UTIL_BUCKETS VARCHAR(20)
);

INSERT INTO INDUS."PUBLIC".CREDIT_BUILDER_UTIL_SHELL (UTIL_BUCKETS)
VALUES
    ('0-10%'),
   ('11-20%'),
  ('21-30%'),
 ('31-40%'),
   ('41-50%'),
  ('51-60%'),
 ('61-70%'),
   ('71-80%'),
  ('81-90%'),
 ('91-100%' ),
('No Bucket');

CREATE OR REPLACE TABLE INDUS."PUBLIC".CREDIT_BUILDER_RISK_SHELL
(
RISK_BUCKETS VARCHAR(20)
);

INSERT INTO INDUS."PUBLIC".CREDIT_BUILDER_RISK_SHELL (RISK_BUCKETS)
VALUES
    ('1-4'),
   ('5-7'),
  ('8-9'),
  ('10-12'),
  ('13+'),
 ('No Bucket');
 
