CREATE OR REPLACE TABLE INDUS."PUBLIC".CREDIT_BUILDER_KM_VIEW_TEST_19 AS
(
WITH CREDIT_BUILDER_POPULATION AS (
select fbbid,
credit_builder_status,
first_credit_builder_offer_time,
CASE
	WHEN dayofweek(current_date()) = 3 THEN DATE_TRUNC('WEEK',first_credit_builder_offer_time::date+4)::date+2
	WHEN datediff('day', first_credit_builder_offer_time::date, DATE_TRUNC('WEEK',current_date()+4)::date-5) < 0 AND datediff('day', first_credit_builder_offer_time::date, current_date()) <= 0 THEN NULL
	WHEN datediff('day', first_credit_builder_offer_time::date, DATE_TRUNC('WEEK',current_date()+4)::date-5) < 0 THEN current_date()-1
	ELSE DATE_TRUNC('WEEK', first_credit_builder_offer_time::date+4)::date+2
END FIRST_OFFERED_WEEK_END,
first_credit_builder_approval_time AS FIRST_APPROVED_TIME,
CASE
	WHEN dayofweek(current_date()) = 3 THEN DATE_TRUNC('WEEK',first_credit_builder_approval_time::date+4)::date+2
	WHEN datediff('day', first_credit_builder_approval_time::date, DATE_TRUNC('WEEK',current_date()+4)::date-5) < 0 AND datediff('day', first_credit_builder_approval_time::date, current_date()) <= 0 THEN NULL
	WHEN datediff('day', first_credit_builder_approval_time::date, DATE_TRUNC('WEEK',current_date()+4)::date-5) < 0 THEN current_date()-1
	ELSE DATE_TRUNC('WEEK', first_credit_builder_approval_time::date+4)::date+2
END FIRST_APPROVED_WEEK_END,
credit_builder_limit AS CREDIT_LIMIT,
--state,
date(first_draw_time) first_draw_date,
CASE
	WHEN dayofweek(current_date()) = 3 THEN DATE_TRUNC('WEEK',first_draw_date::date+4)::date+2
	WHEN datediff('day', first_draw_date::date, DATE_TRUNC('WEEK',current_date()+4)::date-5) < 0 AND datediff('day', first_draw_date::date, current_date()) <= 0 THEN NULL
	WHEN datediff('day', first_draw_date::date, DATE_TRUNC('WEEK',current_date()+4)::date-5) < 0 THEN current_date()-1
	ELSE DATE_TRUNC('WEEK', first_draw_date::date+4)::date+2
END FIRST_DRAW_WEEK_END,
first_draw_amount,
from bi.public.customers_rt_data_salesforce
where sub_product = 'Credit Builder'
ORDER BY FBBID),
 
CREDIT_BUILDER_CUSTOMERS_DATA AS (
 
SELECT CREDIT_BUILDER.*,
 
-- CD.FIRST_ALIGNED_BUCKET,
f.ob_dal_bucket,
 
(CASE WHEN f.ob_dal_bucket BETWEEN 1 AND 3 THEN '1-3'
WHEN f.ob_dal_bucket BETWEEN 4 AND 5 THEN '4-5'
WHEN f.ob_dal_bucket BETWEEN 6 AND 8 THEN '6-8'
WHEN f.ob_dal_bucket BETWEEN 9 AND 10 THEN '9-10'
WHEN f.ob_dal_bucket >=11 THEN '11+'
ELSE 'No Bucket' END) AS OB_RISK_BUCKET,
 
(CASE WHEN CD.PREQUAL_ANNUAL_REVENUE_RANGE IN ('0K-100K')  THEN 50000
WHEN CD.PREQUAL_ANNUAL_REVENUE_RANGE IN ('100K-200K') THEN 150000
WHEN CD.PREQUAL_ANNUAL_REVENUE_RANGE IN ('200K-300K') THEN 250000
WHEN CD.PREQUAL_ANNUAL_REVENUE_RANGE IN ('300K-600K')   THEN 450000
WHEN CD.PREQUAL_ANNUAL_REVENUE_RANGE IN ('600K-1M') THEN  750000
WHEN CD.PREQUAL_ANNUAL_REVENUE_RANGE IN ('>1M')   THEN 1000000
ELSE 0 END) AS AVERAGE_REVENUE,
 
(CASE WHEN CD.FICO_ONBOARDING BETWEEN 300 AND 350 THEN '300-350'
WHEN CD.FICO_ONBOARDING BETWEEN 351 AND 400 THEN '351-400'
WHEN CD.FICO_ONBOARDING BETWEEN 401 AND 450 THEN '401-450'
WHEN CD.FICO_ONBOARDING BETWEEN 451 AND 500 THEN '451-500'
WHEN CD.FICO_ONBOARDING BETWEEN 501 AND 550 THEN '501-550'
WHEN CD.FICO_ONBOARDING BETWEEN 551 AND 600 THEN '551-600'
WHEN CD.FICO_ONBOARDING BETWEEN 601 AND 650 THEN '601-650'
WHEN CD.FICO_ONBOARDING BETWEEN 651 AND 700 THEN '651-700'
WHEN CD.FICO_ONBOARDING BETWEEN 701 AND 750 THEN '701-750'
WHEN CD.FICO_ONBOARDING BETWEEN 751 AND 800 THEN '751-800'
ELSE 'No Bucket' END) AS FICO_BUCKET,
 
CD.FICO_ONBOARDING,
 
(CASE WHEN CD.PREQUAL_ANNUAL_REVENUE_RANGE IN (NULL,'0K-100K')  THEN '<100K'
WHEN CD.PREQUAL_ANNUAL_REVENUE_RANGE IN ('100K-200K','200K-300K','300K-600K')   THEN '100K - 600K'
WHEN CD.PREQUAL_ANNUAL_REVENUE_RANGE IN ('600K-1M','>1M')   THEN '>600K'
ELSE 'No Bucket' END) AS REVENUE_BUCKET,
 
CASE WHEN CD.PREQUAL_YEARS_IN_BUSINESS_RANGE IS NULL THEN 'No Bucket'
ELSE CD.PREQUAL_YEARS_IN_BUSINESS_RANGE END AS YEARS_IN_BUSINESS,
 
FROM
CREDIT_BUILDER_POPULATION CREDIT_BUILDER
LEFT JOIN
BI.PUBLIC.CUSTOMERS_DATA CD
ON CREDIT_BUILDER.FBBID = CD.FBBID
LEFT JOIN
(
select distinct fbbid, ob_dal_bucket
from INDUS.PUBLIC.INDUS_KEY_METRICS_FILTERS) f
ON CREDIT_BUILDER.FBBID = f.FBBID
ORDER BY FBBID
),
 
CREDIT_BUILDER_CUSTOMERS_DATA_DACD AS (
SELECT
DACD.FBBID,
DACD.CREDIT_LIMIT_START_TIME::DATE AS CREDIT_LIMIT_START_DATE,
CASE
	WHEN dayofweek(current_date()) = 3 THEN DATE_TRUNC('WEEK',CREDIT_LIMIT_START_DATE+4)::date+2
	WHEN datediff('day', CREDIT_LIMIT_START_DATE, DATE_TRUNC('WEEK',current_date()+4)::date-5) < 0 AND datediff('day', CREDIT_LIMIT_START_DATE, current_date()) <= 0 THEN NULL
	WHEN datediff('day', CREDIT_LIMIT_START_DATE, DATE_TRUNC('WEEK',current_date()+4)::date-5) < 0 THEN current_date()-1
	ELSE DATE_TRUNC('WEEK', CREDIT_LIMIT_START_DATE+4)::date+2
END CREDIT_LIMIT_WEEK_END,
 
CASE
	WHEN dayofweek(current_date()) = 3 THEN DATE_TRUNC('WEEK',DACD.EDATE::date+4)::date+2
	WHEN datediff('day', DACD.EDATE::date, DATE_TRUNC('WEEK',current_date()+4)::date-5) < 0 AND datediff('day', DACD.EDATE::date, current_date()) <= 0 THEN NULL
	WHEN datediff('day', DACD.EDATE::date, DATE_TRUNC('WEEK',current_date()+4)::date-5) < 0 THEN current_date()-1
	ELSE DATE_TRUNC('WEEK', DACD.EDATE::date+4)::date+2
END WEEK_END,

CASE WHEN LOWER(CD.REGISTRATION_CAMPAIGN_NAME) LIKE LOWER('%business%loan%') THEN 'Business Loans'
WHEN DACD.STATE = 'CA' OR DACD.STATE = 'GA' THEN 'YES'
ELSE 'NO' END AS STATE_CA_GA,
 
(CASE WHEN DACD.CREDIT_STATUS = 'approved' AND (DACD.IS_LOCKED_DASHBOARD=0 OR DACD.DASHBOARD_STATUS_CHANGE_REASON = 'full_utilization')
AND DACD.CREDIT_LIMIT>0
THEN DACD.FBBID ELSE NULL END) AS ABLE_TO_DRAW,
 
(CASE WHEN DACD.RISK_CREDIT_REVIEW_ALIGNED_BUCKET BETWEEN 1 AND 4 THEN '1-4'
WHEN  DACD.RISK_CREDIT_REVIEW_ALIGNED_BUCKET BETWEEN 5 AND 7 THEN '5-7'
WHEN  DACD.RISK_CREDIT_REVIEW_ALIGNED_BUCKET BETWEEN 8 AND 9 THEN '8-9'
WHEN  DACD.RISK_CREDIT_REVIEW_ALIGNED_BUCKET BETWEEN 10 AND 12 THEN '10-12'
WHEN  DACD.RISK_CREDIT_REVIEW_ALIGNED_BUCKET >=13 THEN '13+'
ELSE 'No Bucket' END) AS OG_RISK_BUCKET,
 
(CASE WHEN DACD.CREDIT_UTILIZATION <= 0.1 THEN '0-10%'
WHEN DACD.CREDIT_UTILIZATION >0.1 AND DACD.CREDIT_UTILIZATION <=0.2 THEN '11-20%'
WHEN DACD.CREDIT_UTILIZATION > 0.2 AND DACD.CREDIT_UTILIZATION <= 0.3 THEN '21-30%'
WHEN DACD.CREDIT_UTILIZATION > 0.3 AND DACD.CREDIT_UTILIZATION <=0.4 THEN '31-40%'
WHEN DACD.CREDIT_UTILIZATION > 0.4 AND DACD.CREDIT_UTILIZATION <= 0.5 THEN '41-50%'
WHEN DACD.CREDIT_UTILIZATION > 0.5 AND DACD.CREDIT_UTILIZATION <= 0.6 THEN '51-60%'
WHEN DACD.CREDIT_UTILIZATION > 0.6 AND DACD.CREDIT_UTILIZATION <= 0.7 THEN '61-70%'
WHEN DACD.CREDIT_UTILIZATION >0.7 AND DACD.CREDIT_UTILIZATION <= 0.8 THEN '71-80%'
WHEN DACD.CREDIT_UTILIZATION > 0.8 AND DACD.CREDIT_UTILIZATION <= 0.9 THEN '81-90%'
WHEN DACD.CREDIT_UTILIZATION > 0.9 AND DACD.CREDIT_UTILIZATION <=1 THEN '91-100%'
ELSE 'No Bucket' END
) AS UTIL_BUCKET,
DACD.CREDIT_STATUS,
DACD.CREDIT_UTILIZATION,
DACD.IS_CHARGEOFF,
DACD.DPD_DAYS,
DACD.ACCOUNT_STATUS,
FMD.tot_orig,
FMD1.outstanding_principal_due,
DACD2.ATD_EXPO,
IND_CD.calc_revenue,
IND_CD.calc_revenue1,
CDC.ORIG_FEE

FROM
(select *,
		CASE
	WHEN dayofweek(current_date()) = 3 THEN DATE_TRUNC('WEEK',EDATE::date+4)::date+2
	WHEN datediff('day', EDATE::date, DATE_TRUNC('WEEK',current_date()+4)::date-5) < 0 AND datediff('day', EDATE::date, current_date()) <= 0 THEN NULL
	WHEN datediff('day', EDATE::date, DATE_TRUNC('WEEK',current_date()+4)::date-5) < 0 THEN current_date()-1
	ELSE DATE_TRUNC('WEEK', EDATE::date+4)::date+2
	END WEEK_END
from BI.PUBLIC.DAILY_APPROVED_CUSTOMERS_DATA
WHERE FBBID IN (SELECT FBBID FROM CREDIT_BUILDER_POPULATION)
AND EDATE = WEEK_END
ORDER BY WEEK_END DESC,FBBID) DACD

LEFT JOIN
(SELECT FBBID, REGISTRATION_CAMPAIGN_NAME
 FROM INDUS.PUBLIC.customers_data) CD
ON DACD.FBBID = CD.FBBID 

left join 
(SELECT DISTINCT FBBID, loan_created_week_end_date,sum(originated_amount) tot_orig from
(SELECT DISTINCT fbbid,
loan_created_date,loan_key,
		CASE 
	WHEN dayofweek(current_date()) = 3 THEN DATE_TRUNC('WEEK', loan_created_date+4)::date+2
	WHEN datediff('day', loan_created_date, DATE_TRUNC('WEEK',current_date()+4)::date-5) < 0 AND datediff('day', loan_created_date, current_date()) <= 0 THEN NULL 
	WHEN datediff('day', loan_created_date, DATE_TRUNC('WEEK',current_date()+4)::date-5) < 0 THEN current_date()-1
	ELSE DATE_TRUNC('WEEK', loan_created_date::date+4)::date+2
    END loan_created_week_end_date,
	originated_amount   
	FROM (
SELECT * FROM BI.FINANCE.FINANCE_METRICS_DAILY 
WHERE PRODUCT_TYPE <> 'Flexpay' )
 WHERE FBBID IN (SELECT FBBID FROM CREDIT_BUILDER_POPULATION)) 
 GROUP BY 1,2) FMD
ON DACD.edate = FMD.loan_created_week_end_date
AND DACD.fbbid = FMD.fbbid
LEFT JOIN
(SELECT DISTINCT fbbid,
		CASE 
	WHEN dayofweek(current_date()) = 3 THEN DATE_TRUNC('WEEK', edate+4)::date+2
	WHEN datediff('day', edate, DATE_TRUNC('WEEK',current_date()+4)::date-5) < 0 AND datediff('day', edate, current_date()) <= 0 THEN NULL 
	WHEN datediff('day', edate, DATE_TRUNC('WEEK',current_date()+4)::date-5) < 0 THEN current_date()-1
	ELSE DATE_TRUNC('WEEK', edate::date+4)::date+2
    END week_end_date,
	SUM(outstanding_principal_due) outstanding_principal_due   
	FROM (
SELECT * FROM BI.FINANCE.FINANCE_METRICS_DAILY 
WHERE PRODUCT_TYPE <> 'Flexpay' )
	WHERE FBBID IN (SELECT FBBID FROM CREDIT_BUILDER_POPULATION)
	AND edate = week_end_date
	GROUP BY 1,2)FMD1
ON DACD.edate = FMD1.week_end_date
AND DACD.fbbid = FMD1.fbbid
LEFT JOIN
(
	SELECT FBBID, 
	CASE
		WHEN IS_CHARGEOFF = 0 
		AND account_status <> 'suspended'
		AND credit_status = 'approved'
		AND (is_locked_dashboard = 0 or is_locked_dashboard IS NULL
			OR (is_locked_dashboard = 1 and dashboard_status_change_reason = 'full_utilization'))
		THEN credit_limit
		ELSE 0
	END atd_expo,
	CASE 
		WHEN dayofweek(current_date()) = 3 THEN DATE_TRUNC('WEEK', edate+4)::date+2
		WHEN datediff('day', edate, DATE_TRUNC('WEEK',current_date()+4)::date-5) < 0 AND datediff('day', edate, current_date()) <= 0 THEN NULL 
		WHEN datediff('day', edate, DATE_TRUNC('WEEK',current_date()+4)::date-5) < 0 THEN current_date()-1
		ELSE DATE_TRUNC('WEEK', edate::date+4)::date+2
    END week_end_date
	FROM BI.PUBLIC.DAILY_APPROVED_CUSTOMERS_DATA 
	WHERE FBBID IN(
	SELECT FBBID
	FROM BI.PUBLIC.DAILY_APPROVED_CUSTOMERS_DATA
	WHERE SUB_PRODUCT = 'Credit Builder'
	)
	AND edate = week_end_date) DACD2
ON DACD.EDATE = DACD2.WEEK_END_DATE
AND DACD.FBBID = DACD2.FBBID
LEFT JOIN 
(	SELECT fbbid
		   ,(COALESCE(first_account_size_accounting_software,first_account_size_fi,0) * 12) calc_revenue
		   ,(COALESCE(first_account_size_accounting_software,first_account_size_fi) * 12) calc_revenue1
	FROM indus."PUBLIC".customers_data_indus) IND_CD
ON dacd.fbbid = IND_CD.FBBID 
LEFT JOIN 
(
	SELECT DISTINCT T1.FBBID, loan_created_week_end_date,sum(CHARGE_AMOUNT) ORIG_FEE
	FROM(
	SELECT *,
	JSON_EXTRACT_PATH_TEXT(EXTRA_DATA, 'direct_draw_id')::varchar AS loan_id
	FROM CDC_V2.payments.charges
	WHERE charge_type = 'LOAN_ORIGINATION_FEE'
	AND CDC_V2.payments.charges.status='PAID') T1
	LEFT JOIN( 
	SELECT FBBID, LOAN_ID, LOAN_KEY
	FROM bi."PUBLIC".LOAN_DATA) T2
	ON T1.FBBID = T2.FBBID
	AND T1.LOAN_ID = T2.LOAN_ID
	LEFT JOIN(
	(SELECT DISTINCT fbbid
	-- ,loan_created_date
    ,loan_key
	,CASE 
	WHEN dayofweek(current_date()) = 3 THEN DATE_TRUNC('WEEK', loan_created_date+4)::date+2
	WHEN datediff('day', loan_created_date, DATE_TRUNC('WEEK',current_date()+4)::date-5) < 0 AND datediff('day', loan_created_date, current_date()) <= 0 THEN NULL 
	WHEN datediff('day', loan_created_date, DATE_TRUNC('WEEK',current_date()+4)::date-5) < 0 THEN current_date()-1
	ELSE DATE_TRUNC('WEEK', loan_created_date::date+4)::date+2
    END loan_created_week_end_date   
	FROM (
SELECT * FROM BI.FINANCE.FINANCE_METRICS_DAILY 
WHERE PRODUCT_TYPE <> 'Flexpay' )
 	WHERE FBBID IN (SELECT FBBID FROM CREDIT_BUILDER_POPULATION))) T3
	ON T1.FBBID = T3.FBBID
	AND T2.LOAN_KEY = T3.loan_key
	GROUP BY 1,2
)cdc
ON dacd.fbbid = cdc.fbbid 
AND DACD.edate = cdc.loan_created_week_end_date),
-------------------------------------------------------------------------QC-------------------------------------------------------------------------
--SELECT fbbid, calc_revenue
--FROM CREDIT_BUILDER_CUSTOMERS_DATA_DACD
--
--SELECT count(*),count(DISTINCT fbbid)
--FROM indus."PUBLIC".customers_data_indus
--LIMIT 10
--
--SELECT fbbid, FIRST_APPROVED_ACCOUNT_SIZE_FI, FIRST_APPROVED_ACCOUNT_SIZE_ACCOUNTING_SOFTWARE 
--FROM indus.PUBLIC.CUSTOMERS_DATA_INDUS 
--WHERE fbbid = 1467994
--SELECT FBBID, WEEK_END, ATD_EXPO
--FROM CREDIT_BUILDER_CUSTOMERS_DATA_DACD
--
--SELECT FBBID, CREDIT_LIMIT
--FROM INDUS."PUBLIC".DAILY_APPROVED_CUSTOMERS_DATA 
--WHERE FBBID = 1308428
--AND EDATE = '2024-07-31'
--	SELECT fbbid, outstanding_principal_due

--	FROM CREDIT_BUILDER_CUSTOMERS_DATA_DACD
--	where fbbid = 1474112
-- Add Pranatahi's code here

--	SELECT fbbid, edate, outstanding_principal_due, 
--		   CASE 
--	WHEN dayofweek(current_date()) = 3 THEN DATE_TRUNC('WEEK', edate+4)::date+2
--	WHEN datediff('day', edate, DATE_TRUNC('WEEK',current_date()+4)::date-5) < 0 AND datediff('day', edate, current_date()) <= 0 THEN NULL 
--	WHEN datediff('day', edate, DATE_TRUNC('WEEK',current_date()+4)::date-5) < 0 THEN current_date()-1
--	ELSE DATE_TRUNC('WEEK', edate::date+4)::date+2
--    END week_end_date
--	FROM bi.REPORTS.FINANCE_METRICS_DAILY 
--	WHERE fbbid=1474112
--	AND EDATE = week_end_date
--WHERE dacd.fbbid = 1462611

--SELECT CREDIT_BUILDER_CUSTOMERS_DATA_DACD.FBBID,
--	   CREDIT_BUILDER_CUSTOMERS_DATA_DACD.WEEK_END,
--	   CREDIT_BUILDER_CUSTOMERS_DATA_DACD.ORIGINATED_AMOUNT
-- SELECT fbbid, sum(originated_amount)
-- FROM CREDIT_BUILDER_CUSTOMERS_DATA_DACD
-- GROUP BY 1;
-------------------------------------------------------------------------QC-------------------------------------------------------------------------

CREDIT_BUILDER_CUSTOMERS_DATA_DAILY AS (
SELECT
DACD.CREDIT_LIMIT_WEEK_END,
DACD.WEEK_END,
DACD.STATE_CA_GA,
DACD.ABLE_TO_DRAW,
DACD.OG_RISK_BUCKET,
DACD.UTIL_BUCKET,
DACD.CREDIT_STATUS,
DACD.CREDIT_UTILIZATION,
DACD.IS_CHARGEOFF,
DACD.DPD_DAYS,
DACD.ACCOUNT_STATUS,
DACD.tot_orig,
DACD.outstanding_principal_due,
DACD.ATD_EXPO,
DACD.CALC_REVENUE,
DACD.calc_revenue1,
DACD.ORIG_FEE,
CB.*
FROM
CREDIT_BUILDER_CUSTOMERS_DATA CB --daily fbbid data
LEFT JOIN
CREDIT_BUILDER_CUSTOMERS_DATA_DACD DACD --weekly fbbid data
ON CB.FBBID = DACD.FBBID
),
--------------weekly this week^^---

CREDIT_BUILDER_CUSTOMERS_DATA_WEEKLY AS (
SELECT DACD.*,
(CASE WHEN DACD.ABLE_TO_DRAW IS NOT NULL AND DACD_LAG.ABLE_TO_DRAW IS NULL THEN DACD.FBBID ELSE NULL END) AS ABLE_TO_DRAW_THIS_WEEK,
(CASE WHEN DACD.FIRST_APPROVED_WEEK_END = DACD.WEEK_END THEN DACD.FBBID ELSE NULL END) AS ACCEPTED_THIS_WEEK,
(CASE WHEN ACCEPTED_THIS_WEEK IS NOT NULL AND DACD.CREDIT_STATUS = 'approved' THEN DACD.FBBID ELSE NULL END) AS APPROVED_THIS_WEEK,
(CASE WHEN DACD.FIRST_DRAW_WEEK_END= DACD.WEEK_END THEN DACD.FBBID ELSE NULL END) FIRST_TIME_DRAW_THIS_WEEK,
(CASE WHEN DACD.CREDIT_STATUS = 'approved' AND (DACD_LAG.CREDIT_STATUS IS NULL OR DACD_LAG.CREDIT_STATUS <> 'approved') THEN DACD.CREDIT_UTILIZATION END) CREDIT_UTIL_THIS_WEEK,
(CASE WHEN DACD.FIRST_DRAW_WEEK_END= DACD.WEEK_END THEN DACD.FIRST_DRAW_AMOUNT END) AS DRAW_AMOUNT_THIS_WEEK,
(CASE WHEN ACCEPTED_THIS_WEEK IS NOT NULL THEN DACD.FICO_ONBOARDING END) AS FICO_OPTIN,
(CASE WHEN DACD.IS_CHARGEOFF=1 AND (DACD_LAG.IS_CHARGEOFF IS NULL OR DACD_LAG.IS_CHARGEOFF = 0) THEN DACD.FBBID ELSE NULL END) AS CHARGE_OFF_THIS_WEEK,
(CASE WHEN DACD.DPD_DAYS > 0 AND DACD_LAG.DPD_DAYS=0 THEN dacd.fbbid ELSE NULL END) AS DPD_THIS_WEEK,
DACD_LAG.ABLE_TO_DRAW as ABLE_TO_DRAW_LAST_WEEK,
FMD.cumm_org
FROM
CREDIT_BUILDER_CUSTOMERS_DATA_DAILY DACD
LEFT JOIN
CREDIT_BUILDER_CUSTOMERS_DATA_DAILY DACD_LAG
ON DACD.FBBID = DACD_LAG.FBBID
AND DACD.WEEK_END = DATEADD('DAY',7,DACD_LAG.WEEK_END)
LEFT JOIN
(SELECT DISTINCT fbbid,
	edate,
	CASE 
	WHEN dayofweek(current_date()) = 3 THEN DATE_TRUNC('WEEK', edate+4)::date+2
	WHEN datediff('day', edate, DATE_TRUNC('WEEK',current_date()+4)::date-5) < 0 AND datediff('day', edate, current_date()) <= 0 THEN NULL 
	WHEN datediff('day', edate, DATE_TRUNC('WEEK',current_date()+4)::date-5) < 0 THEN current_date()-1
	ELSE DATE_TRUNC('WEEK', edate::date+4)::date+2
    END week_end_date,
    sum(originated_amount) AS cumm_org
	FROM (
SELECT * FROM BI.FINANCE.FINANCE_METRICS_DAILY 
WHERE PRODUCT_TYPE <> 'Flexpay' )
 	WHERE FBBID IN (SELECT FBBID FROM CREDIT_BUILDER_POPULATION)
 	AND edate=week_end_date
 	GROUP BY 1,2,3) FMD
 ON DACD.FBBID = FMD.FBBID
AND DACD.WEEK_END = FMD.week_end_date
),

---------weekly last week^^-------------------------------


-- -- SELECT FBBID, week_end, tot_orig, outstanding_principal_due, ATD_EXPO, CALC_REVENUE
-- -- FROM CREDIT_BUILDER_CUSTOMERS_DATA_WEEKLY
-- -- ORDER BY fbbid, week_end desc 
 
--  SELECT percentile_cont(0.5) WITHIN GROUP (ORDER BY calc_revenue1) AS MEDIAN_REVENUE
--  FROM CREDIT_BUILDER_CUSTOMERS_DATA_WEEKLY
 
-- -- SELECT AVG(CALC_REVENUE)
-- -- FROM CREDIT_BUILDER_CUSTOMERS_DATA_WEEKLY

---------security deposit transactions-------------------------------
 
security_payments_txn AS
(SELECT a.fbbid,
		CASE
			WHEN dayofweek(current_date()) = 3 THEN DATE_TRUNC('WEEK',CREATED_DATE+4)::date+2
			WHEN datediff('day', CREATED_DATE, DATE_TRUNC('WEEK',current_date()+4)::date-5) < 0 AND datediff('day', CREATED_DATE, current_date()) <= 0 THEN NULL
			WHEN datediff('day', CREATED_DATE, DATE_TRUNC('WEEK',current_date()+4)::date-5) < 0 THEN current_date()-1
			ELSE DATE_TRUNC('WEEK', CREATED_DATE+4)::date+2
		END SECURITY_DEPOSIT_INIT_WEEK_END,
		CASE
			WHEN dayofweek(current_date()) = 3 THEN DATE_TRUNC('WEEK',a.TRANSMISSION_DATE+4)::date+2
			WHEN datediff('day', a.TRANSMISSION_DATE, DATE_TRUNC('WEEK',current_date()+4)::date-5) < 0 AND datediff('day', a.TRANSMISSION_DATE, current_date()) <= 0 THEN NULL
			WHEN datediff('day', a.TRANSMISSION_DATE, DATE_TRUNC('WEEK',current_date()+4)::date-5) < 0 THEN current_date()-1
			ELSE DATE_TRUNC('WEEK', a.TRANSMISSION_DATE+4)::date+2
		END SECURITY_DEPOSIT_WEEK_END,
		a.CREATED_DATE,
		a.STATUS,
		a.AMOUNT_IN_CENTS
		FROM
		(SELECT fbbid,
		CREATED_TIME::DATE AS CREATED_DATE,
		TRANSMISSION_DATE,
		STATUS,
		AMOUNT_IN_CENTS,
		ID,
		LAST_MODIFIED_TIME
		FROM CDC_V2.secured_payments.secured_payments_transactions
		WHERE BALANCE_TYPE='DEBIT') a
		INNER JOIN
		(SELECT fbbid,
			   max(LAST_MODIFIED_TIME) AS latest_update_time,
			   max(id) AS latest_id
			   FROM CDC_V2.secured_payments.secured_payments_transactions
			   WHERE BALANCE_TYPE='DEBIT'
			   GROUP BY 1) b
			   ON a.fbbid=b.fbbid
			   AND a.LAST_MODIFIED_TIME=b.latest_update_time
			   AND a.ID=b.latest_id),
 


CREDIT_BUILDER_CUSTOMERS_DATA_AGG AS 
(
SELECT
COALESCE(DACD.WEEK_END,DACD.FIRST_OFFERED_WEEK_END) AS WEEK_END_DATE_1,
COALESCE(DACD.STATE_CA_GA,'NO') AS STATE_GROUP_1,
COALESCE(DACD.REVENUE_BUCKET,'No Bucket')  AS REVENUE_BUCKET_1,
COALESCE(DACD.FICO_BUCKET,'No Bucket')  AS FICO_BUCKET_1,
COALESCE(DACD.OB_RISK_BUCKET,'No Bucket')  AS RISK_BUCKET_1,
COALESCE(DACD.UTIL_BUCKET,'No Bucket') AS UTIL_BUCKET_1,
COALESCE(DACD.YEARS_IN_BUSINESS,'0') AS YEARS_IN_BUSINESS_1,

SUM(CASE WHEN DACD.CREDIT_STATUS = 'approved' THEN DACD.FICO_ONBOARDING END) AS AVERAGE_APPROVED_FICO,
SUM(CASE WHEN DACD.CREDIT_STATUS = 'approved' AND DACD.CREDIT_LIMIT>0 THEN DACD.CREDIT_LIMIT END) AS AVERAGE_FUNDED_CREDIT_LIMIT,

count(DISTINCT DACD.ABLE_TO_DRAW_THIS_WEEK) AS ABLE_TO_DRAW_THIS_WEEK,
count(DISTINCT DACD.ACCEPTED_THIS_WEEK) AS ACCEPTED_THIS_WEEK,
count(DISTINCT DACD.APPROVED_THIS_WEEK) AS APPROVED_THIS_WEEK,
count(DISTINCT DACD.FIRST_TIME_DRAW_THIS_WEEK) AS FTD_THIS_WEEK,
SUM(DACD.CREDIT_UTIL_THIS_WEEK) AS UTIL_THIS_WEEK_AGG,
SUM(DACD.DRAW_AMOUNT_THIS_WEEK) AS DRAW_AMOUNT_THIS_WEEK,
count(DISTINCT DACD.CHARGE_OFF_THIS_WEEK) AS CHARGE_OFF_THIS_WEEK,
count(DISTINCT DACD.DPD_THIS_WEEK) AS DPD_THIS_WEEK,
SUM(DACD.tot_orig) AS TOTAL_ORIGINATIONS,
sum(DACD.cumm_org) AS Cummulative_Originations,
SUM(DACD.outstanding_principal_due) AS TOTAL_OUTSTANDING,
SUM(ATD_EXPO) AS TOTAL_ABLE_TO_DRAW_EXPOSURE,
--(CASE WHEN CAST(SUM(DACD.ORIG_FEE) AS INT)<> 0 THEN SUM(DACD.ORIG_FEE)/100 ELSE 0 END) AS TOTAL_ORIGINATION_FEE,
SUM(DACD.ORIG_FEE)/100 AS TOTAL_ORIGINATION_FEE,
-- percentile_cont(0.5) WITHIN GROUP (ORDER BY calc_revenue1) AS MEDIAN_REVENUE,

COUNT(DISTINCT CASE WHEN CDC.SECURITY_DEPOSIT_INIT_WEEK_END = DACD.WEEK_END AND CDC.STATUS IS NOT NULL AND CDC.FBBID IS NOT NULL THEN  DACD.FBBID END) AS TOTAL_CUST_SECURITY_DEPOSIT_INITIATED,

--COUNT(CASE WHEN CDC.SECURITY_DEPOSIT_WEEK_END = DACD.WEEK_END AND DACD.CREDIT_LIMIT>0 AND DACD.FIRST_APPROVED_TIME IS NOT NULL  AND CDC.STATUS IN ('APPROVED') THEN  DACD.FBBID END) AS TOTAL_CUST_SECURITY_DEPOSIT_CONFIRMED,
COUNT(DISTINCT CASE WHEN CDC.SECURITY_DEPOSIT_WEEK_END = DACD.WEEK_END AND DACD.FIRST_APPROVED_TIME IS NOT NULL AND DACD.CREDIT_LIMIT>0 AND CDC.STATUS IN ('APPROVED') THEN  DACD.FBBID END) AS TOTAL_CUST_SECURITY_DEPOSIT_CONFIRMED,


SUM(CASE WHEN CDC.SECURITY_DEPOSIT_INIT_WEEK_END = DACD.WEEK_END AND CDC.STATUS IN ('IN_PROGRESS','SCHEDULED') THEN  AMOUNT_IN_CENTS/100 END) AS TOTAL_SECURITY_DEPOSIT_INITIATED,
SUM(CASE WHEN DACD.CREDIT_LIMIT_WEEK_END = DACD.WEEK_END AND DACD.FIRST_APPROVED_TIME IS NOT NULL AND DACD.CREDIT_LIMIT>0 AND CDC.STATUS IN ('APPROVED') THEN  AMOUNT_IN_CENTS/100 END) AS TOTAL_SECURITY_DEPOSIT_CONFIRMED,

COUNT(DISTINCT CASE WHEN WEEK_END_DATE_1=DACD.FIRST_OFFERED_WEEK_END THEN DACD.FBBID END) AS ALL_OFFERED,
SUM(CASE WHEN WEEK_END_DATE_1=DACD.FIRST_OFFERED_WEEK_END THEN DACD.FICO_ONBOARDING END) AS FICO_ELIGIBLE,
SUM(CASE WHEN WEEK_END_DATE_1=DACD.FIRST_OFFERED_WEEK_END THEN DACD.AVERAGE_REVENUE END) AS REVENUE_ELIGIBLE,
--MAX(DACD.ALL_OFFERED) AS ALL_OFFERED,

--MAX(DACD.FICO_ELIGIBLE) AS FICO_ELIGIBLE,
SUM(DACD.FICO_OPTIN) AS FICO_OPTIN,
SUM(CASE WHEN CDC.SECURITY_DEPOSIT_INIT_WEEK_END = DACD.WEEK_END AND CDC.STATUS IS NOT NULL AND CDC.FBBID IS NOT NULL THEN DACD.FICO_ONBOARDING END) AS FICO_SECURITY_DEPOSIT_INITIATED,
SUM(CASE WHEN DACD.ABLE_TO_DRAW_THIS_WEEK IS NOT NULL THEN DACD.FICO_ONBOARDING END) AS FICO_ATD,

--MAX(DACD.REVENUE_ELIGIBLE) AS REVENUE_ELIGIBLE,
SUM(CASE WHEN ACCEPTED_THIS_WEEK IS NOT NULL THEN DACD.AVERAGE_REVENUE END) AS REVENUE_OPTIN,
SUM(CASE WHEN CDC.SECURITY_DEPOSIT_INIT_WEEK_END = DACD.WEEK_END AND CDC.STATUS IS NOT NULL  AND CDC.FBBID IS NOT NULL THEN DACD.AVERAGE_REVENUE END) AS REVENUE_SECURITY_DEPOSIT_INITIATED,
SUM(CASE WHEN DACD.ABLE_TO_DRAW_THIS_WEEK IS NOT NULL THEN DACD.AVERAGE_REVENUE END) AS REVENUE_ATD,

COUNT(DISTINCT CASE WHEN DACD.CREDIT_STATUS IS NOT NULL THEN DACD.FBBID END) AS TOTAL_ACCEPTED,
COUNT(DISTINCT CASE WHEN DACD.CREDIT_STATUS = 'approved' THEN DACD.FBBID END) AS TOTAL_APPROVED,
COUNT(DISTINCT CASE WHEN DACD.CREDIT_STATUS = 'approved' AND DACD.CREDIT_LIMIT>0 THEN DACD.FBBID END) AS TOTAL_FUNDED,
COUNT(DISTINCT CASE WHEN DACD.CREDIT_STATUS = 'approved' AND DACD.CREDIT_LIMIT<=0 THEN DACD.FBBID END) AS TOTAL_NOT_FUNDED,
COUNT(DISTINCT CASE WHEN DACD.ABLE_TO_DRAW IS NOT NULL THEN DACD.FBBID ELSE NULL END) AS TOTAL_ABLE_TO_DRAW,

SUM(CASE WHEN ACCEPTED_THIS_WEEK IS NOT NULL THEN ob_dal_bucket END) AS RISK_BUCKET_OPTIN,
COUNT(DISTINCT CASE WHEN ACCEPTED_THIS_WEEK IS NOT NULL AND ob_dal_bucket IS NOT NULL THEN DACD.FBBID END) AS RISK_BUCKET_OPTIN_DENOM,
-- SUM(DACD.FIRST_ALIGNED_BUCKET) AS RISK_BUCKET_OPTIN,
SUM(CASE WHEN DACD.ABLE_TO_DRAW_THIS_WEEK IS NOT NULL THEN ob_dal_bucket END) AS RISK_BUCKT_ATD,
COUNT(DISTINCT CASE WHEN DACD.ABLE_TO_DRAW_THIS_WEEK IS NOT NULL AND ob_dal_bucket IS NOT NULL THEN DACD.FBBID END) AS RISK_BUCKT_ATD_DENOM,

-- COUNT(DISTINCT CASE WHEN CDC.SECURITY_DEPOSIT_INIT_WEEK_END = DACD.WEEK_END AND CDC.STATUS IS NOT NULL AND CDC.FBBID IS NOT NULL THEN  DACD.FBBID END) AS TOTAL_CUST_SECURITY_DEPOSIT_INITIATED
COUNT(DISTINCT CASE WHEN CDC.SECURITY_DEPOSIT_INIT_WEEK_END <= WEEK_END_DATE_1 AND CDC.STATUS IS NOT NULL AND CDC.FBBID IS NOT NULL THEN  DACD.FBBID END) AS TOT_CUST_SECURITY_DEPOSIT_INITIATED,

COUNT(DISTINCT CASE WHEN WEEK_END_DATE_1 >= CDC.SECURITY_DEPOSIT_WEEK_END and CDC.STATUS IN ('APPROVED') AND DACD.CREDIT_LIMIT>0 AND DACD.FIRST_APPROVED_TIME IS NOT NULL THEN  DACD.FBBID END) AS TOT_CUST_SECURITY_DEPOSIT_CONFIRMED,
COUNT(DISTINCT CASE WHEN CDC.STATUS IN ('APPROVED') AND (DACD.CREDIT_LIMIT<=0 OR DACD.CREDIT_STATUS = 'disabled' OR DACD.account_status = 'suspended' OR DACD.CREDIT_LIMIT IS NULL OR DACD.FIRST_APPROVED_TIME IS NULL) THEN  DACD.FBBID END) AS TOT_CUST_SECURITY_DEPOSIT_CONFIRMED_DIS,

SUM(CASE WHEN CDC.STATUS IN ('IN_PROGRESS','SCHEDULED') THEN  CDC.AMOUNT_IN_CENTS/100 END) AS TOT_SECURITY_DEPOSIT_INITIATED,
SUM(CASE WHEN CDC.STATUS IN ('APPROVED') AND DACD.CREDIT_LIMIT>0 AND DACD.FIRST_APPROVED_TIME IS NOT NULL  THEN  CDC.AMOUNT_IN_CENTS/100 END) AS TOT_SECURITY_DEPOSIT_CONFIRMED,


COUNT(DISTINCT CASE WHEN DACD.FIRST_DRAW_DATE IS NOT NULL and WEEK_END_DATE_1 >= DACD.FIRST_DRAW_WEEK_END THEN DACD.FBBID ELSE NULL END) AS TOTAL_FTDS,

SUM(CASE WHEN DACD.FIRST_DRAW_DATE IS NOT NULL THEN DACD.FIRST_DRAW_AMOUNT END ) AS TOTAL_FIRST_TIME_DRAW_AMOUNT,

COUNT(DISTINCT CASE WHEN DACD.IS_CHARGEOFF = 1 THEN DACD.FBBID ELSE NULL END) TOTAL_CHARGEOFFS,

COUNT(DISTINCT CASE WHEN DPD_DAYS >0 AND DACD.IS_CHARGEOFF = 0 THEN DACD.FBBID ELSE NULL END) TOTAL_DPDS,
COUNT(DISTINCT CASE WHEN DPD_DAYS >0 AND DPD_DAYS <=7 THEN DACD.FBBID ELSE NULL END) TOTAL_DPDS_0_1,
COUNT(DISTINCT CASE WHEN DPD_DAYS >7 AND DPD_DAYS <=14 THEN DACD.FBBID ELSE NULL END) TOTAL_DPDS_1_2,
COUNT(DISTINCT CASE WHEN DPD_DAYS >14 AND DPD_DAYS <=21 THEN DACD.FBBID ELSE NULL END) TOTAL_DPDS_2_3,
COUNT(DISTINCT CASE WHEN DPD_DAYS >21 AND DPD_DAYS <=28 THEN DACD.FBBID ELSE NULL END) TOTAL_DPDS_3_4,
COUNT(DISTINCT CASE WHEN DPD_DAYS >28 AND DPD_DAYS <=35 AND DACD.IS_CHARGEOFF = 0 THEN DACD.FBBID ELSE NULL END) TOTAL_DPDS_4_5,


FROM
CREDIT_BUILDER_CUSTOMERS_DATA_WEEKLY DACD

LEFT JOIN 
(
(SELECT * FROM security_payments_txn) CDC
)
ON DACD.FBBID = CDC.FBBID

GROUP BY 1,2,3,4,5,6,7
),

CREDIT_BUILDER_HORIZONTAL_HELPER AS (
SELECT FBBID,MAX(WEEK_END) AS MAX_WKN_DATE
FROM
CREDIT_BUILDER_CUSTOMERS_DATA_DAILY
GROUP BY 1
),

CREDIT_BUILDER_CUSTOMERS_DATA_AGG_HOR AS (
SELECT 
DACD.FIRST_OFFERED_WEEK_END AS WEEK_END_DATE_1,
COALESCE(DACD.STATE_CA_GA,'NO') AS STATE_GROUP_1,
COALESCE(DACD.REVENUE_BUCKET,'No Bucket')  AS REVENUE_BUCKET_1,
COALESCE(DACD.FICO_BUCKET,'No Bucket')  AS FICO_BUCKET_1,
COALESCE(DACD.OB_RISK_BUCKET,'No Bucket')  AS RISK_BUCKET_1,
COALESCE(DACD.UTIL_BUCKET,'No Bucket') AS UTIL_BUCKET_1,
COALESCE(DACD.YEARS_IN_BUSINESS,'0') AS YEARS_IN_BUSINESS_1,

COUNT(DISTINCT CASE WHEN DATEDIFF(DAY,DACD.FIRST_OFFERED_WEEK_END,DACD.FIRST_APPROVED_WEEK_END)<7 THEN DACD.FBBID END) AS TOTAL_ACCEPTED_7_DAY,

COUNT(DISTINCT CASE WHEN  DATEDIFF(DAY,DACD.FIRST_OFFERED_WEEK_END,DACD.FIRST_APPROVED_WEEK_END)<15 THEN DACD.FBBID END) AS TOTAL_ACCEPTED_15_DAY,

COUNT(DISTINCT CASE WHEN  DATEDIFF(DAY,DACD.FIRST_OFFERED_WEEK_END,DACD.FIRST_APPROVED_WEEK_END)<30 THEN DACD.FBBID END) AS TOTAL_ACCEPTED_30_DAY,

-----------------------------NEW ADDITIONS-------------------------------------------------
COUNT(DISTINCT CASE WHEN DACD.FIRST_DRAW_DATE IS NOT NULL THEN DACD.FBBID END) FTD_HORIZONTAL,
COUNT(DISTINCT CASE WHEN DACD.ABLE_TO_DRAW IS NOT NULL THEN DACD.FBBID END) ABLE_TO_DRAW_HORIZONTAL,
COUNT(DISTINCT CASE WHEN CDC.FBBID IS NOT NULL THEN DACD.FBBID END) SECURITY_DEPOSIT_INITIATED_HORIZONTAL,
COUNT(DISTINCT CASE WHEN CDC.FBBID IS NOT NULL  AND CDC.STATUS IN ('APPROVED') THEN DACD.FBBID END) SECURITY_DEPOSIT_CONFIRMED_HORIZONTAL,
COUNT(DISTINCT CASE WHEN DACD.FIRST_APPROVED_WEEK_END IS NOT NULL THEN DACD.FBBID END) ACCEPTED_THIS_WEEK_HORIZONTAL,
-------------------------------------------------------------------------------------------

COUNT(DISTINCT CASE WHEN DACD.FIRST_DRAW_DATE IS NOT NULL AND DACD.ABLE_TO_DRAW IS NOT NULL AND DATEDIFF(DAY,DACD.FIRST_APPROVED_WEEK_END,DACD.FIRST_DRAW_WEEK_END)<7 THEN DACD.FBBID END) AS FIRST_TIME_DRAW_7_DAY,
COUNT(DISTINCT CASE WHEN DACD.FIRST_DRAW_DATE IS NOT NULL AND DACD.ABLE_TO_DRAW IS NOT NULL AND DATEDIFF(DAY,DACD.FIRST_APPROVED_WEEK_END,DACD.FIRST_DRAW_WEEK_END)<15 THEN  DACD.FBBID END) AS FIRST_TIME_DRAW_15_DAY,
COUNT(DISTINCT CASE WHEN DACD.FIRST_DRAW_DATE IS NOT NULL AND DACD.ABLE_TO_DRAW IS NOT NULL AND DATEDIFF(DAY,DACD.FIRST_APPROVED_WEEK_END,DACD.FIRST_DRAW_WEEK_END)<30 THEN  DACD.FBBID END) AS FIRST_TIME_DRAW_30_DAY,


COUNT(DISTINCT CASE WHEN CDC.FBBID IS NOT NULL AND DATEDIFF(DAY,DACD.FIRST_APPROVED_WEEK_END,SECURITY_DEPOSIT_INIT_WEEK_END)<7 AND DATEDIFF(DAY,DACD.FIRST_APPROVED_WEEK_END,SECURITY_DEPOSIT_INIT_WEEK_END)>=0 THEN DACD.FBBID END) AS SECURITY_DEPOSIT_INITIATED_7_DAY,
COUNT(DISTINCT CASE WHEN CDC.FBBID IS NOT NULL AND DATEDIFF(DAY,DACD.FIRST_APPROVED_WEEK_END,SECURITY_DEPOSIT_INIT_WEEK_END)<15 AND DATEDIFF(DAY,DACD.FIRST_APPROVED_WEEK_END,SECURITY_DEPOSIT_INIT_WEEK_END)>=0 THEN  DACD.FBBID END) AS SECURITY_DEPOSIT_INITIATED_15_DAY,
COUNT(DISTINCT CASE WHEN CDC.FBBID IS NOT NULL AND DATEDIFF(DAY,DACD.FIRST_APPROVED_WEEK_END,SECURITY_DEPOSIT_INIT_WEEK_END)<30 AND DATEDIFF(DAY,DACD.FIRST_APPROVED_WEEK_END,SECURITY_DEPOSIT_INIT_WEEK_END)>=0 THEN  DACD.FBBID END) AS SECURITY_DEPOSIT_INITIATED_30_DAY,

FROM
CREDIT_BUILDER_HORIZONTAL_HELPER HEL
LEFT JOIN
CREDIT_BUILDER_CUSTOMERS_DATA_DAILY DACD
ON
HEL.FBBID = DACD.FBBID AND
HEL.MAX_WKN_DATE = DACD.WEEK_END

LEFT JOIN 
(
(SELECT * FROM security_payments_txn) CDC
)
ON DACD.FBBID = CDC.FBBID
--WHERE DACD.WEEK_END > DATEDIFF(CURRENT_DATE())
--WHERE DACD.WEEK_END > CURRENT_DATE()-7 OR DACD.WEEK_END IS NULL
GROUP BY 1,2,3,4,5,6,7),

CREDIT_BUILDER_CUSTOMERS_DATA_AGG_FINAL AS (
SELECT 
COALESCE(VERT.WEEK_END_DATE_1,HOR.WEEK_END_DATE_1) AS WEEK_END_DATE,
COALESCE(VERT.STATE_GROUP_1,HOR.STATE_GROUP_1) AS STATE_GROUP,
COALESCE(VERT.REVENUE_BUCKET_1,HOR.REVENUE_BUCKET_1)  AS REVENUE_BUCKET,
COALESCE(VERT.FICO_BUCKET_1,HOR.FICO_BUCKET_1)  AS FICO_BUCKET,
COALESCE(VERT.RISK_BUCKET_1,HOR.RISK_BUCKET_1)  AS RISK_BUCKET,
COALESCE(VERT.UTIL_BUCKET_1,HOR.UTIL_BUCKET_1) AS UTIL_BUCKET,
COALESCE(VERT.YEARS_IN_BUSINESS_1,HOR.YEARS_IN_BUSINESS_1) AS YEARS_IN_BUSINESS,
VERT.*,
HOR.TOTAL_ACCEPTED_7_DAY,
HOR.TOTAL_ACCEPTED_15_DAY,
HOR.TOTAL_ACCEPTED_30_DAY,
HOR.FTD_HORIZONTAL,
HOR.ABLE_TO_DRAW_HORIZONTAL,
HOR.SECURITY_DEPOSIT_INITIATED_HORIZONTAL,
HOR.SECURITY_DEPOSIT_CONFIRMED_HORIZONTAL,
HOR.FIRST_TIME_DRAW_7_DAY,
HOR.FIRST_TIME_DRAW_15_DAY,
HOR.FIRST_TIME_DRAW_30_DAY,
HOR.SECURITY_DEPOSIT_INITIATED_7_DAY,
HOR.SECURITY_DEPOSIT_INITIATED_15_DAY,
HOR.SECURITY_DEPOSIT_INITIATED_30_DAY,
HOR.ACCEPTED_THIS_WEEK_HORIZONTAL,
FROM
CREDIT_BUILDER_CUSTOMERS_DATA_AGG VERT
FULL JOIN
CREDIT_BUILDER_CUSTOMERS_DATA_AGG_HOR HOR
ON
VERT.WEEK_END_DATE_1 = HOR.WEEK_END_DATE_1
AND VERT.STATE_GROUP_1 = HOR.STATE_GROUP_1
AND VERT.REVENUE_BUCKET_1 = HOR.REVENUE_BUCKET_1
AND VERT.FICO_BUCKET_1 = HOR.FICO_BUCKET_1
AND VERT.RISK_BUCKET_1 = HOR.RISK_BUCKET_1
AND VERT.UTIL_BUCKET_1 = HOR.UTIL_BUCKET_1
AND VERT.YEARS_IN_BUSINESS_1 = HOR.YEARS_IN_BUSINESS_1
)

SELECT * FROM CREDIT_BUILDER_CUSTOMERS_DATA_AGG_FINAL
);