create or replace view INDUS.PUBLIC.LOAN_DATA_INDUS_DAILY_NEW(
	LOAN_KEY,
	FBBID,
	LOAN_CREATED_DATE,
	LOAN_CREDITED_DATE,
	LOAN_OPERATIONAL_STATUS,
	ORIGINATED_AMOUNT,
	FIRST_PLANNED_TRANSMISSION_DATE,
	FIRST_GOOD_DEBIT_PAYMENT_DATE,
	EDATE,
	OUTSTANDING_PRINCIPAL_DUE,
	OUTSTANDING_PRINCIPAL_FUNDED,
	DPD_DAYS,
	CHARGEOFF_PRINCIPAL,
	CREDITED_AMOUNT,
	IS_CHARGED_OFF,
	RNK
) as 
(SELECT * 
FROM 
(SELECT 
loan_key,
fbbid ,
LOAN_CREATED_DATE,
LOAN_CREDITED_DATE,
LOAN_OPERATIONAL_STATUS,
ORIGINATED_AMOUNT,
FIRST_PLANNED_TRANSMISSION_DATE,
FIRST_GOOD_DEBIT_PAYMENT_DATE ,
edate ,
OUTSTANDING_PRINCIPAL_DUE, 
OUTSTANDING_PRINCIPAL_FUNDED, 
CASE 
	WHEN is_charged_off = 1 AND DPD_days IS NULL THEN 98
	WHEN is_charged_off = 0 AND DPD_days IS NULL THEN 0 
	ELSE dpd_days 
END
DPD_DAYS,
CHARGEOFF_PRINCIPAL,
CREDITED_AMOUNT ,
IS_CHARGED_OFF,
ROW_NUMBER () over( PARTITION BY loan_key ORDER BY edate DESC ) rnk 
FROM (
SELECT * FROM BI.FINANCE.FINANCE_METRICS_DAILY 
WHERE PRODUCT_TYPE <> 'Flexpay' ))
WHERE rnk = 1 
AND edate >= DATEADD(MONTH, -2, CURRENT_DATE)
) ;