CREATE OR REPLACE VIEW ANALYTICS.CREDIT.OG_MODEL_SCORES_RETROSCORED_V2_2 AS
WITH OG_MODEL_SCORES AS (
SELECT IDENTIFIER_ID
, SCORE
, CASE 
    WHEN SCORE >= 0 AND SCORE < 0.016 THEN 1
    WHEN SCORE >= 0.016 AND SCORE < 0.019 THEN 2
    WHEN SCORE >= 0.019 AND SCORE < 0.025 THEN 3
    WHEN SCORE >= 0.025 AND SCORE < 0.030 THEN 4
    WHEN SCORE >= 0.030 AND SCORE < 0.036 THEN 5
    WHEN SCORE >= 0.036 AND SCORE < 0.043 THEN 6
    WHEN SCORE >= 0.043 AND SCORE < 0.052 THEN 7
    WHEN SCORE >= 0.052 AND SCORE < 0.063 THEN 8
    WHEN SCORE >= 0.063 AND SCORE < 0.080 THEN 9
    WHEN SCORE >= 0.080 AND SCORE < 0.110 THEN 10
    WHEN SCORE >= 0.110 AND SCORE < 0.122 THEN 11
    WHEN SCORE >= 0.122 AND SCORE < 0.135 THEN 12
    WHEN SCORE >= 0.135 AND SCORE < 0.156 THEN 13
    WHEN SCORE >= 0.156 AND SCORE < 0.195 THEN 14
    WHEN SCORE >= 0.195 AND SCORE < 1.00 THEN 15
  END AS MODEL_BUCKET
, CUTOFF_TIME
, CONFIDENCE
, LEFT(TO_DATE(CUTOFF_TIME), 10) AS CUTOFF_DATE
, LEFT(TO_DATE(CUTOFF_TIME), 7) AS CUTOFF_MONTH
, ROW_NUMBER() OVER (PARTITION BY IDENTIFIER_ID, CUTOFF_DATE ORDER BY CUTOFF_TIME DESC) AS ROW_NUM
FROM DATA_SCIENCE.RISK_MONTHLY_PERIODIC_ONGOING_SIMULATION.MODEL_SCORES
WHERE MODEL_NAME = 'UnifiedOngoingMLEModelV2.2' AND LEFT(CUTOFF_MONTH, 4) >= 2020 AND score IS NOT NULL 
QUALIFY ROW_NUM = 1
)
SELECT FBBID
, EDATE
, SCORE AS OG_SCORE
, MODEL_BUCKET AS OG_BUCKET
, CUTOFF_DATE
, ROW_NUMBER()OVER(PARTITION BY FBBID, EDATE ORDER BY CUTOFF_DATE DESC) AS ROW_NUM_SCORE
FROM BI.PUBLIC.DAILY_APPROVED_CUSTOMERS_DATA AS A1
LEFT JOIN OG_MODEL_SCORES AS A2 ON A1.FBBID = A2.IDENTIFIER_ID AND A1.EDATE >= A2.CUTOFF_DATE
WHERE EDATE >= '2020-01-01'
QUALIFY ROW_NUM_SCORE = 1;