------------------------------------PURPOSE OF THE TABLE: CREATING A MODIFIED FMD TABLE WITH THE EXCUSION OF CANCELLED LOANS, ADDITION OF CALCULATED FIELD, SINCE THESE LOANS ARE NOT REQUIRED TO BE MONITORED------------------------------------------
------------------------------------------------------------------------------------------THE BELOW TABLE WILL BE USED WHENEVER FINANCE METRICS DAILY IS REQUIRED---------------------------------------------------------------------------------------

CREATE OR REPLACE TABLE ANALYTICS.CREDIT.FINANCE_METRICS_DAILY_UPDATED AS
SELECT A1.*
, TO_DATE(LOAN_CREDITED_DATE::STRING) as LCD
, CASE
    WHEN LOAN_CREATED_DATE = CURRENT_DATE() AND DAYOFWEEK(LOAN_CREATED_DATE) <> 3 THEN NULL
    WHEN DATEDIFF(DAY, LOAN_CREATED_DATE, DATE_TRUNC('WEEK',CURRENT_DATE()+4)::DATE-5) < 0 THEN CURRENT_DATE()-1
    ELSE DATE_TRUNC('WEEK', LOAN_CREATED_DATE::DATE+4)::DATE + 2
END AS LOAN_CREATED_WEEK_END
, CASE
    WHEN EDATE = CURRENT_DATE() AND DAYOFWEEK(EDATE) <> 3 THEN NULL
    WHEN DATEDIFF(DAY, EDATE, DATE_TRUNC('WEEK',CURRENT_DATE()+4)::DATE-5) < 0 THEN CURRENT_DATE()-1
    ELSE DATE_TRUNC('WEEK', EDATE::DATE+4)::DATE + 2
END AS FMD_WEEK_END
, CASE 
	WHEN DPD_DAYS IS NULL AND IS_CHARGED_OFF = 0 THEN 0
	WHEN DPD_DAYS IS NULL AND IS_CHARGED_OFF = 1 THEN 98
	ELSE DPD_DAYS
END AS DPD_DAYS_CORRECTED
, MAX(EDATE)OVER(PARTITION BY A1.FBBID, LOAN_KEY ORDER BY EDATE DESC) AS MAX_EDATE
FROM (
SELECT * FROM BI.FINANCE.FINANCE_METRICS_DAILY 
WHERE PRODUCT_TYPE <> 'Flexpay' 
AND (loan_operational_status <> 'CNCL' OR loan_operational_status IS NULL) AND LOAN_CREATED_DATE >= '2024-01-01') AS A1
;

--select * from ANALYTICS.CREDIT.FINANCE_METRICS_DAILY_UPDATED where fmd_week_end = '2025-01-22';

------------------------------------PURPOSE OF THE TABLE: CREATING A MODIFIED DAILY APPROVED CUSTOMERS DATA WITH CALCULATED FIELDS------------------------------------------
------------------------------------------------------------------------------------------THE BELOW TABLE WILL BE USED WHENEVER DAILY APPROVED CUSTOMERS DATA IS REQUIRED------------------------------------------------------------------------
CREATE OR REPLACE TABLE ANALYTICS.CREDIT.DAILY_APPROVED_CUSTOMERS_DATA_UPDATED AS
SELECT A1.*
, DATE_TRUNC('WEEK', A1.EDATE::DATE+4)::DATE-4 AS WEEK_START
, CASE
    WHEN A1.EDATE = CURRENT_DATE() AND DAYOFWEEK(A1.EDATE) <> 3 THEN NULL
    WHEN DATEDIFF(DAY, A1.EDATE, DATE_TRUNC('WEEK',CURRENT_DATE()+4)::DATE-5) < 0 THEN CURRENT_DATE()-1
    ELSE DATE_TRUNC('WEEK', A1.EDATE::DATE+4)::DATE + 2
END AS WEEK_END
, CREDIT_LIMIT - OUTSTANDING_PRINCIPAL AS OPEN_TO_BUY
, CREDIT_SCORE_JSON:"VantageScore 4.0"."score" AS VANTAGE4
, A2.CHANNEL
, A2.PARTNER
, A2.NEW_CUST_FILTER
, A2.OB_BUCKET_GROUP_DAL
, A2.OG_BUCKET_GROUP
, CASE 
	WHEN DPD_DAYS IS NULL AND A1.IS_CHARGEOFF = 0 THEN 0
	WHEN DPD_DAYS IS NULL AND A1.IS_CHARGEOFF = 1 THEN 98
	ELSE DPD_DAYS
END AS DPD_DAYS_CORRECTED
, CASE 
	WHEN DPD_DAYS_CORRECTED BETWEEN 1 AND 7 THEN 'DPD 1-7' 
	WHEN DPD_DAYS_CORRECTED BETWEEN 8 AND 14 THEN 'DPD 8-14'
	WHEN DPD_DAYS_CORRECTED BETWEEN 15 AND 35 THEN 'DPD 15-35'
	WHEN DPD_DAYS_CORRECTED BETWEEN 36 AND 63 THEN 'DPD 36-63'
	WHEN DPD_DAYS_CORRECTED BETWEEN 64 AND 97 THEN 'DPD 64-90'
END DPD_GROUP
, DATEDIFF(MONTH, A1.FIRST_APPROVED_TIME, A1.EDATE) AS AGE_OF_ACCOUNT
, GREATEST(IFNULL(FIRST_ACCOUNT_SIZE_ACCOUNTING_SOFTWARE,0), IFNULL(FIRST_ACCOUNT_SIZE_FI,0)) * 12 ANNUAL_REVENUE
, MAX(DPD_DAYS_CORRECTED) OVER (PARTITION BY A1.FBBID ORDER BY A1.EDATE DESC ROWS BETWEEN 30 PRECEDING AND CURRENT ROW) AS DPD_LAST30DAYS
FROM BI.PUBLIC.DAILY_APPROVED_CUSTOMERS_DATA AS A1
LEFT JOIN INDUS.PUBLIC.INDUS_KEY_METRICS_FILTERS AS A2 ON A1.FBBID = A2.FBBID AND A1.EDATE = A2.EDATE
LEFT JOIN BI.PUBLIC.CUSTOMERS_DATA AS A3 ON A1.FBBID = A3.FBBID
WHERE A1.EDATE >= '2024-04-15' AND UPPER(A1.SUB_PRODUCT) = 'LINE OF CREDIT' AND IS_TEST_USER = 0;

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------RMR MONITORING CODE----------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-------------------------------------------------------------------TABLE 1
---------------------------USE OF THE TABLE IS: LIST OF FBBIDs WHICH WENT BANKRUPT AND HENCE RMR EXPANSION ISN'T CONCERENED WITH THESE CUSTOMERS---------------------------------
-----------------------------------------CREATING BANKRUPTCY TABLE BY COMBINING ALL THE FBBIDs WHICH HAVE BEEN FLAGGED AS BANKRUPTCY FROM MULTIPLE SOURCE--------------------
CREATE OR REPLACE TABLE ANALYTICS.CREDIT.RMR_MONITORING_BANKRUPTCY_DATA AS
SELECT FBBID 
FROM CDC_V2.RECOVERY.BANKRUPTCY_BUSINESS
UNION
SELECT FBBID 
FROM CDC_V2.FEATURE_FLAGS.TAGS_FUNDBOX_BUSINESSES
WHERE TAG_CATEGORY_ID = 28
UNION
SELECT FBBID 
FROM (
    SELECT 
        TO_NUMBER(FUNDBOX_ID__C) AS FBBID, 
        MAX(CASE WHEN BANKRUPTCY_STATUS__C = 'Active - Credit Review' THEN 1 ELSE 0 END) AS BK_FLAG_SALESFORCE
    FROM EXTERNAL_DATA_SOURCES.SALESFORCE_NOVA.BANKRUPTCY__C
    GROUP BY FBBID
) 
WHERE BK_FLAG_SALESFORCE = 1;

-------------------------------------------------------------------TABLE 2
-----------------------------------------------USE OF THE TABLE IS: LABELING THE RMR MARGINAL ENTER AND EXIT DATE---------------------------------------------------------------
-----------------------------------------CREATING TABLE UNIQUE ON FBBID X EDATE LEVEL WHICH CAPTURES THE RMR MARGINAL ENTER AND EXIT DATE--------------------
CREATE OR REPLACE TABLE ANALYTICS.CREDIT.RMR_MONITORING_LABELING_TABLE AS
WITH RMR_DATA AS (


--30th jan, adding control flow type

/*
SELECT FBBID
, TO_DATE(CREATED_TIME) AS LOCK_START
, CONVERT_TIMEZONE('UTC','America/Los_Angeles',lock_start::date)::date LOCK_START_LTZ
, IFNULL(to_date(LOCK_RELEASE_TIME),current_date()+10) AS LOCK_END
FROM CDC_V2.CREDIT.CREDIT_STATUSES_LOCKS
WHERE CREDIT_LOCK_CONTEXT ILIKE '%rmr%'*/


----30th jan, adding control flow type

SELECT b.fbbid,
IFNULL(to_date(a.CREATED_TIME),b.rmr_time::date) lock_start,
convert_timezone('UTC','America/Los_Angeles',lock_start::date)::date lock_start_ltz,
IFNULL(to_date(a.LOCK_RELEASE_TIME),current_date()+10) lock_end ,
from
(
SELECT DATA:tag_option::varchar flow_Type,
DATA:segment::varchar rmr_segment,
DATA:event_type::varchar event_type,
DATA:fbbid AS fbbid,
DATA:event_time::timestamp rmr_time,
convert_timezone('UTC','America/Los_Angeles',DATA:event_time::date)::date rmr_time_ltz,
DATA:comment::varchar AS comment
FROM CDC_V2.RISK_HIST.EVENTS_OUTBOX eo
WHERE DATA:entity_type = 'RMR_FLOW'
AND DATA:event_type = 'RiskEnterRMREvent'
qualify row_number() over(partition by fbbid order BY rmr_time  desc) = 1
) b
LEFT join
(SELECT fbbid,
CREATED_TIME,
--convert_timezone('UTC','America/Los_Angeles',lock_start::date)::date lock_start_ltz,
IFNULL(to_date(LOCK_RELEASE_TIME),current_date()+10) LOCK_RELEASE_TIME
FROM indus."PUBLIC".credit_statuses_locks
WHERE credit_lock_context ILIKE '%rmr%'
)a
ON a.fbbid = b.fbbid



)
SELECT A1.WEEK_END
, A1.EDATE
, A1.FBBID
, A1.OPEN_TO_BUY
, CASE
    WHEN A3.FBBID IS NOT NULL AND A3.LOCK_START_LTZ <= A1.WEEK_END AND (A3.LOCK_END IS NULL OR A3.LOCK_END > A1.WEEK_END) THEN 1
    ELSE 0
END AS IS_RMR
, A1.CHANNEL
, A1.PARTNER
, A1.NEW_CUST_FILTER
, A1.VANTAGE4
, A1.RISK_CREDIT_REVIEW_ALIGNED_BUCKET AS OG_RISK_BUCKET
, A1.RISK_CREDIT_REVIEW_MODEL_SCORE AS OG_SCORE
, ANNUAL_REVENUE
, A1.FIRST_APPROVED_TIME::DATE AS FIRST_APPROVED_DATE
, A3.LOCK_START_LTZ
, A3.LOCK_END
--------------------------------------------------------RMR MARGINAL POLICY--------------------------------------------------------
, CASE
	WHEN IS_RMR = 1 THEN 'RMR SEGMENT'
	WHEN DPD_DAYS_CORRECTED > 0 OR IS_IN_BREATHER = 1 OR PAYOFF_STATUS = 'ACT' OR PAYOFF_STATUS = 'FUND' OR OPEN_TO_BUY <=1000 
    OR A2.FBBID IS NOT NULL OR (UPPER(A1.ACCOUNT_STATUS) = 'SUSPENDED' AND UPPER(ACCOUNT_STATUS_REASON) IN ('INACTIVE FLOW'))
	OR A3.LOCK_START_LTZ IS NOT NULL THEN 'NO RMR SEGMENT'
	WHEN 
    (A1.CHANNEL = 'Direct' AND A1.PARTNER = 'Direct' AND OG_RISK_BUCKET >= 11 AND OG_RISK_BUCKET <=12 
    AND DATEDIFF(DAY, FIRST_APPROVED_DATE, A1.EDATE) >= 60 AND ANNUAL_REVENUE > 150000)
	OR 
	(A1.CHANNEL = 'Direct' AND A1.PARTNER = 'Direct' AND OG_SCORE > 0.096 AND OG_RISK_BUCKET <= 12
	AND DATEDIFF(DAY, FIRST_APPROVED_DATE, A1.EDATE) >= 90 AND ANNUAL_REVENUE > 150000) 
	OR 
	(A1.CHANNEL = 'Direct' AND A1.PARTNER = 'Direct' AND OG_RISK_BUCKET >= 9 AND OG_RISK_BUCKET <=10
	AND DATEDIFF(DAY, FIRST_APPROVED_DATE, A1.EDATE)>=90 AND ANNUAL_REVENUE > 150000 AND (A1.VANTAGE4 < 610 OR A1.DPD_LAST30DAYS > 0))
	OR
	(A1.PARTNER <> 'Intuit' AND OG_RISK_BUCKET >= 11 AND OG_RISK_BUCKET <= 12 
	AND DATEDIFF(DAY, FIRST_APPROVED_DATE, A1.EDATE)>=60  AND  ANNUAL_REVENUE > 150000) 
	OR 
	(A1.PARTNER <> 'Intuit' AND OG_SCORE > 0.096 AND OG_RISK_BUCKET <= 12
	AND DATEDIFF(DAY, FIRST_APPROVED_DATE, A1.EDATE) >= 90 AND ANNUAL_REVENUE > 150000) 
	OR 
	(A1.PARTNER <> 'Intuit' AND OG_RISK_BUCKET >= 10 AND OG_RISK_BUCKET <=11 AND (A1.VANTAGE4 < 610 OR A1.DPD_LAST30DAYS > 0)
	AND DATEDIFF(DAY, FIRST_APPROVED_DATE, A1.EDATE) >= 90 AND ANNUAL_REVENUE > 150000)
	OR
	(A1.PARTNER = 'Intuit' AND OG_RISK_BUCKET >= 11 AND OG_RISK_BUCKET <=12
	AND DATEDIFF(DAY, FIRST_APPROVED_DATE, A1.EDATE) >= 60)
	OR
	(A1.PARTNER = 'Intuit' AND OG_SCORE > 0.096 AND OG_RISK_BUCKET <= 12
	AND DATEDIFF(DAY, FIRST_APPROVED_DATE, A1.EDATE) >= 90)
	OR 
	(A1.PARTNER = 'Intuit' AND OG_RISK_BUCKET >= 9 AND OG_RISK_BUCKET <=10 AND (A1.VANTAGE4 < 610 OR A1.DPD_LAST30DAYS > 0)
	AND DATEDIFF(DAY, FIRST_APPROVED_DATE, A1.EDATE) >= 90) THEN 'MARGINAL SEGMENT'
	ELSE 'NO RMR SEGMENT'
END POPULATION_SEGMENT
, CASE
    WHEN UPPER(A1.ACCOUNT_STATUS) = 'SUSPENDED' THEN 1
    ELSE 0
END AS IS_SUSPENDED_ACCOUNT
, CASE WHEN POPULATION_SEGMENT = 'MARGINAL SEGMENT' AND IS_SUSPENDED_ACCOUNT = 0 THEN A1.EDATE END AS MARGINAL_POP_SEGMENT_DATE
, CASE WHEN POPULATION_SEGMENT = 'RMR SEGMENT' THEN A3.LOCK_START_LTZ END AS RMR_POP_SEGMENT_DATE
, CASE
    WHEN UPPER(A1.NEW_CUST_FILTER) = 'NEW CUSTOMER' THEN A1.OB_BUCKET_GROUP_DAL
    WHEN UPPER(A1.NEW_CUST_FILTER) = 'EXISTING CUSTOMER' THEN A1.OG_BUCKET_GROUP
END AS BUCKET_GROUP
, CASE WHEN IS_SUSPENDED_ACCOUNT = 1 THEN EDATE ELSE NULL END AS SUSPENDED_ACCOUNT_DATE
, A1.AGE_OF_ACCOUNT
FROM ANALYTICS.CREDIT.DAILY_APPROVED_CUSTOMERS_DATA_UPDATED AS A1
LEFT JOIN ANALYTICS.CREDIT.RMR_MONITORING_BANKRUPTCY_DATA AS A2 ON A1.FBBID = A2.FBBID
LEFT JOIN RMR_DATA AS A3 ON A1.FBBID = A3.FBBID AND A1.WEEK_END >= A3.LOCK_START_LTZ
WHERE A1.IS_CHARGEOFF = 0 AND A1.DPD_DAYS_CORRECTED < 98;

-------------------------------------------------------------------TABLE 3
--------------------------------USE OF THE TABLE IS: TAGGING THE OLDEST RMR MARGINAL ENTER DATE AND RECENT RMR DATE------------------------------------------------
-----------------------------------------CREATING TABLE UNIQUE ON FBBID X EDATE LEVEL WHICH CAPTURES THE RMR MARGINAL ENTER AND RMR DATE-------------------------------------
CREATE OR REPLACE TABLE ANALYTICS.CREDIT.RMR_MARGINAL_SEGMENT_TIME AS
SELECT *
, MIN(MARGINAL_POP_SEGMENT_DATE)OVER(PARTITION BY FBBID ORDER BY EDATE ASC) AS MARGINAL_POP_SEGMENT_START_DATE
, MAX(RMR_POP_SEGMENT_DATE)OVER(PARTITION BY FBBID ORDER BY EDATE ASC) AS RMR_POP_SEGMENT_START_DATE
, MIN(SUSPENDED_ACCOUNT_DATE)OVER(PARTITION BY FBBID ORDER BY EDATE ASC) AS ACCOUNT_SUSPENDED_START_DATE
, CASE
    WHEN RMR_POP_SEGMENT_START_DATE = CURRENT_DATE() AND DAYOFWEEK(RMR_POP_SEGMENT_START_DATE) <> 3 THEN NULL
    WHEN DATEDIFF(DAY, RMR_POP_SEGMENT_START_DATE, DATE_TRUNC(WEEK, CURRENT_DATE()+4)::DATE - 5) < 0 THEN CURRENT_DATE()-1
    ELSE DATE_TRUNC(WEEK, RMR_POP_SEGMENT_START_DATE::DATE + 4)::DATE+2
END AS RMR_POP_SEGMENT_START_WEEK_END
, CASE
    WHEN MARGINAL_POP_SEGMENT_START_DATE = CURRENT_DATE() AND DAYOFWEEK(MARGINAL_POP_SEGMENT_START_DATE) <> 3 THEN NULL
    WHEN DATEDIFF(DAY, MARGINAL_POP_SEGMENT_START_DATE, DATE_TRUNC(WEEK, CURRENT_DATE()+4)::DATE - 5) < 0 THEN CURRENT_DATE()-1
    ELSE DATE_TRUNC(WEEK, MARGINAL_POP_SEGMENT_START_DATE::DATE + 4)::DATE+2
END AS MARGINAL_POP_SEGMENT_START_WEEK_END
, CASE
    WHEN IS_RMR = 1 OR DATEDIFF(DAY, RMR_POP_SEGMENT_START_DATE, WEEK_END) BETWEEN 0 AND 90 THEN 'RMR SEGMENT'
    WHEN MARGINAL_POP_SEGMENT_START_DATE <= '2024-05-29' THEN 'NO RMR SEGMENT'
    WHEN DATEDIFF(DAY, MARGINAL_POP_SEGMENT_START_DATE, WEEK_END) BETWEEN 0 AND 90 AND IS_SUSPENDED_ACCOUNT = 0 THEN 'MARGINAL SEGMENT'
    ELSE 'NO RMR SEGMENT'
END AS FINAL_SEGMENT
, ROW_NUMBER()OVER(PARTITION BY FBBID, EDATE ORDER BY LOCK_START_LTZ DESC) AS DACD_ROW_NUM
FROM ANALYTICS.CREDIT.RMR_MONITORING_LABELING_TABLE
QUALIFY DACD_ROW_NUM = 1;

-------------------------------------------------------------------TABLE 4
--------------------------------USE OF THE TABLE IS: ORIGINATIONS AND $DPD IN RMR MARGINAL SEGMENT ARE CALCULATED FROM HERE------------------------------------------------
-----------------------------------------CREATING TABLE UNIQUE ON FBBID X EDATE LEVEL WHICH CAPTURES THE RMR MARGINAL ENTER AND RMR DATE-------------------------------------
CREATE OR REPLACE TABLE ANALYTICS.CREDIT.MARGINAL_SEGMENT_METRICS AS
WITH ORIGINATED_DATA AS (
SELECT DISTINCT FBBID
, LOAN_KEY
, LOAN_CREATED_DATE
, LOAN_CREATED_WEEK_END
, ORIGINATED_AMOUNT
FROM ANALYTICS.CREDIT.FINANCE_METRICS_DAILY_UPDATED
WHERE EDATE = loan_created_date
),
LOAN_DATA_WITH_SEGMENTS AS (
SELECT A1.WEEK_END
, A1.FBBID
, A1.EDATE
, A1.FINAL_SEGMENT
, A1.IS_SUSPENDED_ACCOUNT
, A1.MARGINAL_POP_SEGMENT_START_DATE
, A1.MARGINAL_POP_SEGMENT_START_WEEK_END
, A1.RMR_POP_SEGMENT_START_DATE
, A1.RMR_POP_SEGMENT_START_WEEK_END
, A1.AGE_OF_ACCOUNT
, A2.LOAN_KEY
, A2.ORIGINATED_AMOUNT
FROM ANALYTICS.CREDIT.RMR_MARGINAL_SEGMENT_TIME AS A1
LEFT JOIN ORIGINATED_DATA AS A2
ON A1.FBBID = A2.FBBID AND A1.EDATE = A2.LOAN_CREATED_DATE
AND A1.FINAL_SEGMENT = 'MARGINAL SEGMENT' AND DATEDIFF(DAY, MARGINAL_POP_SEGMENT_START_DATE, A2.LOAN_CREATED_DATE) BETWEEN 0 AND 90 AND MARGINAL_POP_SEGMENT_START_DATE > '2024-05-29'
),
-------------------------------------AGGREGATED MARGINAL SEGMENT METRICS----------------------------------------
----------------------------------------------------------------------------------------------------------------
STOCK_VIEW AS (
SELECT WEEK_END
, COUNT(DISTINCT CASE WHEN FINAL_SEGMENT = 'MARGINAL SEGMENT' AND MARGINAL_POP_SEGMENT_START_DATE > '2024-05-29' AND IS_SUSPENDED_ACCOUNT = 0 THEN FBBID ELSE NULL END) AS NUMBER_OF_MARGINAL_CUSTOMERS
, COUNT(DISTINCT CASE WHEN FINAL_SEGMENT = 'RMR SEGMENT' AND MARGINAL_POP_SEGMENT_START_DATE > '2024-05-29' THEN FBBID ELSE NULL END) AS NUMBER_OF_RMR_CUSTOMERS
, COUNT(DISTINCT CASE WHEN IS_SUSPENDED_ACCOUNT = 1 AND MARGINAL_POP_SEGMENT_START_DATE > '2024-05-29' THEN FBBID ELSE NULL END) AS NUMBER_OF_SUSPENDED_CUSTOMERS
FROM LOAN_DATA_WITH_SEGMENTS
GROUP BY 1
),
MARGINAL_ENTER_CUSTOMERS AS (
SELECT MARGINAL_POP_SEGMENT_START_WEEK_END
, COUNT(DISTINCT FBBID) AS NUM_MARGINAL_ENTER_ACCOUNTS_THIS_WEEK
FROM LOAN_DATA_WITH_SEGMENTS
WHERE MARGINAL_POP_SEGMENT_START_DATE > '2024-05-29'
GROUP BY 1
),
RMR_ENTER_CUSTOMERS AS (
SELECT RMR_POP_SEGMENT_START_WEEK_END
, COUNT(DISTINCT FBBID) AS NUM_RMR_ENTER_ACCOUNTS_THIS_WEEK
FROM LOAN_DATA_WITH_SEGMENTS
GROUP BY 1
),
MARGINAL_ORIGINATIONS AS (
SELECT WEEK_END
, SUM(ORIGINATED_AMOUNT) AS MARGINAL_ORIGINATIONS_THIS_WEEK
, COUNT(DISTINCT LOAN_KEY) AS MARGINAL_DRAWS_THIS_WEEK
FROM LOAN_DATA_WITH_SEGMENTS
GROUP BY 1
),
MARGINAL_ORIGINATED_LOANS AS (
SELECT DISTINCT LOAN_KEY
, AGE_OF_ACCOUNT
FROM LOAN_DATA_WITH_SEGMENTS
),
MARGINAL_LOANS_FMD_DATA AS (
SELECT A1.LOAN_KEY
, A1.AGE_OF_ACCOUNT
, A2.FBBID
, A2.ORIGINATED_AMOUNT
, A2.FMD_WEEK_END
, A2.DPD_DAYS_CORRECTED
, A2.IS_CHARGED_OFF
, A2.OUTSTANDING_PRINCIPAL_DUE
, ROW_NUMBER()OVER(PARTITION BY A1.LOAN_KEY, FMD_WEEK_END ORDER BY EDATE DESC) AS ROW_NUM
FROM MARGINAL_ORIGINATED_LOANS AS A1
LEFT JOIN ANALYTICS.CREDIT.FINANCE_METRICS_DAILY_UPDATED AS A2 ON A1.LOAN_KEY = A2.LOAN_KEY
QUALIFY ROW_NUM = 1
),
AGGREGATED_DPD_METRICS AS (
SELECT FMD_WEEK_END
----------TOTAL DOLLAR OUSTANDING---------------
, SUM(OUTSTANDING_PRINCIPAL_DUE) AS TOTAL_OUTSTANDING
------SPLIT BY TENURE GROUPS------
, SUM(CASE WHEN AGE_OF_ACCOUNT >= 60 THEN OUTSTANDING_PRINCIPAL_DUE ELSE 0 END) AS TOTAL_OS_TENURE_5
, SUM(CASE WHEN AGE_OF_ACCOUNT BETWEEN 36 AND 59 THEN OUTSTANDING_PRINCIPAL_DUE ELSE 0 END) AS TOTAL_OS_TENURE_3_5
, SUM(CASE WHEN AGE_OF_ACCOUNT BETWEEN 12 AND 35 THEN OUTSTANDING_PRINCIPAL_DUE ELSE 0 END) AS TOTAL_OS_TENURE_1_3
, SUM(CASE WHEN AGE_OF_ACCOUNT BETWEEN 6 AND 11 THEN OUTSTANDING_PRINCIPAL_DUE ELSE 0 END) AS TOTAL_OS_TENURE_12MON
, SUM(CASE WHEN AGE_OF_ACCOUNT < 6 THEN OUTSTANDING_PRINCIPAL_DUE ELSE 0 END) AS TOTAL_OS_TENURE_6MON
----------TOTAL DOLLAR DPD OUTSTANDING-----------------
, SUM(CASE WHEN DPD_DAYS_CORRECTED > 0 AND IS_CHARGED_OFF = 0 THEN OUTSTANDING_PRINCIPAL_DUE ELSE 0 END) AS TOTAL_DPD_OUTSTANDING
, SUM(CASE WHEN DPD_DAYS_CORRECTED > 0 AND IS_CHARGED_OFF = 0 AND AGE_OF_ACCOUNT >= 60 THEN OUTSTANDING_PRINCIPAL_DUE ELSE 0 END) AS TOTAL_DPD_OS_TENURE_5
, SUM(CASE WHEN DPD_DAYS_CORRECTED > 0 AND IS_CHARGED_OFF = 0 AND AGE_OF_ACCOUNT BETWEEN 36 AND 59 THEN OUTSTANDING_PRINCIPAL_DUE ELSE 0 END) AS TOTAL_DPD_OS_TENURE_3_5
, SUM(CASE WHEN DPD_DAYS_CORRECTED > 0 AND IS_CHARGED_OFF = 0 AND AGE_OF_ACCOUNT BETWEEN 12 AND 35 THEN OUTSTANDING_PRINCIPAL_DUE ELSE 0 END) AS TOTAL_DPD_OS_TENURE_1_3
, SUM(CASE WHEN DPD_DAYS_CORRECTED > 0 AND IS_CHARGED_OFF = 0 AND AGE_OF_ACCOUNT BETWEEN 6 AND 11 THEN OUTSTANDING_PRINCIPAL_DUE ELSE 0 END) AS TOTAL_DPD_OS_TENURE_12MON
, SUM(CASE WHEN DPD_DAYS_CORRECTED > 0 AND IS_CHARGED_OFF = 0 AND AGE_OF_ACCOUNT < 6 THEN OUTSTANDING_PRINCIPAL_DUE ELSE 0 END) AS TOTAL_DPD_OS_TENURE_6MON
----------DOLLAR OUTSTANDING_BUCKET WISE---------
, SUM(CASE WHEN IS_CHARGED_OFF = 1 THEN OUTSTANDING_PRINCIPAL_DUE ELSE 0 END) AS TOTAL_MARGINAL_CHARGEOFF
, SUM(CASE WHEN DPD_DAYS_CORRECTED BETWEEN 1 AND 7 THEN OUTSTANDING_PRINCIPAL_DUE ELSE 0 END) AS TOTAL_DPD_OUSTANDING_BUCKET_1
, SUM(CASE WHEN DPD_DAYS_CORRECTED BETWEEN 8 AND 14 THEN OUTSTANDING_PRINCIPAL_DUE ELSE 0 END) AS TOTAL_DPD_OUSTANDING_BUCKET_2
, SUM(CASE WHEN DPD_DAYS_CORRECTED BETWEEN 15 AND 35 THEN OUTSTANDING_PRINCIPAL_DUE ELSE 0 END) AS TOTAL_DPD_OUSTANDING_BUCKET_3
, SUM(CASE WHEN DPD_DAYS_CORRECTED BETWEEN 36 AND 63 THEN OUTSTANDING_PRINCIPAL_DUE ELSE 0 END) AS TOTAL_DPD_OUSTANDING_BUCKET_4
, SUM(CASE WHEN DPD_DAYS_CORRECTED BETWEEN 64 AND 97 THEN OUTSTANDING_PRINCIPAL_DUE ELSE 0 END) AS TOTAL_DPD_OUSTANDING_BUCKET_5
----------NUMBER OF CUSTOMERS IN DELINQUENCY--------
, COUNT(DISTINCT CASE WHEN DPD_DAYS_CORRECTED > 0 THEN FBBID ELSE 0 END) AS NUMBER_OF_DPD_CUSTOMERS
----------NUMBER OF CUSTOMERS IN DELINQUENCY BUCKET WISE--------
, COUNT(DISTINCT CASE WHEN DPD_DAYS_CORRECTED BETWEEN 1 AND 7 THEN FBBID ELSE NULL END) AS NUMBER_DPD_OUSTANDING_BUCKET_1
, COUNT(DISTINCT CASE WHEN DPD_DAYS_CORRECTED BETWEEN 8 AND 14 THEN FBBID ELSE NULL END) AS NUMBER_DPD_OUSTANDING_BUCKET_2
, COUNT(DISTINCT CASE WHEN DPD_DAYS_CORRECTED BETWEEN 15 AND 35 THEN FBBID ELSE NULL END) AS NUMBER_DPD_OUSTANDING_BUCKET_3
, COUNT(DISTINCT CASE WHEN DPD_DAYS_CORRECTED BETWEEN 36 AND 63 THEN FBBID ELSE NULL END) AS NUMBER_DPD_OUSTANDING_BUCKET_4
, COUNT(DISTINCT CASE WHEN DPD_DAYS_CORRECTED BETWEEN 64 AND 97 THEN FBBID ELSE NULL END) AS NUMBER_DPD_OUSTANDING_BUCKET_5
FROM MARGINAL_LOANS_FMD_DATA
GROUP BY 1
),
ROLL_RATE AS (
SELECT FMD_WEEK_END
, SUM(CASE WHEN DPD_PREV_WEEK = 0 AND DPD_DAYS_CORRECTED > 0 THEN OUTSTANDING_PRINCIPAL_DUE END) AS TOTAL_OUTSTANDING_DELINQUENT_THIS_WEEK
, SUM(CASE WHEN DPD_PREV_WEEK = 0 THEN OUSTANDING_PREV_WEEK END) AS TOTAL_OUTSTANDING_NON_DELINQUENT_PREV_WEEK
, (TOTAL_OUTSTANDING_DELINQUENT_THIS_WEEK/TOTAL_OUTSTANDING_NON_DELINQUENT_PREV_WEEK) AS PERCENTAGE_DOLLAR_ROLL_RATE
---------DPD 1->2--------
, SUM(CASE WHEN DPD_PREV_WEEK BETWEEN 1 AND 7 AND DPD_DAYS_CORRECTED BETWEEN 8 AND 14 THEN OUTSTANDING_PRINCIPAL_DUE END) AS TOTAL_OUTSTANDING_BUCKET_2_THIS_WEEK
, SUM(CASE WHEN DPD_PREV_WEEK BETWEEN 1 AND 7 THEN OUSTANDING_PREV_WEEK END) AS TOTAL_OUTSTANDING_BUCKET_1_LAST_WEEK
, (TOTAL_OUTSTANDING_BUCKET_2_THIS_WEEK/TOTAL_OUTSTANDING_BUCKET_1_LAST_WEEK) AS PERCENTAGE_DOLLAR_ROLL_RATE_BUCKET_1_2
---------DPD 2->3--------
, SUM(CASE WHEN DPD_PREV_WEEK BETWEEN 8 AND 14 AND DPD_DAYS_CORRECTED BETWEEN 15 AND 35 THEN OUTSTANDING_PRINCIPAL_DUE END) AS TOTAL_OUTSTANDING_BUCKET_3_THIS_WEEK
, SUM(CASE WHEN DPD_PREV_WEEK BETWEEN 8 AND 14 THEN OUSTANDING_PREV_WEEK END) AS TOTAL_OUTSTANDING_BUCKET_2_LAST_WEEK
, (TOTAL_OUTSTANDING_BUCKET_3_THIS_WEEK/TOTAL_OUTSTANDING_BUCKET_2_LAST_WEEK) AS PERCENTAGE_DOLLAR_ROLL_RATE_BUCKET_2_3
---------DPD 3->4--------
, SUM(CASE WHEN DPD_PREV_WEEK BETWEEN 15 AND 35 AND DPD_DAYS_CORRECTED BETWEEN 36 AND 63 THEN OUTSTANDING_PRINCIPAL_DUE END) AS TOTAL_OUTSTANDING_BUCKET_4_THIS_WEEK
, SUM(CASE WHEN DPD_PREV_WEEK BETWEEN 15 AND 35 THEN OUSTANDING_PREV_WEEK END) AS TOTAL_OUTSTANDING_BUCKET_3_LAST_WEEK
, (TOTAL_OUTSTANDING_BUCKET_4_THIS_WEEK/TOTAL_OUTSTANDING_BUCKET_3_LAST_WEEK) AS PERCENTAGE_DOLLAR_ROLL_RATE_BUCKET_3_4
---------DPD 4->5--------
, SUM(CASE WHEN DPD_PREV_WEEK BETWEEN 36 AND 63 AND DPD_DAYS_CORRECTED BETWEEN 64 AND 97 THEN OUTSTANDING_PRINCIPAL_DUE END) AS TOTAL_OUTSTANDING_BUCKET_5_THIS_WEEK
, SUM(CASE WHEN DPD_PREV_WEEK BETWEEN 36 AND 63 THEN OUSTANDING_PREV_WEEK END) AS TOTAL_OUTSTANDING_BUCKET_4_LAST_WEEK
, (TOTAL_OUTSTANDING_BUCKET_5_THIS_WEEK/TOTAL_OUTSTANDING_BUCKET_4_LAST_WEEK) AS PERCENTAGE_DOLLAR_ROLL_RATE_BUCKET_4_5
---------DPD 5->6--------
, SUM(CASE WHEN DPD_PREV_WEEK BETWEEN 64 AND 97 AND DPD_DAYS_CORRECTED > 97 THEN OUTSTANDING_PRINCIPAL_DUE END) AS TOTAL_OUTSTANDING_CO_THIS_WEEK
, SUM(CASE WHEN DPD_PREV_WEEK BETWEEN 64 AND 97 THEN OUSTANDING_PREV_WEEK END) AS TOTAL_OUTSTANDING_BUCKET_5_LAST_WEEK
, (TOTAL_OUTSTANDING_CO_THIS_WEEK/TOTAL_OUTSTANDING_BUCKET_5_LAST_WEEK) AS PERCENTAGE_DOLLAR_ROLL_RATE_BUCKET_5_CO
FROM ( SELECT *
, LAG(DPD_DAYS_CORRECTED)OVER(PARTITION BY LOAN_KEY ORDER BY FMD_WEEK_END ASC) AS DPD_PREV_WEEK
, LAG(OUTSTANDING_PRINCIPAL_DUE)OVER(PARTITION BY LOAN_KEY ORDER BY FMD_WEEK_END ASC) AS OUSTANDING_PREV_WEEK
FROM MARGINAL_LOANS_FMD_DATA
) AS SUB_QUERY
GROUP BY 1
)
SELECT A1.WEEK_END AS WEEK_END_DATE
, A1.NUMBER_OF_MARGINAL_CUSTOMERS
, A1.NUMBER_OF_RMR_CUSTOMERS
, A1.NUMBER_OF_SUSPENDED_CUSTOMERS
, SUM(A4.MARGINAL_ORIGINATIONS_THIS_WEEK)OVER(ORDER BY A1.WEEK_END ASC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUMULATIVE_ORIGINATIONS
, A2.NUM_MARGINAL_ENTER_ACCOUNTS_THIS_WEEK
, COALESCE(A3.NUM_RMR_ENTER_ACCOUNTS_THIS_WEEK,0) AS NUM_RMR_ENTER_ACCOUNTS_THIS_WEEK
, A4.MARGINAL_ORIGINATIONS_THIS_WEEK
, A4.MARGINAL_DRAWS_THIS_WEEK
--------TOTAL OUTSTANDING FROM THE LOANS
, A5.TOTAL_OUTSTANDING
--------SPLIT BY TENURES
, A5.TOTAL_OS_TENURE_5
, A5.TOTAL_OS_TENURE_3_5
, A5.TOTAL_OS_TENURE_1_3
, A5.TOTAL_OS_TENURE_12MON
, A5.TOTAL_OS_TENURE_6MON
--------TOTAL DPD OUSTANDING FROM THESE LOANS
, A5.TOTAL_DPD_OUTSTANDING
--------SPLIT BY TENURE
, A5.TOTAL_DPD_OS_TENURE_5
, A5.TOTAL_DPD_OS_TENURE_3_5
, A5.TOTAL_DPD_OS_TENURE_1_3
, A5.TOTAL_DPD_OS_TENURE_12MON
, A5.TOTAL_DPD_OS_TENURE_6MON
----------PERCENTAGE DPD OUSTANDING--------------------
, TOTAL_DPD_OUTSTANDING/TOTAL_OUTSTANDING AS PERCENTAGE_DPD_OUTSTANDING
----------SPLIT BY TENURE
, CASE WHEN TOTAL_OS_TENURE_5 <> 0 THEN TOTAL_DPD_OS_TENURE_5/TOTAL_OS_TENURE_5 END AS PERCENTAGE_DPD_OUTSTANDING_TENURE_5
, CASE WHEN TOTAL_OS_TENURE_3_5 <> 0 THEN TOTAL_DPD_OS_TENURE_3_5/TOTAL_OS_TENURE_3_5 END AS PERCENTAGE_DPD_OUTSTANDING_TENURE_3_5
, CASE WHEN TOTAL_OS_TENURE_1_3 <> 0 THEN TOTAL_DPD_OS_TENURE_1_3/TOTAL_OS_TENURE_1_3 END AS PERCENTAGE_DPD_OUTSTANDING_TENURE_1_3
, CASE WHEN TOTAL_OS_TENURE_12MON <> 0 THEN TOTAL_DPD_OS_TENURE_12MON/TOTAL_OS_TENURE_12MON END AS PERCENTAGE_DPD_OUTSTANDING_TENURE_12MON
, CASE WHEN TOTAL_OS_TENURE_6MON <> 0 THEN TOTAL_DPD_OS_TENURE_6MON/TOTAL_OS_TENURE_6MON END AS PERCENTAGE_DPD_OUTSTANDING_TENURE_6MON
----------SPLIT BY DPD BUCKETS
, A5.TOTAL_DPD_OUSTANDING_BUCKET_1
, A5.TOTAL_DPD_OUSTANDING_BUCKET_2
, A5.TOTAL_DPD_OUSTANDING_BUCKET_3
, A5.TOTAL_DPD_OUSTANDING_BUCKET_4
, A5.TOTAL_DPD_OUSTANDING_BUCKET_5
, A5.NUMBER_OF_DPD_CUSTOMERS
, A5.NUMBER_DPD_OUSTANDING_BUCKET_1
, A5.NUMBER_DPD_OUSTANDING_BUCKET_2
, A5.NUMBER_DPD_OUSTANDING_BUCKET_3
, A5.NUMBER_DPD_OUSTANDING_BUCKET_4
, A5.NUMBER_DPD_OUSTANDING_BUCKET_5
, A5.TOTAL_MARGINAL_CHARGEOFF
, A6.TOTAL_OUTSTANDING_BUCKET_2_THIS_WEEK
-------------------ROLL RATES--------------
, ROUND(COALESCE(A6.PERCENTAGE_DOLLAR_ROLL_RATE,0),4) AS PERCENTAGE_DOLLAR_ROLL_RATE
-------------------
, ROUND(COALESCE(A6.PERCENTAGE_DOLLAR_ROLL_RATE_BUCKET_1_2,0),4) AS PERCENTAGE_DOLLAR_ROLL_RATE_1_2
, ROUND(COALESCE(A6.PERCENTAGE_DOLLAR_ROLL_RATE_BUCKET_2_3,0),4) AS PERCENTAGE_DOLLAR_ROLL_RATE_2_3
, ROUND(COALESCE(A6.PERCENTAGE_DOLLAR_ROLL_RATE_BUCKET_3_4,0),4) AS PERCENTAGE_DOLLAR_ROLL_RATE_3_4
, ROUND(COALESCE(A6.PERCENTAGE_DOLLAR_ROLL_RATE_BUCKET_4_5,0),4) AS PERCENTAGE_DOLLAR_ROLL_RATE_4_5
, ROUND(COALESCE(A6.PERCENTAGE_DOLLAR_ROLL_RATE_BUCKET_5_CO,0),4) AS PERCENTAGE_DOLLAR_ROLL_RATE_5_CO
, A6.TOTAL_OUTSTANDING_DELINQUENT_THIS_WEEK AS OS_DPD_1_7_THIS_WEEK
, A6.TOTAL_OUTSTANDING_NON_DELINQUENT_PREV_WEEK AS OS_DPD_0_PREV_WEEK
FROM STOCK_VIEW AS A1
LEFT JOIN MARGINAL_ENTER_CUSTOMERS AS A2 ON A1.WEEK_END = A2.MARGINAL_POP_SEGMENT_START_WEEK_END
LEFT JOIN RMR_ENTER_CUSTOMERS AS A3 ON A1.WEEK_END = A3.RMR_POP_SEGMENT_START_WEEK_END
LEFT JOIN MARGINAL_ORIGINATIONS AS A4 ON A1.WEEK_END = A4.WEEK_END
LEFT JOIN AGGREGATED_DPD_METRICS AS A5 ON A1.WEEK_END = A5.FMD_WEEK_END
LEFT JOIN ROLL_RATE AS A6 ON A1.WEEK_END = A6.FMD_WEEK_END
WHERE A1.WEEK_END >= '2024-06-05' AND A1.WEEK_END <= CURRENT_DATE;

